### ISSUE TITLE
Need save and restore abilities

### ISSUE THREAD

**Issue by VoronyukM** [anteo/redmine_custom_workflows#1]
It will be great to have abilities to save custom workflows with name and description (e.g. as .rb files with special comments) and restore them from that files. Now I have to manually copy and paste the scripts into files to be able to keep versions in git.

**Comment by anteo** [comment]
Has implemented this in 0.1.1 (for Redmine 3 only), but can backport it also to Redmine 2 if needed.

**Comment by anteo** [comment]
Implemented in redmine-2 branch, please checkout or download release 0.0.6
