### ISSUE TITLE
running CW from console?

### ISSUE THREAD

**Issue by pyroit** [anteo/redmine_custom_workflows#10]
Hi,

is there a way to run a custom worklfow from the ruby console? I would like to set up a cron job which runs one of my custom workflows once a day.

Thank you very much

Kind Regards
Pyro

**Comment by anteo** [comment]
Custom workflows are not intended to run cron jobs. It runs only when issue updated/created.
If you want to run your own code in cron job, consider writing rake task. It's quite simple
Look into redmine/lib/tasks, there are some examples. Just create your own *.rake file, define task name, description and insert your code in `task` block

**Comment by anteo** [comment]
Then you can run rake task (from console or from crontab) with

     rake <task_name>

**Comment by pyroit** [comment]
ok thank you very much

**Comment by pyroit** [comment]
[CustomWorkflow.rake.txt](https://github.com/anteo/redmine_custom_workflows/files/476805/CustomWorkflow.rake.txt) but here redmine//lib/tasks

This can be called via corn or from the terminal. I created a user to trigger an custom workflow event. But any observable object can be used.
