### ISSUE TITLE
How to Copy Issue and move it to another workflow

### ISSUE THREAD

**Issue by mbalecr7** [anteo/redmine_custom_workflows#100]
Hy everyone,

I don't know how to copy a issue automatically after that the issue ratio is set to 100% and status is "Under Review", status changes to "Resolved". 

After the copy of the same issue I want that this copy started the new workflow.

I just started with this but I don't know how to continue : 

"BEFORE SAVING"

if @issue.done_ratio_changed?
  if @issue.done_ratio==100 && @issue.status_id==16
    @issue.status_id=5
    @need_create = status_id_changed? && !new_record?
  end
end  

"AFTER SAVING"

if @need_create
  issue = Issue.create!(
    :author => User.current,
    :project => project,
    :tracker => tracker,
    :assigned_to => author,
    :parent_issue_id => id,
    :subject => "subject",
    :description => "Description")
end

( This create a new issue but I want the copy of the issue that go to "done" ) 

Thank's a lots

**Comment by picman** [comment]
```ruby
issue_copy = @issue.copy
....
issue_copy.save!
```
