### ISSUE TITLE
Сonditions for a specific user

### ISSUE THREAD

**Issue by finchmgn** [anteo/redmine_custom_workflows#105]
I created a logical field in the user profile. 
The idea is this when the user goes on vacation he puts a check in this field and can not be assigned to issue.
How can I get value from this field for specific user?

**Comment by picman** [comment]
I'd get it as follows.
```ruby
cv = CustomValue.where(customized_type: 'Principal', customized_id: your_user_id,
          custom_field_id: your_custom_field_id).first
filed_value = cv.value if cv
```
