### ISSUE TITLE
Error install on Redmine 2.6.1

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#11]
Hi,

<pre>
Migrating redmine_custom_workflows (Redmine Custom Workflow plugin)...
==  CreateExampleWorkflow: migrating ==========================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `find_by' for #<Class:0x0000000648c0f0>/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/sistema/redmine261a/plugins/redmine_custom_workflows/db/migrate/20150526132244_create_example_workflow.rb:4:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:370:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `ddl_transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/sistema/redmine261a/lib/redmine/plugin.rb:469:in `migrate_plugin'
/sistema/redmine261a/lib/redmine/plugin.rb:441:in `migrate'
/sistema/redmine261a/lib/redmine/plugin.rb:455:in `block in migrate'
/sistema/redmine261a/lib/redmine/plugin.rb:454:in `each'
/sistema/redmine261a/lib/redmine/plugin.rb:454:in `migrate'
/sistema/redmine261a/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
</pre>

Environment

<pre>
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.3
  custom_menu                    1.0.0
  redmine_checklists             3.1.1
  redmine_meetings               0.2.6
  redmine_pipeline_plugin        2.0.0
  redmine_time_tracker           0.4
  redmine_wiki_extensions        0.6.5
  redmine_wiki_lists             0.0.5
  release_logs                   0.1.1
  sidebar_hide                   0.0.7
</pre>

**Comment by anteo** [comment]
Try last version from repository branch 'redmine-2'
