### ISSUE TITLE
devel 1.0.0 on redmine 4.0.0 problem.

### ISSUE THREAD

**Issue by samatkiss** [anteo/redmine_custom_workflows#112]
Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.6.0-p0 (2018-12-25) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     

Your devel 1.0.0 plugin incompatible with the REDMINE CHECKLISTs by redmineup plugin.
The redmine_checklists plugin is official compatible with redmine 4.0.x so please consider to debug you code for final release.

Error:
Reproduce:
If you click on the settings menu under a project it will show internal error.
ProductionLog:
```
Completed 500 Internal Server Error in 218ms (ActiveRecord: 6.0ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0000000006871418>:0x00007efc04b7f0c8>
Did you mean? project_settings_tabs_with_checklists):
1: <h2><%=l(:label_settings)%></h2>
2:
3: <%= render_tabs project_settings_tabs >
4:
5: < html_title(l(:label_settings)) -%>

plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/projects_helper_patch.rb:27:in `project_settings_tabs'
plugins/redmine_checklists/lib/redmine_checklists/patches/projects_helper_patch.rb:37:in `project_settings_tabs_with_checklists'
plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/projects_helper_patch.rb:27:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___248793250993114950_69810438584860'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by picman** [comment]
I've just downloaded redmine_checklist 3.1.14 light version and there is no more _lib/redmine_checklists/patches/projects_helper_patch.rb file_.
Could you check the version of your plugin. Upgrade it to the last version and provide a feedback?

**Comment by samatkiss** [comment]
Dear Picman!

First of all, thanks for you quick reply and help!
I checked, and the version doesnt contain that file. Although the PRO version contains it!

How could i help you further?

**Comment by picman** [comment]
I'm not going to buy the PRO version to test it, so if you can send me zipped plugin, I'll investigate it.

**Comment by samatkiss** [comment]
I try to discuss with the developer team of that plugin.

**Comment by samatkiss** [comment]
Where can i send you a private e-mail with attachment?

**Comment by picman** [comment]
karel.picman@kontron.com

**Comment by samatkiss** [comment]
Thank you very much!
It seems OK now!
