### ISSUE TITLE
Install The Custom Workflows Error

### ISSUE THREAD

**Issue by maning34773694** [anteo/redmine_custom_workflows#113]
Dear @picman  
I installed the plugin devel-1.0.0 and get this error message.

![image](https://user-images.githubusercontent.com/47095271/51813050-4912ae80-22ef-11e9-92f7-0fc16637bde6.png)

Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.11.0
  Cvs                            1.12.13
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  select_to_select2              0.1.0

**Comment by picman** [comment]
Have you ran `bundle install`? act_as_list gem is in the plugin's dependencies.

**Comment by maning34773694** [comment]
Thank you for your help. It's ok after `bundle install`.
