### ISSUE TITLE
raise errors 

### ISSUE THREAD

**Issue by maning34773694** [anteo/redmine_custom_workflows#116]
Dear @picman 
      I can't raise errors. like
`errors.add '', 'Cannot close an item with Open children.'`
or 
`errors.add :base,'message'`
or
errors.add(:base,"Cannot close an item with Open children.")
   
     I use this `errors.add :base,'message'` before redmine 4.x and devel-1.0.0

**Comment by picman** [comment]
I think that `errors` belongs to the model, so you should call `@issue.errors.add` instead.

**Comment by maning34773694** [comment]
> I think that `errors` belongs to the model, so you should call `@issue.errors.add` instead.

it's not ok.

**Comment by picman** [comment]
What's not ok?

**Comment by maning34773694** [comment]
@issue.errors.add

**Comment by picman** [comment]
Hm, you're right. There is a change in Rails4 -> Rails 5. If you want to abort saving you must call something like that:
```ruby
errors.add :base, "An issue's error"
throw :abort
```
See related documentation [here](https://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html#module-ActiveRecord::Callbacks-label-Canceling+callbacks)

Maybe I can call `throw :abort` if there's an error present to keep existing user's scripts unchanged. What do you think?

**Comment by maning34773694** [comment]
I agree with you. It's better not change the scripts.
Thank you for your help.

**Comment by picman** [comment]
Fixed.
