### ISSUE TITLE
Redmine plugin page 

### ISSUE THREAD

**Issue by picman** [anteo/redmine_custom_workflows#117]
I've released v1.0.0 compatible with Redmine 4.0. I'd like to update the plugin's page on Redmine web too, but only the plugin's owner is allowed to do that. Could you update it?

http://www.redmine.org/plugins/custom-workflows

**Comment by TrumanRu** [comment]
@picman am I correctly understading this plugin will be compatible with Redmine 4.0+ only?

**Comment by picman** [comment]
Yes. There are plenty changes related to Rails5 and a backward compatibility with Redmine 3.x is practically impossible.

**Comment by maksnet2** [comment]
@picman  Здравствуйте. Подскажите, как скачать версию для Redmine 3? Если качаю 1.6, то он неправильно отображается в боковом меню.

**Comment by picman** [comment]
@maksnet2: Ano, ve verzi 1.6 je tato chyba. Buďto ji můžete manuálně opravit nebo je potřeba přejít na Redmine 4.0 a plugin 2.0.

**Comment by maksnet2** [comment]
@picman:  Понял. Спасибо.

**Comment by picman** [comment]
I've just registered this plugin again in [Redmine home page](https://www.redmine.org) as [Custom workflows plug-in](http://www.redmine.org/plugins/custom-workflows-plug-in).
