### ISSUE TITLE
PostgreSQL querry error

### ISSUE THREAD

**Issue by Skycast** [anteo/redmine_custom_workflows#119]
custom_workflow.rb querry
 where("is_for_all=? OR EXISTS (SELECT * FROM #{projects_join_table} WHERE project_id=? AND custom_workflow_id=id)", 1, project.id)
cause error on postgress  PG::UndefinedFunction: ERROR: operator does not exist: boolean = integer is_for_all=1

changing 1 to true fixing issue

**Comment by picman** [comment]
Fixed.
