### ISSUE TITLE
How to close version

### ISSUE THREAD

**Issue by telpina** [anteo/redmine_custom_workflows#121]
I want to close the version when the issue become close.
I find verstion as
vers = Version.find(@issue.fixed_version_id)
and it's work.
But I cannot change the status, I tried - 
vers.status = 'close'
 or
vers.update(status : 'close')

but it did not work

**Comment by picman** [comment]
```ruby
vers.status = 'closed'
```
Note **d** at the end.

**Comment by telpina** [comment]
> ```ruby
> vers.status = 'closed'
> ```
> 
> Notice **d** at the end.

Thank you!   vers.update(status: 'closed')  - is work!
