### ISSUE TITLE
Can I change the assignee of a Jenkins alerts 

### ISSUE THREAD

**Issue by Ajeeshb** [anteo/redmine_custom_workflows#123]
Hi,
I am using a single email address for creating tickets in Redmine. But these are assigned to Management team person. I have installed Custom workflows plugin in my redmine. Can I use this plugin to change the particular ticket and assign to the current working sprint in my redmine?

**Comment by picman** [comment]
Yes, you can change the issue in before or after scripts.

**Comment by Ajeeshb** [comment]
Do you have any example for me to check?

**Comment by picman** [comment]
https://github.com/anteo/redmine_custom_workflows/wiki
