### ISSUE TITLE
Creating new time entry

### ISSUE THREAD

**Issue by Spongar** [anteo/redmine_custom_workflows#125]
Hi,
there is a possibility to create new time entry (from issue level)? The following command returns an error message:

```ruby
te = TimeEntry.create!(
  :project_id => 1,
  :user_id => 6,
  :issue_id => 1,
  :hours => 3.0,
  :comments => "auto",
  :activity_id => 8,
  :spent_on => "2019-04-18",
  :tyear => 2019,
  :tmonth => 4,
  :tweek => 16,
  :created_on => "2019-04-18 09:00:00",
  :updated_on => "2019-04-18 09:00:00")
```
**WARNING: Can't mass-assign protected attributes for TimeEntry: user_id, tyear, tmonth, tweek
        app/models/time_entry.rb:94:in `initialize'
ActiveRecord::RecordInvalid: Validation failed: User cannot be blank
(...)**

**Comment by picman** [comment]
Try a different approach:
```ruby
te = TimeEntry.new
te.project_id = 1
te.user_id = 6
...
te.save!
```

**Comment by Spongar** [comment]
It works, thanks a lot!
