### ISSUE TITLE
How do I know , in redmine , what classes and their attributes and methods are there ?

### ISSUE THREAD

**Issue by sosogh** [anteo/redmine_custom_workflows#127]
redmine_custom_workflows  is a amazing  plugin.

Now I want to force redmine user to submit a new comment (note) whenever the status of a issue is changed .
I know I can "program" it within redmine_custom_workflows . 
I am new to ruby and redmine , and  a question that how do I know that what class and the related attribute and method in redmine?

for example:

`if subject.present?
    self.add_watcher(User.current) unless watched_by?(User.current)
end
`

How do I know , in redmine ,there is a class  "subject" and it has a  attribute  "present"?
What keyword should I use when program it ?
Thank you !

**Comment by picman** [comment]
There is no other way than to look into the Redmine's source codes.
