### ISSUE TITLE
undefined method `custom_email'

### ISSUE THREAD

**Issue by georgeming0331** [anteo/redmine_custom_workflows#128]
Hi, I am trying to use your plugin's feature to send custom email.

But I get undefined error no matter I tried to call `custom_email` or `deliver_custom_email`. 

Is this command still working? Or did I miss something?

Please see attached photos for the error message.
Thank you so much!

![custom_email](https://user-images.githubusercontent.com/24454512/57670964-3032cc80-7644-11e9-8cc2-60b5dac38ff0.PNG)
![deliver_custom_email](https://user-images.githubusercontent.com/24454512/57670965-32952680-7644-11e9-9d90-8e71ba2a303b.PNG)

**Comment by picman** [comment]
I had to rewrite it. The new method call looks like follows:
```ruby
CustomWorkflowMailer.deliver_custom_email(issue.author, 'Subject', 'Body')
```
