### ISSUE TITLE
Automatic issue generation from Checklist

### ISSUE THREAD

**Issue by karagounis78** [anteo/redmine_custom_workflows#129]
Hi to everyone,
I'm evaluating the opportunity to install the plugin in my company Redmine instance. My purpose is to use it for creating approval workflow for internal procedures. 

One of the target would be to generate automatic issue corresponding to flagged items in issue checklist. Does anyone has experience of link between custom_orkflow and checklist plugin (https://www.redmine.org/plugins/redmine_checklists)?

Or do you have any idea for automatically creating some tasks starting from status change in another issue?

Fabio

**Comment by AirTibu** [comment]
Hi,

Maybe this helps:

```
if self.status_id_changed? && !self.new_record?  && self.status_id==2 && self.checklists.present?

    approvals = self.checklists.where(:is_done => 'true').sort.pluck(:subject)

       unless approvals.blank?

              approvals.each do |cl_item| 
                        cl_issue = Issue.new(
                            :author => User.current,
                            :project => project,
                            :tracker => tracker,
                            :subject => cl_item.to_s)
                        cl_issue.save!
        end
    end
end
```

**Comment by karagounis78** [comment]
Thanks AirTibu.
I have changed the tool for my target, but the solution can be useful in any case. If possible I'll try it.

Fabio
