### ISSUE TITLE
Redmine 4.0.x, 4.1.x compatibility

### ISSUE THREAD

**Issue by tanertas** [anteo/redmine_custom_workflows#130]
I can't see any git commit or any comment related with Redmine 4.x compatibility. Is this work is progress?

**Comment by picman** [comment]
If you read README.md, at the end is written that the plugin is compatible with Redmine 4.x. Concerning Redmine 4.1 I don't know but for sure it's working with Redmine 4.0.0.

**Comment by tanertas** [comment]
Oh, sorry I didn't notice that. Thank you for response.
