### ISSUE TITLE
Always set default assignee during project change

### ISSUE THREAD

**Issue by tanertas** [anteo/redmine_custom_workflows#131]
If I move an issue to another project, I want to make sure that assignee will set automatically to default assignee of that project. Can I do this with redmine_custom_workflows plugin?

**Comment by boki69** [comment]
Try this code, and set on all destination projects, where you want to move issues:

if @issue.project_id_changed?
        @issue.assigned_to_id = Project.find(@issue.project_id).default_assignee_id
end

**Comment by tanertas** [comment]
Thank you very much. Can we modify script like "if @issue.project_id_changed? && !@issue.assigned_to_id_changed" in order make it work only when project_id changed. If both project_id and assigned_to_id changed (which means deliberately selected assignee), code must not to be executed.

**Comment by AirTibu** [comment]
Hi,

Yes, you can do it. 
```

if project_id_changed? && assigned_to_id_changed?
  self.assigned_to_id = Project.find(project_id).default_assignee_id
end

```

**Comment by tanertas** [comment]
@AirTibu  Thank you. This will probably work.
