### ISSUE TITLE
custom_email not working

### ISSUE THREAD

**Issue by pizfantast** [anteo/redmine_custom_workflows#132]
Hi!
I need to send an email notification to the user if a new project has been created.

wiki example does not work
```
error: undefined method 'custom_email' for Mailer:Class

Mailer.custom_email(:to => 'user@example.net', :text_body => 'Hi!').deliver
```
this code does not work too
`CustomWorkflowMailer.deliver_custom_email(User.current, 'Subject', 'Body')`

How can I send custom mail without modifying the source code?
Thank you for any help

**Comment by picman** [comment]
Duplicates #128.
