### ISSUE TITLE
Adding user custom field to the first comment.

### ISSUE THREAD

**Issue by tanertas** [anteo/redmine_custom_workflows#133]
We have some custom fields for users like department, telephone etc. We trying to find a way to embed these fields to the first comment as footer/header. Thus these information will be available on notification emails. Is such thing doable with redmine_custom_workflows ?

**Comment by picman** [comment]
I don't think so. Custom workflows' hooks are triggered by object changes. You can modify these or related objects in these hooks but you can modify email notifications. They are independent.

**Comment by tanertas** [comment]
Actually, I didn't meant to directly modify email notifications. I just wanted to put some extra info from user custom fields  to the first comment.

**Comment by picman** [comment]
Which comment?

**Comment by tanertas** [comment]
> Which comment?
I mean, the first created comment/note (whatever you call) when creating an issue.

**Comment by picman** [comment]
You can try something like this:
```ruby
footer = ''
User.current.custom_values.each do |cv|
  footer << "#{cv.custom_field.name} : #{cv.value}\n" 
end
@issue.init_journal User.current, footer
@issue.save
```

**Comment by tanertas** [comment]
Thank you. But it didn't work.
Closing btw.
