### ISSUE TITLE
Find a user by role id

### ISSUE THREAD

**Issue by vdkri** [anteo/redmine_custom_workflows#136]
Hi. 
I need to find the user by the role id in the project. If more than one is found, take the first element of the array. How can I get value ?

**Comment by picman** [comment]
E.g.:
```ruby
members = project.users_by_role
users = members[role]
user = users.first
```

**Comment by vdkri** [comment]
Thanks for the answer. But I'm a little confused.
users.first returns nil. 
Users contains the following:
` #<Role id: 19, name: "role", position: 14, assignable: true, builtin: 0, permissions: [:see_all_project_timesheets, :see_project_timesheets, :select_project_modules, :close_project, :edit_project, :add_subprojects, :add_project, :save_queries, :manage_versions, :manage_public_queries, :manage_project_workflow, :manage_members, :manage_activity_report_settings, :add_agile_queries, :manage_agile_verions, :view_agile_charts, :view_agile_queries, :manage_public_agile_queries, :add_messages, :view_messages, :edit_own_messages, :edit_messages, :delete_own_messages, :delete_messages, :manage_boards, :view_calendar, :add_notes, :add_contacts, :manage_contacts, :view_contacts, :view_private_contacts, :edit_contacts, :delete_notes, :delete_contacts, :delete_own_notes, :manage_contact_issue_relations, :display_system_folders, :email_documents, :file_approval, :user_preferences, :view_dmsf_file_revision_accesses, :view_dmsf_file_revisions, :view_dmsf_files, :view_dmsf_folders, :force_file_unlock, :file_delete, :folder_manipulation, :manage_workflows, :file_manipulation, :add_documents, :view_documents, :edit_documents, :delete_documents, :edit_baselines, :view_baselines, :view_easy_gantt, :view_global_easy_gantt, :view_personal_easy_gantt, :edit_personal_easy_gantt, :edit_easy_gantt, :edit_global_easy_gantt, :eq_manage_query_categories, :view_files, :manage_files, :view_gantt, :create_tags, :edit_tags, :done_checklists, :add_issues, :add_issue_watchers, :add_issue_notes, :import_issues, :copy_issues, :view_checklists, :view_issues, :view_issue_view_stats, :view_private_notes, :view_issue_watchers, :set_notes_private, :edit_issues, :edit_issue_notes, :edit_own_issue_notes, :edit_checklists, :delete_issues, :delete_issue_watchers, :manage_categories, :manage_subtasks, :manage_issue_relations, :set_issues_private, :set_own_issues_private, :comment_news, :view_news, :manage_news, :commit_access, :view_changesets, :browse_repository, :manage_related_issues, :manage_repository, :view_time_entries, :edit_own_time_entries, :edit_time_entries, :manage_project_activities, :log_time, :protect_wiki_pages, :rename_wiki_pages, :view_wiki_pages, :view_wiki_edits, :edit_wiki_pages, :delete_wiki_pages, :delete_wiki_pages_attachments, :manage_wiki, :export_wiki_pages], issues_visibility: "all", users_visibility: "all", time_entries_visibility: "all", all_roles_managed: true, settings: {"permissions_all_trackers"=>{"view_issues"=>"1", "add_issues"=>"1", "edit_issues"=>"1", "add_issue_notes"=>"1", "delete_issues"=>"1"}, "permissions_tracker_ids"=>{"view_issues"=>[], "add_issues"=>[], "edit_issues"=>[], "add_issue_notes"=>[], "delete_issues"=>[]}}>=>[#<User id: 94, login: "d.bogov", hashed_password: "", firstname: "Денис", lastname: "Богов", admin: false, status: 1, last_login_on: "2019-08-23 06:12:10", language: "ru", auth_source_id: 1, created_on: "2019-01-24 14:04:35", updated_on: "2019-01-24 14:04:35", type: "User", identity_url: nil, mail_notification: "only_my_events", salt: nil, must_change_passwd: false, passwd_changed_on: nil, reminder_notification: nil>]}`

**Comment by picman** [comment]
Concerning my code snippet you must enter an existing role there, e.g.

```ruby
members = project.users_by_role
role = Role.find 19
users = members[role]
user = users.first
```

And, of course, there must exist a member of such role.

**Comment by vdkri** [comment]
Thank you very much
