### ISSUE TITLE
It is possible to change issue status an hour later

### ISSUE THREAD

**Issue by msslava** [anteo/redmine_custom_workflows#139]
It is possible to change issue status after 1 hour passed?
For example, I created issue.
An hour later, the status automatically changed.

**Comment by picman** [comment]
I'd use `Concurent::TimerTask` - https://www.rubydoc.info/gems/concurrent-ruby/Concurrent/TimerTask
```ruby
if @issue
  task = Concurrent::TimerTask.new(run_now: true) do |t|
    sleep 3600 # 1hour
    @issue.reload
    @issue.done_ratio = 10  
    @issue.save
    t.shutdown
   end
   task.execute
end
```
