### ISSUE TITLE
Problem with pt-br locale

### ISSUE THREAD

**Issue by w0www** [anteo/redmine_custom_workflows#14]
ActionView::Template::Error (can not load translations from /home/entelibai/redmine/plugins/redmine_custom_workflows/config/locales/pt-br.yml: #<Psych::SyntaxError: (/home/entelibai/redmine/plugins/redmine_custom_workflows/config/locales/pt-br.yml): did not find expected key while parsing a block mapping at line 2 column 3>):
    2: <%= form_tag({:action => 'default_configuration'}) do %>
    3:     <%= simple_format(l(:text_no_configuration_data)) %>
    4:     <p><%= l(:field_language) %>:
    5:     <%= select_tag 'lang', options_for_select(lang_options_for_select(false), current_language.to_s) %>
    6:     <%= submit_tag l(:text_load_default_configuration) %></p>
    7: <% end %>
    8: </div>
  lib/redmine/i18n.rb:167:in `init_translations'
  lib/redmine/i18n.rb:181:in `lookup'
  lib/redmine/i18n.rb:98:in `block in languages_options'
  lib/redmine/i18n.rb:98:in `select'
  lib/redmine/i18n.rb:98:in `languages_options'
  lib/redmine/i18n.rb:103:in `block in languages_options'
  lib/redmine/i18n.rb:102:in `languages_options'
  app/helpers/application_helper.rb:1041:in `lang_options_for_select'
  app/views/admin/_no_data.html.erb:5:in `block in _app_views_admin__no_data_html_erb__3287497614057199964_70204844916560'
  app/views/admin/_no_data.html.erb:2:in `_app_views_admin__no_data_html_erb__3287497614057199964_70204844916560'
  app/views/admin/index.html.erb:4:in `_app_views_admin_index_html_erb___1187172352493287663_70204844797340'

This happened today. In a new installation. In my older copy dont happened this

**Comment by anteo** [comment]
Fixed

**Comment by w0www** [comment]
:D THANKS!!!!!
