### ISSUE TITLE
Error install in Redmine 4.0.4

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#140]
Hi! I get this error, when i install plugin.
Gem::InstallError: acts_as_list requires Ruby version >= 2.4.7.
An error occurred while installing acts_as_list (1.0.0), and Bundler cannot continue.
Make sure that `gem install acts_as_list -v '1.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

**Comment by TrumanRu** [comment]
Use the fork https://www.redmine.org/plugins/custom-workflows-plug-in

**Comment by picman** [comment]
@TrumanRu The fork you refer is this plugin.

@koren85 Fix the reported errors. Ruby 2.5 is obviously required.
