### ISSUE TITLE
Bug when using PT-BR

### ISSUE THREAD

**Issue by rafaelmartinsrm** [anteo/redmine_custom_workflows#141]
There's an error on PT-BR locale that is forcing Redmine use PT.

**Comment by picman** [comment]
Any details how to reproduce it?

**Comment by rafaelmartinsrm** [comment]
Actually I just installed the plugin and when forcing PT-BR on redmine settings to users it actually uses PT.

**Comment by rafaelmartinsrm** [comment]
Removing redmine_custom_workflows/config/locales/pt-BR.yml seems to solve the issue, which looks like there is something wrong with that file.

**Comment by picman** [comment]
Fixed. Either update your master branch or fix it manually according to the related commit.
