### ISSUE TITLE
question:  append current assignee to a user type custom field with multiple value allowed

### ISSUE THREAD

**Issue by tainewoo** [anteo/redmine_custom_workflows#144]
Thank you in advance.

I'm thinking about this usage:
There is a custom field in issue, which is User format, and multiple value is allowed.
What's the method to append current assignee to the value of the custom field before save?  consider the old value of it is empty or not empty.

And if i want to also append string to the notes with the new assignee's name in the string, such as, append this word to the notes:
xxxxx (assignee name), please xxxxxxxx.
How to implement this? also, consider the original notes is empty or not empty.

**Comment by tainewoo** [comment]
need help, please~~

**Comment by boki69** [comment]
Hi tainewoo,

This my code, maybe resolve your problem.
In my example, 222 is the id of the user type custom field.


> users_cf=[]
> users_cf=@issue.custom_field_values(222)
> users_cf << User.current.id
> @issue.custom_field_values={'222' => users_cf}
>

**Comment by tainewoo** [comment]
Hi @boki69 ,

Thank you for your help, i just tried the same way to implement it, and checked it works.
And after that, i tried sort and uniq but seems not working. 
Do you have any clue?

**Comment by boki69** [comment]
Hi @tainewoo 

1.- 
Yout question:

> And after that, i tried sort and uniq but seems not working.
Do you have any clue?

What would You like to sort and uniq?


2.-
Your question:

> And if i want to also append string to the notes with the new assignee's name in the string, such as, append this word to the notes:
xxxxx (assignee name), please xxxxxxxx.
How to implement this? also, consider the original notes is empty or not empty.

My code (before save, issue type custom workflow):

> append_to_note="\r\n xxxxx (" + User.current.lastname + " " + User.current.firstname +"), please xxxxxxxx."
if !@issue.notes.nil?
    @issue.notes << append_to_note
end

**Comment by tainewoo** [comment]
Hi @boki69 
The sort and uniq problem is reolved.
And thank you so much for your code of append_to_note, thank you for help solve my problems.
