### ISSUE TITLE
doc: method not working to check multiple value custom field changed?

### ISSUE THREAD

**Issue by tainewoo** [anteo/redmine_custom_workflows#145]
The method to detect if the custom field value changed or not only works for single value custom fields, and it's not working for multiple value custom fields, such as multiple value list or key/value list.
Because for multiple value custom fields, the return of ustom_field_value(cf.id) would be:
=> ["12", "13"]
And even only single value is set, the return would be:
=> ["12"]
And, no matter how many values set to the custom field, the custom_value_for(cf.id) return would be only the first value, and without [""] part:
=>12
So it only works for single value custom fields.

From FQA:

> 
> def custom_value_changed?(cf)
> 	custom_field_value(cf.id) != custom_value_for(cf.id).try(&:value)
> end

**Comment by tainewoo** [comment]
is there kind of xxx_was and xxx_changed? or xxx.changed? for issue's custom field value?

**Comment by boki69** [comment]
Hi @tainewoo,

I agree with you, that code doesn't work for me too.

Here is my code to solve your problem (Issue type before save event):

> def multi_custom_value_changed?(cf_id)
  Issue.find(@issue.id).custom_field_value(cf_id).sort != @issue.custom_field_value(cf_id).sort
end

**Comment by tainewoo** [comment]
Hi @boki69 

This code looks good to me, I will try to use it, thank you so much boki.

**Comment by tainewoo** [comment]
Hi @boki69 ,

How about .uniq.sort, in case of some codes changed the value and before save, sometimes there will be repeated values.

```
def multi_custom_value_changed?(cf_id)
Issue.find(@issue.id).custom_field_value(cf_id).uniq.sort != @issue.custom_field_value(cf_id).uniq.sort
end
```

**Comment by tainewoo** [comment]
Hi @boki69 ,

Seems now we have a overall method to check custom field changed? for both single value or multiple value custom fields


```
def custom_value_changed?(cf_id)
   if [Issue.find(@issue.id).custom_field_value(cf_id)].uniq.sort != [@issue.custom_field_value(cf_id)].uniq.sort
end
```

**Comment by yurmala** [comment]
I don't understand, how use it method? Can you put example?

**Comment by jcatrysse** [comment]
> ```
> def custom_value_changed?(cf_id)
>    if [Issue.find(@issue.id).custom_field_value(cf_id)].uniq.sort != [@issue.custom_field_value(cf_id)].uniq.sort
> end
> ```

I think this needs some modifications (I'm not a programmer, so please optimize as needed). In the above method the `if` is not ok.

This is what I use:
``` ruby
def custom_value_changed?(cf_id)
  @current_value = nil
  @new_value = nil
  if Issue.find(@issue.id).custom_field_value(cf_id).respond_to?(:sort)
    @current_value = Issue.find(@issue.id).custom_field_value(cf_id).uniq.sort
    @new_value = @issue.custom_field_value(cf_id).uniq.sort
  else
    @current_value = [Issue.find(@issue.id).custom_field_value(cf_id)]
    @new_value = [@issue.custom_field_value(cf_id)]
  end
  @current_value.uniq.sort != @new_value.uniq.sort
end
```

``` ruby
if custom_value_changed?(custom_field_id)
 dosomething
end
```
