### ISSUE TITLE
custom workflows before showing issues or other objects

### ISSUE THREAD

**Issue by tainewoo** [anteo/redmine_custom_workflows#148]
is it possible to modify some of the attributes/values before showing the issues or other ojbects?
such as, according to some criteria, and hide some of the options of some of the custom fields before showing the issue, or before showing the issue edit?

**Comment by boki69** [comment]
Hi @tainewoo,

I think you can't do that with this plugin.
You can use redmine_custom_js plugin to manipulate field values in browser.
