### ISSUE TITLE
Error install on redmine 4.1.0

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#153]
Hi

Installing plugin on redmine 4.1.0 clean without plugin  showed the error
Thanks!

(in /var/www/redmine-4.1.0)
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x0000559aebce7058>
/home/redmine/.rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/home/redmine/.rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/var/www/redmine-4.1.0/config/application.rb:18:in `<top (required)>'
/var/www/redmine-4.1.0/Rakefile:5:in `require'
/var/www/redmine-4.1.0/Rakefile:5:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

**Comment by picman** [comment]
Duplicates #149.
