### ISSUE TITLE
Is it possible to change current user?

### ISSUE THREAD

**Issue by oamoris** [anteo/redmine_custom_workflows#158]
I have bot user which is author of many autocreated issues. When I changing status of issue I want to use authors' externded workflow (standard redmine workflow) rights for that issue. 
So I need to change current user to bot user with prevelege rights, like sudo in linux.
Is it possible?

**Comment by picman** [comment]
Not sure, but I'd try something like that:

```ruby
original_user = User.current
User.current = new_user
...
User.current = original_user
```

**Comment by lcasanova78** [comment]
Thank you very much, I have one more question.
How can I know if a user has the External Developer role?

Thank you, Luis.
