### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by nervolsergey** [anteo/redmine_custom_workflows#16]
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.1.3-p242 (2014-09-19) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.4
  ajax_counters                  0.0.1
  custom_menu                    1.5.0
  extra_queries                  1.0.2
  first_mail_answer              0.0.1
  it25_interface                 0.0.1
  luxury_buttons                 2.2.0
  redmine_open_links_in_new_window 0.0.3
  rm_user_mentions               0.0.1
  unread_issues                  1.0.0
  usability                      1.0.0

When trying to install plugin there is error in file: 20150526132244_create_example_workflow.rb
I removed that file and repeat execute command: rake redmine:plugins:migrate --trace RAILS_ENV=production

Plugin installed succesfully but when try to enter any project settings page there was an error:

`PG::SyntaxError: ERROR: non-integer constant in ORDER BY LINE 1: SELECT 1 AS one FROM "custom_workflows" ORDER BY '--- ^ : SELECT 1 AS one FROM "custom_workflows" ORDER BY '--- :position: :asc ' LIMIT 1 `

Full error trace:

        Лог ошибки
    
            /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `exec_no_cache'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1262:in `select'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/relation/finder_methods.rb:202:in `exists?'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/querying.rb:5:in `exists?'
    /var/www-root/redmine-2.6.1/plugins/redmine_custom_workflows/app/views/projects/settings/_custom_workflow.html.erb:6:in `block in _plugins_redmine_custom_workflows_app_views_projects_settings__custom_workflow_html_erb___776842098537356390_38390880'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/capture_helper.rb:40:in `capture'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/form_helper.rb:378:in `form_for'
    /var/www-root/redmine-2.6.1/plugins/redmine_custom_workflows/app/views/projects/settings/_custom_workflow.html.erb:1:in `_plugins_redmine_custom_workflows_app_views_projects_settings__custom_workflow_html_erb___776842098537356390_38390880'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:145:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:125:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:143:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:237:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:41:in `render_partial'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:15:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/rendering_helper.rb:24:in `render'
    /var/www-root/redmine-2.6.1/app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__166398606193287121_70006676859380'
    /var/www-root/redmine-2.6.1/app/views/common/_tabs.html.erb:21:in `each'
    /var/www-root/redmine-2.6.1/app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__166398606193287121_70006676859380'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:145:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:125:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:143:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:237:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:41:in `render_partial'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:15:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/helpers/rendering_helper.rb:24:in `render'
    /var/www-root/redmine-2.6.1/app/helpers/application_helper.rb:328:in `render_tabs'
    /var/www-root/redmine-2.6.1/app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___465503258230998837_70006672325520'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:145:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:125:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/template.rb:143:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:18:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:36:in `render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:17:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:110:in `_render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/streaming.rb:225:in `_render_template'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:103:in `render_to_body'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:88:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:16:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
    /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in `ms'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:39:in `render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:513:in `_run__3600200384928874493__process_action__4343983155749642660__callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
    /usr/local/rvm/gems/ruby-2.1.3/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__1609130968381141785__call__3434552608062777507__callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
    /usr/local/rvm/gems/ruby-2.1.3/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
    /usr/local/rvm/gems/ruby-2.1.3/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /usr/local/rvm/gems/ruby-2.1.3/gems/passenger-5.0.8/lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
    /usr/local/rvm/gems/ruby-2.1.3/gems/passenger-5.0.8/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
    /usr/local/rvm/gems/ruby-2.1.3/gems/passenger-5.0.8/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
    /usr/local/rvm/gems/ruby-2.1.3/gems/passenger-5.0.8/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
    /usr/local/rvm/gems/ruby-2.1.3/gems/passenger-5.0.8/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by anteo** [comment]
Hello,
It seems you are trying to install the latest version of redmine_custom_workflows >= 0.1.0 on Redmine 2.6.4. Support of Redmine 2.x.x has dropped with version 0.0.6 of the plugin.
Please download version 0.0.6 from http://www.redmine.org/plugins/custom-workflows or checkout redmine-2 branch
