### ISSUE TITLE
Overwrite to workflow

### ISSUE THREAD

**Issue by atopcu** [anteo/redmine_custom_workflows#162]
Hi,
Is it possible to overwrite workflow?
I wants change issue status to that not exist in their workflow.

BR

**Comment by AirTibu** [comment]
Hi,

You can try this in before save:

`
WorkflowTransition.find(workflows_id).update(:tracker_id => 'tracker_id ',:old_status_id => 'old_status_id ',:new_status_id => 'new_status_id ',:role_id => 'role_id ')
`

Something like this with ids:

`
WorkflowTransition.find(5736).update(:tracker_id => '28',:old_status_id => '2',:new_status_id => '6',:role_id => '10')
`

I hope this helps!
