### ISSUE TITLE
Check last version of plugin KO

### ISSUE THREAD

**Issue by ludovicandrieux** [anteo/redmine_custom_workflows#168]
Hi,

When i go to /admin/plugins in my redmine instance, i try to check last version.
The response for this plugin : unknown plugin

Other plugins in my list works fine and found the last version

A screenshot
![2020-05-11_160405](https://user-images.githubusercontent.com/11213740/81571024-ad9d3400-93a1-11ea-9fdb-996d5b7226d3.png)

Best regards

**Comment by picman** [comment]
In my Redmine no such a feature is available. Do you use an extension?
![image](https://user-images.githubusercontent.com/779003/81572282-50a27d80-93a3-11ea-8f13-ffe8fe35ee1a.png)

**Comment by picman** [comment]
There was an old URL. Could you try it again with updated devel branch.

**Comment by ludovicandrieux** [comment]
Nothing change. I don't get your branch.
Just appliy your commit ( https://github.com/anteo/redmine_custom_workflows/commit/5dd32b6251670cd36469ac30889a3e5fb7daa5f3 ) in my instance manualy.

You are in the query of the request :
![2020-05-11_163737](https://user-images.githubusercontent.com/11213740/81574195-cb6c9800-93a5-11ea-839d-a6e104a3860a.png)

But you are not in the response :
![2020-05-11_163718](https://user-images.githubusercontent.com/11213740/81574220-d32c3c80-93a5-11ea-824b-e16f8790e84b.png)

**Comment by picman** [comment]
Again. In my Redmine no such a feature is available. Do you use an extension?

**Comment by ludovicandrieux** [comment]
To see it, you only need to have one plugin installed.

You can see the test in the code of /app/views/admin/plugins.html.erb at line 3 => https://github.com/redmine/redmine/blob/dd9fa9c9a7850a38780552c93901839909dbdc47/app/views/admin/plugins.html.erb#L3

The link is at line 19 => https://github.com/redmine/redmine/blob/dd9fa9c9a7850a38780552c93901839909dbdc47/app/views/admin/plugins.html.erb#L19

I use the non official repo of redmine but it's a safe mirror

**Comment by picman** [comment]
Fixed. The problem was that the plugin's id didn't correspond to redmine.org plugin's id.

**Comment by ludovicandrieux** [comment]
I confirm the fix. Thanks.
