### ISSUE TITLE
An easy one of custom fields

### ISSUE THREAD

**Issue by AdelRS** [anteo/redmine_custom_workflows#169]
I apologize if it's too easy, but this is my first approach to Redmine. What's wrong here?

if @issue.custom_field_values(47)==1
  @issue.status_id=16   
end

Error:
Workflow script executable before saving observable object contains error: wrong number of arguments (given 1, expected 0)

**Comment by picman** [comment]
The brackets?
```ruby
if @issue.custom_field_values[47]==1
@issue.status_id=16
end
````

**Comment by AdelRS** [comment]
Thank you very much.
