### ISSUE TITLE
Full support 2.6

### ISSUE THREAD

**Issue by pyroit** [anteo/redmine_custom_workflows#17]
Would it be possilbe support redmine < 3.0.0 again for the master version? So all the great current and upcoming changes will be also availible for 2.6?

Thank you 
Regards

**Comment by anteo** [comment]
Theoretically yes, I can support latest 2.6.x branch, but not older versions. Testing over multiple versions is a rather complicated. And supporting versions 1.x.x is a total pain.
I will investigate it in a few days.

**Comment by anteo** [comment]
I think I did it.

**Comment by pyroit** [comment]
Thank you very much!!!

**Comment by pyroit** [comment]
[CustomWorkflow.rake.txt](https://github.com/anteo/redmine_custom_workflows/files/476773/CustomWorkflow.rake.txt) but it here redmine/lib/tasks

For other with the same issue. I use this rake file for ether run from the Terminal (ruby bin/rake redmine:update_user_7 RAILS_ENV="production") or use cron.

I my case I created a user (user 7) , which I can use to trigger a custom workflow. So you can create another user or use just any other object. Remember to repalce the user number in with your own one in the rake file.
