### ISSUE TITLE
Retrieving value from key/value custom field

### ISSUE THREAD

**Issue by kty0mka** [anteo/redmine_custom_workflows#172]
When using key/value type custom fields `custom_field_value(cf_id)` returns us key (enumerator id).
Is there any way to fetch value?

**For example:**
Custom field (key/value) possible values:
* green
* black
* orange

I want test if my custom field has _orange_ value, but instead of set value I get _3_ (enumerator id of value "orange").

**Comment by AirTibu** [comment]
Hi,

Maybe you can use this:

`
CustomFieldEnumeration.where(:id=> custom_field_value(cf_id).to_s,:custom_field_id => 'cf_id').first
`

I hope this helps!

**Comment by kty0mka** [comment]
Hi @AirTibu,

Thanks! It works)
I think that second filter (`:custom_field_id => 'cf_id'`) is unnecessary, because every value has unique enumerator id.
Anyway thank you very much!
