### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by spbdimka** [anteo/redmine_custom_workflows#178]
I saw that you wrote customworkflowmailer, but how i can pass default templates to your mailer?

**Comment by spbdimka** [comment]
Or maybe its posible to pass html into mailer?

**Comment by AirTibu** [comment]
Hi,

Check this issue: #50 

There is the answer.

**Comment by spbdimka** [comment]
> Hi,
> 
> Check this issue: #50
> 
> There is the answer.

yes, thanks, its helped to use html tags, but question about using default redmine templates (such as mailer/issue_add) are opened.
When im trying to use Mailer, i got error `undefined method `custom_email' for Mailer:Class`, and CustomWorkflowMailer gets only address, subject and body parameters.

**Comment by AirTibu** [comment]
Hi,

Check this issue about mail templates: #34

**Comment by picman** [comment]
#330
