### ISSUE TITLE
Is it possible to reload a children sub task until main task  (grandparent or root issues)? 

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#179]
![2323](https://user-images.githubusercontent.com/50211455/89719420-b0bfb480-d9d0-11ea-82a9-c61bc80ce50d.png)
i need when i edit the last children (bill)#5530 and save it,the all subtasks  and main task only reloads (#4812,#3664,#3638) 
becuase im reload it manulay to recalculate its.
this mean if possible when im edit last subtask  after save it reload main task  and subtasks upper( grandparent or root issues)

**Comment by ashrafalzyoud** [comment]
@AirTibu 
@picman 
if u can help

**Comment by ashrafalzyoud** [comment]
#35

**Comment by AirTibu** [comment]
Hi,

Most probably there are some connection between levels, maybe you use some data for calculation, that's the reason why you want to recalculate all the levels.

Maybe the best way would be, if you add a code, which is running only on the lowest level and it's update all parent's fields step by step.

Could you please share with me what you want to update (recalculate) in the 'Tender', 'The electronic wallet', 'company' trackers?

Is it a custom field? If yes, what is the custom_field_id and what kind of data should be there?
Is it standard field, like start_date, due_date, subject, assignee, etc? If yes, then please explain what you want on update on it.

**Comment by ashrafalzyoud** [comment]
@AirTibu 
in my case its (custom field ) not standard field connection between levels
and the type of custom field its ( integer and float) numbers  need update
and parent's field take computed value  from child field
because that i need code to reload  issues to upper  when im save the (bill)
the user edit the issues until the tender manually
#35 like that
are there code depend in root.issue or parent.parent.issue

**Comment by ashrafalzyoud** [comment]
as example cfs[10],cfs[11] integar
                    cfs[12],cfs[13] float

**Comment by AirTibu** [comment]
Hi,

Ok, could you please provide me the information in this structure:

**Tender tracker:**

- What is the tracker id?

- Which custom field is calculated? I need the custom field id

- what is the exact calculation in the calculated field?

Next tracker 
Next tracker 
And soon...

**Comment by ashrafalzyoud** [comment]
as example
Tracker ( TENDER )
 tracker id =1
cfs[1]= float
cfs[2]= float
cfs[3]= float
Tracker (The electronic wallet)
tracker id =2
cfs[4]= float
cfs[5]= float
cfs[6]= float
Tracker (company)
tracker id =3
cfs[7]= float
cfs[8]= float
cfs[9]= float

what is the exact calculation in the calculated field?
im using computed_custom_field plugin
and there 
Calculations related to payments, allocations, assignments and financial savings
from bill to company to  The electronic wallet to Tenders 
thats why i need reload the subtasks to upper grand task to effect to tender issiue

**Comment by ashrafalzyoud** [comment]
like eaxmple
Traker bill (1) cfs[10] = 100$ ,Traker bill (2) cfs[10] = 100$
Traker company (1) cfs[9] = total cfs[10] =200$
Tracker wallet (1) cfs[6] =total companys[cf9]- 1000$
Tracker Tender  cfs[3]= result cfs[6] + 5000$
there many calcauations just need reload issiues or update cfs in each issiues

**Comment by ashrafalzyoud** [comment]
@AirTibu 
any feedback

**Comment by AirTibu** [comment]
Hi,

Honestly speaking I have no better idea, just this one:
```

if self.tracker_id == YOUR_BILL_TRACKER_ID
     self.parent.save
     self.parent.parent.save
     self.root.save
end

```

Replace the "YOUR_BILL_TRACKER_ID" with your tracker_id number.

**Comment by ashrafalzyoud** [comment]
before save or after save

**Comment by ashrafalzyoud** [comment]
Perfect perfect perfect 
👏👏👏👏

**Comment by AirTibu** [comment]
After save

**Comment by ashrafalzyoud** [comment]
Just to confirm
because this formula take time
its just only effect for (task 1,task2,task3,task4) --> self.tracker_id
or in  all tasks in same tracker (id) in same projects

**Comment by AirTibu** [comment]
Hi,

It has effect only on parents and not on all issues in tracker. See the below scenarios:

![image](https://user-images.githubusercontent.com/68789735/97788027-f34ef280-1bb5-11eb-861e-db9f9ac7a279.png)

![image](https://user-images.githubusercontent.com/68789735/97788046-25f8eb00-1bb6-11eb-97f5-5cba5e09c626.png)

![image](https://user-images.githubusercontent.com/68789735/97788054-3e690580-1bb6-11eb-8d7a-f8cf846670e3.png)

![image](https://user-images.githubusercontent.com/68789735/97788075-5d679780-1bb6-11eb-941e-ace90a25dd87.png)

I hope its help!

**Comment by ashrafalzyoud** [comment]
thx for you brother
perfect
this what i want
