### ISSUE TITLE
Proper way to early exit a custom workflow

### ISSUE THREAD

**Issue by go2null** [anteo/redmine_custom_workflows#18]
What is the proper way to early exit a custom workflow?

This is to avoid deep nesting of `if` statements and to provide better readability.

**Comment by anteo** [comment]
Currently you can do ```return true``` to exit current workflow and go on with the rest of workflows.
I will try to clarify this moment in future version and allow ```return``` or ```return true``` to exit workflow and continue; ```return false``` to stop executing workflow chain.

**Comment by anteo** [comment]
Done (in master)

**Comment by go2null** [comment]
Thank you @anteo!
