### ISSUE TITLE
Intercepting when watcher is added / removed

### ISSUE THREAD

**Issue by andreav** [anteo/redmine_custom_workflows#182]
Hello,
a client of mine would like to log on the issue if a user is added or removed as a watcher.

Is it possible using this plugin?

Thank you.

**Comment by AirTibu** [comment]
Hi,

There is no trigger for watchers add/remove in this plugin. You should check this plugin, which has similar functionality, if you modify it, it can works:

https://github.com/efigence/redmine_accounting

I hope it helps!

**Comment by andreav** [comment]
Thank you,  I'll try it!

**Comment by andreav** [comment]
Thank you, I will try it!

Il Mer 22 Giu 2022, 15:18 Karel Pičman ***@***.***> ha
scritto:
