### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by spbdimka** [anteo/redmine_custom_workflows#185]
Hi. It happens that I change in the workflow, for example, the assigned user and after saving the issue, the current user does not have enough rights.
The user sees a 403 error. Is there any way to redress it, for example, on / issues?

**Comment by picman** [comment]
I think, that it's an error in your code. You shouldn't cut off yourself. If it's necessary, from whatever reason, you should detect yourself this case and redirect it as follows:

```ruby
redirect_to: issues_path
```

**Comment by spbdimka** [comment]
> I think, that it's an error in your code. You shouldn't cut off yourself. If it's necessary, from whatever reason, you should detect yourself this case and redirect it as follows:
> 
> ```ruby
> redirect_to: issues_path
> ```

`Processing by CustomWorkflowsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"sdfVhurcQtfg==", "custom_workflow"=>{"name"=>"redirz", "author"=>"", "observable"=>"issue", "description"=>"", "is_for_all"=>"0", "active"=>"1", "project_ids"=>["3", ""], "before_save"=>"", "after_save"=>"redirect_to: projects_path", "before_destroy"=>"", "after_destroy"=>""}, "commit"=>"Создать"}
  Current user: admin (id=1)
= Running shared code for Issue (#) " #: "
= Finished running shared code for Issue (#) " #: "
Completed 500 Internal Server Error in 32ms (ActiveRecord: 3.9ms)
  
SyntaxError ((eval):1: syntax error, unexpected ':', expecting end-of-input
redirect_to: issues_path
           ^):
  
plugins/redmine_custom_workflows/app/models/custom_workflow.rb:111:in `instance_eval'
plugins/redmine_custom_workflows/app/models/custom_workflow.rb:111:in `validate_syntax_for'
plugins/redmine_custom_workflows/app/models/custom_workflow.rb:142:in `block in validate_syntax'
plugins/redmine_custom_workflows/app/models/custom_workflow.rb:142:in `each'
plugins/redmine_custom_workflows/app/models/custom_workflow.rb:142:in `validate_syntax'
plugins/redmine_custom_workflows/app/controllers/custom_workflows_controller.rb:106:in `block in create'
plugins/redmine_custom_workflows/app/controllers/custom_workflows_controller.rb:105:in `create'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'`

**Comment by picman** [comment]
```ruby
redirect_to issues_path
```

**Comment by spbdimka** [comment]
> ```ruby
> redirect_to issues_path
> ```

so i got undefined variable issues_path
after defining it, i got undefined method redirect_to

redmine 4.1.1,
i put clean code in after_save callback

**Comment by picman** [comment]
Hm, you're right. My advice was completely wrong. You can't use a redirection in a model.
How about the following approach?
```ruby
unless @issue.visible?
  raise WorkflowError.new("You've lost access to the issue")
end
```

**Comment by spbdimka** [comment]
@picman Yes, it is possible, but it is more of a temporary kludge
Is it possible to write an internal function for workflows to implement redirects?

**Comment by picman** [comment]
I don't think so. The plugin works with models only.
