### ISSUE TITLE
 computed custom field

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#187]
how i can in your plugin computed custom values (integar and float)
example :-
1-custom_field_value(1) * 2 + custom_field_value(2)
2- if cfs[1].zero?
 cfs[2]/2
else
 cfs[3]/2
end
how i can do any math sum or diff or divid

**Comment by AirTibu** [comment]
Hi,

You shoud convert the cfs[cf_id] value to integer or into float:

**Example 1:**

custom_field_value(1).to_i  *  2 + custom_field_value(2).to_i

**Example: 2:** 

```
if cfs[1].zero?
cfs[2].to_i / 2
else
cfs[3].to.i / 2
end
```

**IMPORTANT NOTE:**

If you have only integer in your calculation, then the result will be integer. What does it mean? See the below example:

If your cfs[2] field value is **3** and you use .to_i postfix, then the result will be integer:

```
cfs[2].to_i / 1      Resulting: 3 --> It's OK
cfs[2].to_i / 2      Resulting: 1 --> That's NOK
cfs[2].to_i / 3      Resulting: 1 --> It's OK
```

So, to get 1.5 result for 3 / 2 calculation, you should convert minimum one of the element to float:

```
cfs[2]**.to_f** / 2      Resulting: 1.5 --> It's OK
or
cfs[2].to_i  / 2**.to_f**     Resulting: 1.5 --> It's also OK

```

For arithmetic calculations, you can use the mathematical symbols, like: **+ - * /**

Or you can use the .sum as well:

`[  cfs[2].to_i  , 2,  3  ].sum   --> If cfs[2] is still 3, then this resulting: 2 + 2 + 3 = 8
`

I hope this help!

**Comment by ashrafalzyoud** [comment]
Thank you for the quick response and your cooperation
if i can ask u
1- im use this formula to computed custom field from parent to childs if child same tracker_id
```
sum = 0
COSTS_CF_ID = 86
COSTS_TRACKER_ID = 94
select_children = self.children.select { |c| c.tracker_id == COSTS_TRACKER_ID }
select_children.each  { |c| sum+=c.custom_field_value(COSTS_CF_ID).to_f } 
sum
```
2- im use this formula to computed custom field from parent to childs if childs different tracker_id
```
total = 0
children.each do |child|
  next unless child.tracker_id.in?([51,52,53,54,]) 
  total += child.custom_field_value(144).to_f 
end
total
```
3-im use this formula to computed custom field from tracker to another tracker
```
if project.present?
project.issues.includes(:custom_values).where(tracker_id:34).to_a.sum {|issue|issue.custom_field_value(138).to_f}
end
```
these formula its work in your plugins??

**Comment by AirTibu** [comment]
Hi,

**Formula 1:**

```

@children_sum_value =  self.children.where(:tracker_id=>'94').all.sum{|c| c.custom_field_value(86).to_f}.to_f}

```
**Formula 2:**

```

@children_total_value =  self.children.where(:tracker_id=>[51,52,53,54]).all.sum{|c| c.custom_field_value(144).to_f}.to_f}

```

**Formula 3:**

```

@issue_sum_value =  Issue.where(:tracker_id=>'34').all.sum{|c| c.custom_field_value(138).to_f}.to_f}

```

I hope its help!

**Comment by ashrafalzyoud** [comment]
where i can added project_id in these formula
becasue its sum all custom_field[138]

**Comment by AirTibu** [comment]
Hi,

I added the project as filter of issues:

**Formula 1:**

```

@children_sum_value =  self.children.where(:tracker_id=>'94', :project_id=>self.project_id).all.sum{|c| c.custom_field_value(86).to_f}.to_f}

```
**Formula 2:**

```

@children_total_value =  self.children.where(:tracker_id=>[51,52,53,54], :project_id=>self.project_id).all.sum{|c| c.custom_field_value(144).to_f}.to_f}

```

**Formula 3:**

```

@issue_sum_value =  Issue.where(:tracker_id=>'34', :project_id=>self.project_id).all.sum{|c| c.custom_field_value(138).to_f}.to_f}

```

I hope its help!
