### ISSUE TITLE
Can We update done_ratio when Checklist changed?

### ISSUE THREAD

**Issue by SeminYun** [anteo/redmine_custom_workflows#192]
We want to update done_ratio  when CheckList updated.

CheckList is this plugin : https://www.redmine.org/plugins/redmine_checklists

done_ratio

issue.state_id == 2 is done_ratio 20 and  issue.state_id == 3   is done_radio 50

when we state_id is 2,   we check  2 out of 3.
And then  we want to set done_ratio 40

like this  == my ratio done_ratio 20 + (50-20)/3*2

Can we do that?

**Comment by AirTibu** [comment]
Hi,

You can use this code in AFTER SAVE:
```

        done_checklist = @issue.checklists.reject(&:is_section).map { |c| c.is_done ? 1 : 0 }
        done_ratio = 20 + (50-20)/(3*(done_checklist.count(1) )
        @issue.update_columns(done_ratio: done_ratio)

```

Maybe it is better like this:

```

        done_checklist = @issue.checklists.reject(&:is_section).map { |c| c.is_done ? 1 : 0 }
        done_ratio = 20 + (done_checklist.count(1) *10)
        @issue.update_columns(done_ratio: done_ratio)

```


Normally I'm using this code to set done ratio between 0-100. It's independent from number of checklist items:


```

        done_checklist = @issue.checklists.reject(&:is_section).map { |c| c.is_done ? 1 : 0 }
        done_ratio = (done_checklist.count(1) * 10) / done_checklist.count * 10
        @issue.update_columns(done_ratio: done_ratio)

```

I hope its helps!
