### ISSUE TITLE
Error after install on fresh 4.1.1

### ISSUE THREAD

**Issue by DolezalDavid** [anteo/redmine_custom_workflows#193]
Hi,
i've got error after install plugin on fresh RM 4.11. I followed installation instruction. Here is log:

> Started GET "/admin" for xxx.xxx.xxx.xxx at 2020-10-30 09:24:12 +0100
> Processing by AdminController#index as HTML
>   Current user: admin (id=1)
>   Rendering admin/index.html.erb within layouts/admin
>   Rendered admin/_menu.html.erb (9.5ms)
>   Rendered admin/index.html.erb within layouts/admin (60.2ms)
>   Rendering layouts/base.html.erb
>   Rendered layouts/base.html.erb (148.0ms)
> Completed 500 Internal Server Error in 5233ms (ActiveRecord: 457.1ms)
>   
> ActionView::Template::Error (undefined method `match?' for "AdminController":String
> Did you mean?  match):
>     13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
>     14: <%= javascript_heads %>
>     15: <%= heads_for_theme %>
>     16: <%= call_hook :view_layouts_base_html_head %>
>     17: 
>     18: <%= yield :header_tags -%>
>     19: </head>
>   
> plugins/redmine_custom_workflows/lib/redmine_custom_workflows/hooks/hooks.rb:28:in `view_layouts_base_html_head'
> lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
> lib/redmine/hook.rb:63:in `each'
> lib/redmine/hook.rb:63:in `block in call_hook'
> lib/redmine/hook.rb:60:in `tap'
> lib/redmine/hook.rb:60:in `call_hook'
> lib/redmine/hook.rb:98:in `call_hook'
> app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___449394759_45227592'
> app/views/layouts/admin.html.erb:8:in `_app_views_layouts_admin_html_erb___834812368_44566584'
> lib/redmine/sudo_mode.rb:65:in `sudo_mode'

If it help, I use gem redmine_extensions 0.3.11 and this is setup:

> Environment:
>   Redmine version                4.1.1.stable
>   Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
>   Rails version                  5.2.4.2
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Filesystem                     
> Redmine plugins:
>   redmine_lightbox2              0.5.1

**Comment by picman** [comment]
This is the problem: `Ruby version 2.3.3`. Can't you upgrade to Ruby 2.4?

**Comment by picman** [comment]
Fixed.

**Comment by DolezalDavid** [comment]
OK. I will update Ruby. Thank you for quick answer. 👍

**Comment by DolezalDavid** [comment]
Hi Karel, it works smooth and nice after update Ruby! Thank you!
