### ISSUE TITLE
Watchers as member?

### ISSUE THREAD

**Issue by DolezalDavid** [anteo/redmine_custom_workflows#197]
Hi,
I have nice quest, which can - I think - be solved with this awesome plugin. So here is example.

1) I have private project, because I need to see this only members. 
2) I add issue, I'm member of this project. 
3) BUT I need to add my friend as watcher or assignee, because this issue hit his work too, but my friend isn't member. 

**RESULT?** 
I CAN add him as watcher, but he DOESN'T see project or issue and he isn't notified.
I CAN'T add him as assignee, because he isn't member.

**POSSIBLE SOLUTION?**
Add him as member to the private project. But I don't want to do this everytime when I need him to watch the issue/s.

**QUESTION:**
If my friend add as Watcher, can he reach temporaly permission like user-member?

**HOW I THINK ABOUT IT?**
1) I have private project, because I need to see this only members
2) I add issue, I'm member of this project. 
3) I add non-member users as watcher.

**AFTER ADDING**
- non-member user can see project in list of projects
- non-member user can see issue from private project, where is watcher
- non-member can add comment, etc. issue from private project, where is watcher (temporary permission like member with "User" rights)

**WHY?**
I have around 30 projects, all public. Almost everytime I need to get issue from one project to another, like from POOL to SW HELP and I need to keep user access to his issue.

**Comment by AirTibu** [comment]
Hi,

Reading the question, I don't think you need any special code to implement it, you can reach what you want with simple role settings.

1. Create a special role called: "Limited access"
2. Issues visibility will be: "Issues created by or assigned to the user"
3. At Issue tracking flag the following checkboxes:

> - View Issues
> - Edit own issues
> - Add notes
> - Edit own notes
> - View watchers list


4. Add this role to your friend and assign to all projects.

In this case, the user see only the issues, where he is assigned user or watcher, all other issues remain hidden from him.
He will be in watchers list and in assignable user list, so you can choose him easily, if you want.

I hope its help!

**Comment by DolezalDavid** [comment]
> 
> 
> Hi,
> 
> Reading the question, I don't think you need any special code to implement it, you can reach what you want with simple role settings.

Hi @AirTibu,
sorry for late answer. It works, but not exactly how I need... With your setting the user see only issues, which he creates or where he is assignee. Not issue, where he is only as watcher...

**Comment by DolezalDavid** [comment]
Hi, for this problem I use plugin redmine_extended_watchers, where is exactly defined setup for this. So I close this with solution via redmine_extended_watchers. 

Thank for support.
