### ISSUE TITLE
Can one use plugin models in custom_workflows?

### ISSUE THREAD

**Issue by letitbe13** [anteo/redmine_custom_workflows#199]
Hi!
We all have plugins that extend behavior of standart models like Project, Issue. Is it possible to add some "plugin driven" functionality to custom_workflow scenario?
For example, I have redmine_dmsf plugin. I see in _redmine_dmsf/app/models/dmsf_file.rb_ that 

```
class DmsfFile < ActiveRecord::Base
  belongs_to :project
...
  validates :name, presence: true, dmsf_file_name: true

```

and in _redmine_dmsf/app/helpres/dmsf_links_helper.rb_ example of access to dmsf files from project entity:
```
...
files = project.dmsf_files.visible.to_a if project
```
But, when I try to add in Project after_save something like `files = self.dmsf_files` it does nothing or throw a message "undefined method dmsf_files". Now I simply want to get number of files in project dmsf, and use it in done_ratio calculation. But else I want to understand the approach, how to use plugin logic within scenarios.

Thank you.

**Comment by picman** [comment]
But it works. I have the following code in project after save:

```
Rails.logger.info ">>> #{self.dmsf_files.all.size}"
```
After I change e.g. project's description and save the project, I can see in the log:
```
>>> 7
```

**Comment by picman** [comment]
Is the observable object really Project in your case?

**Comment by letitbe13** [comment]
It works, Thank you. That was my inattention.
