### ISSUE TITLE
Repository for example workflows

### ISSUE THREAD

**Issue by plapczyn** [anteo/redmine_custom_workflows#2]
It would be awesome to have a repository of example workflows to get people started or help with ideas.

**Comment by pyroit** [comment]
yes this would be great! How can the something like this?

**Comment by anteo** [comment]
Agree, that plugin documentation need more examples.
Nevertheless I recommend look into [FAQ](https://github.com/anteo/redmine_custom_workflows/wiki/Frequenly-Asked-Questions) first.
I think I could put more workflow examples on Wiki in a future.

**Comment by go2null** [comment]
I've created a wiki page ([Example-Workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows)) as a starting point.

Hope it is fine with anteo.  Feel free to do with as you wish.

**Comment by anteo** [comment]
Thank you, go2null.
I have plans for implementing online repository, with ability to import and push workflows right from admin panel.

**Comment by go2null** [comment]
As you are adding "Version control support"  (#9), it may be nice to be able to pull a workflow from a git repository or GitHub gist.

With this approach, the "online repository" could be a simple list of git URLs.

Also, if users are able to maintain a list of subscribed workflows (git URLs), then users with private custom workflows can also use this facility to update their workflows.

Thoughts?

**Comment by kenan3008** [comment]
Hello, could someone provide some more example workflows as I'm having trouble finding out this on my own? Thanks :)

**Comment by go2null** [comment]
[Example workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows)

**Comment by DonHege** [comment]
Does anybody have examples for creating users? I want to assign a newly create user to a set of default roles/groups/projects automatically.

**Comment by pyroit** [comment]
@DonHege 

for example put this in after save: 

User.last.group_ids = [9] if User.last.mail.include?"@my_company.com"
