### ISSUE TITLE
Request: Change log message so that issue_id is before subject

### ISSUE THREAD

**Issue by go2null** [anteo/redmine_custom_workflows#20]
Reason is that some issues have long subjects and causes the line to wrap.  This means that you cannot easily scan down the log messages to see the sequence of issues that are changed.

Patch

`- Rails.logger.info str + " for #{object.class} \"#{object}\" (\##{object.id})"`
`+ Rails.logger.info str + " for #{object.class} (\##{object.id}) \"#{object}\""`

Then you can easily view with `less -Sinx +F log/production.log`.

**Comment by anteo** [comment]
Done, version 0.1.4 in repository only for now.

**Comment by go2null** [comment]
Thank you!
