### ISSUE TITLE
change subtask status

### ISSUE THREAD

**Issue by cy120032** [anteo/redmine_custom_workflows#200]
Hello, I have a requirement to implement that when user change the status of issue, I need automatically change the status of subtask of that issue.
The following is my code.

before saving :
if @issue.tracker_id == 6
  if @issue.status_id_changed?
    @need_update_status = true
  end
end

after saving:
if @need_update_status
  @issue.children.each{|c| c.status_id = @issue.status_id}
  @need_update_status = false
end

I don't know why this code does not work. 
Is there anyone can help me?

**Comment by AirTibu** [comment]
Hi,

Use this code in **BEFORE SAVE** section:

```

children.each{|c| c.update_columns(status_id:status_id) if c.tracker_id==6 } if status_id_changed?

```

**Please take into consideration the below limitations, when you use this code:**

- This code does not update the History/Change property of subtasks.
- Redmine basically do not allow to close the parent issue, if any child (subtask) is open. (It's not impossible, but a little trick should be applied. Let me know, if you should close the subtasks from parent, then I will explain in detail)
- The code ignores the workflow rules, so if a field is "required" in "In progress" status and it is empty when code is changing the issue status from "New" to "In progress", then it will do it successfully without error notification. (Of course, if you try to save manually again the subtask in "In progress" status, you will get error notification, that a required field is empty.)


I hope it helps!

**Comment by cy120032** [comment]
@AirTibu Thank you very much!
I have solved this problem. Use following code in before save section.
`c.update({:status_id =>10})`

Thanks for you tips. These limitations are also important.

**Comment by luk3k0** [comment]
@cy120032 I need an example code to change subtask.
Can you provide complete script of "before save" and "after save" section?

**Comment by cy120032** [comment]
> @cy120032 I need an example code to change subtask.
> Can you provide complete script of "before save" and "after save" section?

before saving :
`if @issue.tracker_id == 6
    if @issue.status_id_changed?
      @need_update_status = true
    end
end`

after saving:
`if @need_update_status
  @issue.children.each{|c| c.update({:status_id => @issue.status_id})}
  @need_update_status = false
end`

**Comment by luk3k0** [comment]
@cy120032 Thank you for your help.
