### ISSUE TITLE
Issue_relation for redmine 4.0.x

### ISSUE THREAD

**Issue by lcasanova78** [anteo/redmine_custom_workflows#201]
I need to use Issue Relation in Redmine, my version is Redmine 4.0.X, the version of yours that supports Issue Relation is for Redmine 4.1.X, is there any way to make it compatible with my Redmine?

**Comment by lcasanova78** [comment]
I have tried version 1.0.1 but it does not have the Issue Relation object, thank you.

**Comment by picman** [comment]
So in that case the only solution is to upgrade Redmine to 4.1.

**Comment by lcasanova78** [comment]
It is the Redmine of my company, we are in 3.3.0 and there I have Issue Relation (modified by me) and soon we will migrate to 4.0, difficult to convert them to move to 4.1.

Thank you very much anyway, good job
