### ISSUE TITLE
Issue description change doesn't add history diff

### ISSUE THREAD

**Issue by letitbe13** [anteo/redmine_custom_workflows#203]
Hi! I'm using issue after_save to update another issue description (or create new issue if not created yet):
```
...
      OTK = Issue.select{ |is| is.project_id == my_project.id && is.subject == self.subject}.first
      if OTK.nil? 
        OTK = Issue.new
        OTK.project_id = my_project.id
        OTK.tracker_id = 10
        OTK.author = User.current
        OTK.start_date = Date.today
        OTK.subject = self.subject
        OTK.status_id = 1 
        OTK.assigned_to_id = my_project.users_by_role[(Role.find 12)].first.id 
      else
        OTK.description = self.description
      end
      OTK.save! 
...
```
If OKT.issue updated, there is no history record about it (and no chance to see diff), like the issue was just created.
I tried safe_attributes to update description, but it behaves the same way.
When I made description update manualy, without cw, history works fine.
How can I update description with cw to add history record?

**Comment by AirTibu** [comment]
Hi,

Use this code for description update and you will have history:

      OTK = Issue.select{ |is| is.project_id == my_project.id && is.subject == self.subject}.first
      if OTK.nil? 
        OTK = Issue.new
        OTK.project_id = my_project.id
        OTK.tracker_id = 10
        OTK.author = User.current
        OTK.start_date = Date.today
        OTK.subject = self.subject
        OTK.status_id = 1 
        OTK.assigned_to_id = my_project.users_by_role[(Role.find 12)].first.id 
      else
        OKT.update_columns(description: self.description)
      end
      OTK.save! 

**Hint:**
Do you intentionally use capital letters for variables?

Constants begin with an uppercase letter. Constants defined within a class or module can be accessed from within that class or module, and those defined outside a class or module can be accessed globally.

I hope it helps!

**Comment by letitbe13** [comment]
> **Hint:**
> Do you intentionally use capital letters for variables?
> 
> Constants begin with an uppercase letter. Constants defined within a class or module can be accessed from within that class or module, and those defined outside a class or module can be accessed globally.
> 
> I hope it helps!

Thank you, I didn't know that. OTK is just an abbreviation, in my case, I didn't imply a Constant behavior :) I fixed it, but it didn't help

**Comment by AirTibu** [comment]
Hi,

Did you change the code too? I modified the below line, that you will have history:
`

OKT.update_columns(description: self.description)

`

**Comment by letitbe13** [comment]
I did but still haven't history log
```
        o= Issue.select{ |is| is.project_id == my_project.id && is.subject == self.subject}.first
        if o.nil?  #"создаем задачу если нет 
          o= Issue.new
          o.project_id = my_project.id
          o.tracker_id = 10 # Закупка
          o.author = User.current
          o.start_date = Date.today
          o.subject = self.subject
          o.update_columns(description: self.description)
          o.status_id = 1 #В очереди  
          o.assigned_to_id = my_project.users_by_role[(Role.find 12)].first.id 
        else
          o.update_columns(description: self.description)
        end
        o.save! 
```

**Comment by AirTibu** [comment]
Hi,

Yes, it is working only on self issue, but you can update manually the history, like this:
```

        o= Issue.select{ |is| is.project_id == my_project.id && is.subject == self.subject}.first
        if o.nil?  #"создаем задачу если нет 
          o= Issue.new
          o.project_id = my_project.id
          o.tracker_id = 10 # Закупка
          o.author = User.current
          o.start_date = Date.today
          o.subject = self.subject
          o.update_columns(description: self.description)
          o.status_id = 1 #В очереди  
          o.assigned_to_id = my_project.users_by_role[(Role.find 12)].first.id 
        else
          o.update_columns(description: self.description)
        end
        o.save!

journal = o.init_journal(User.current)
journal.save!
journal.details <<  JournalDetail.create!(
                              :journal_id=>o.id,
                              :property => 'attr',
                              :prop_key => 'description',
                              :old_value => nil,
                              :value => self.description)

```

**Comment by letitbe13** [comment]
It almost works! You've realy helped a lot already! The one thing, the code adds history twice, and I can't figue out why
![image](https://user-images.githubusercontent.com/49904609/107744570-fcf30500-6d23-11eb-9e71-b4006b2f9159.png)
First record contains real difference. second record shows no difference, as if :old_value == :value

**Comment by picman** [comment]
```ruby
   journal = o.init_journal(User.current)
-- journal.save!
   journal.details <<  JournalDetail.create!(
                              :journal_id=>o.id,
                              :property => 'attr',
                              :prop_key => 'description',
                              :old_value => nil,
                              :value => self.description)
++ journal.save
```
