### ISSUE TITLE
Refresh page

### ISSUE THREAD

**Issue by lcasanova78** [anteo/redmine_custom_workflows#206]
Is it possible to update the current page from a custom workflow?
I need to do this when I add a relationship to an issue, since there are auto calculated fields that are updated when adding a relationship, I would like that when a relationship is added the page is updated with the fields already calculated, without having to refresh manually.

Thank you very much

**Comment by AirTibu** [comment]
Hi,

I don't think this is really possible this way, as there is no trigger to relationship change in the custom workflow plugin.
