### ISSUE TITLE
Copy custom field value from parent task to subtask

### ISSUE THREAD

**Issue by luk3k0** [anteo/redmine_custom_workflows#207]
We need to copy custom field content from parent task to subtask.
The below script is not working. 
Do you have any ideal?

after saving:
```
if @need_update_status
  @issue.children.each{|c| c.update(
  :status_id => @issue.status_id,
  :custom_field_value = { '3' => @issue.custom_field_value{'3'}}
) if c.tracker_id==1 }
  @need_update_status = false
end
```

@cy120032 Thank you for your help at ticket #200.
_Originally posted by @luk3k0 in https://github.com/anteo/redmine_custom_workflows/issues/200#issuecomment-780537511_

**Comment by cy120032** [comment]
@luk3k0 
replace 4th line with:
:custom_field_values => { 3 => @issue.custom_field_value(3)}

**Comment by luk3k0** [comment]
@cy120032 Thanks a million.

**Comment by ashrafalzyoud** [comment]
if from sutask to parent what i can do??
@cy120032

**Comment by ashrafalzyoud** [comment]
@luk3k0 can u help?!
