### ISSUE TITLE
Save deleted attachment

### ISSUE THREAD

**Issue by lcasanova78** [anteo/redmine_custom_workflows#210]
I want to create a custom workflow so that when a user deletes any type of attachment I can save it inside an issue that I have created for it.  I know that I have to do it in the before destroy part of the workflow.
How can I capture that attachment and then save it?

**Comment by AirTibu** [comment]
Hi,

Check this code:

https://www.redmine.org/attachments/download/7046/duplicate_issues_attachment.diff

From here:
https://www.redmine.org/issues/3055

I hope it helps!
