### ISSUE TITLE
Question. how to determine if the parent task has changed?

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#212]
Hi!
How I can to determine if the parent task has changed?

I try following code but it is not successful:

```
if self.parent_issue_id_changed?
if self.parent_id?
    @parent=self.parent
    if !@parent.parent_id?
      #do nothing
    else
      raise WorkflowError, "error."
      return true
    end
end
end
```
Error
`undefined method `parent_issue_id_changed?' for #<Issue:0x0000000010cce920>`

**Comment by AirTibu** [comment]
Hi,

If you would like to detect any changes on parent, then you should compare the last update date of current issue and its parent.

Use this code:

```

`if child?
if self.parent.journals.reorder(:id => :desc).first.try(:created_on) > self.journals.reorder(:id => :desc).first.try(:created_on)
      #do nothing
    else
      raise WorkflowError, "error."
      return true
end
end


````

I hope it helps!
