### ISSUE TITLE
support latest version for redmine 4.0?

### ISSUE THREAD

**Issue by dpalic** [anteo/redmine_custom_workflows#213]
is there any chance to make the plugin work with redmine 4.0.x?
I am using redmine on ubuntu/debian and not sure how many distributions are based on debian, but afaik many...

And if you check the status on debian they are still on redmine 4.0.7
https://tracker.debian.org/pkg/redmine

also ubuntu, which is forking from debian is on 4.0.6
https://packages.ubuntu.com/focal/redmine

**Motivation why to stick to ubuntu package?**

I myself use ubuntu to have an automatic security update feature, so I do not have to worry about patches until upgrading the OS incl. all required dependencies (ruby, ror, bundler, gem, ...)

is there a technical reason why support for redmine 4.0 was dropped?

**Comment by picman** [comment]
_is there a technical reason why support for redmine 4.0 was dropped?_

There is always a reason.... The newer versions of Redmine requires some changes in the code and libraries used in plugins. Sometimes, these changes aren't compatible with the previous versions of Redmine. Debian is quite conservative distribution. If there is Redmine 4.0.7 you should use Redmine Custom Workflows plugin v1.0.1. If you want a newer plugin version you must logically upgrade Redmine too. You can't expect the newest version being compatible with Redmine several years old.
What you can try is to comment out the Redmine dependency line in _init.rb_.

```ruby
--  requires_redmine version_or_higher: '4.1.0'
++  #requires_redmine version_or_higher: '4.1.0'
```
