### ISSUE TITLE
set custom field values based on other custom field

### ISSUE THREAD

**Issue by Cansiano** [anteo/redmine_custom_workflows#214]
Hello can you help me to create script in order to change possible values from list in custom field id 4 when custom field value from  custom field id 2 been selected to specific value?

I was tried several options but no one worked.
e.g:
if custom_field_value(3) != custom_value_for(3).try(&:value)
  if custom_field_value(3) == 'RPA'
    fields = { "1" => "Execution"}
    @issue.custom_field_values(4) = (fields)
  end
end

thanks

**Comment by Cansiano** [comment]
sorry if custom field 3 is changed and has value "RPA"

**Comment by AirTibu** [comment]
Hi,

It is not really clear for me, that you want to change the possible values or you would like to choose only an element on list type custom field.

If you would like to add value for custom field, then use this code:

```

if custom_field_value(23) != custom_value_for(23).try(&:value) && custom_field_value(3)=="RPA".to_s
      self.custom_field_values = { '4' => "Execution".to_s }
      self.save_custom_field_values   # This save method is required only in after save section.
end


```
If you want to change the possible values (all element of dropdown list), then use this code:

```

if custom_field_value(23) != custom_value_for(23).try(&:value) && custom_field_value(3)=="RPA".to_s
        new_posvalues = ['Plan','Execution','Check','Act']
        CustomField.find(4).update possible_values: new_posvalues.join("\n\r").to_s
        CustomField.find(4).save!
end

```

I hope it helps!

**Comment by Cansiano** [comment]
Hi, thanks for the help. Unfortunatelly its not working. We have redmine 4.2.0_1. Is it possible that is not compatible with this version?

**Comment by AirTibu** [comment]
Hi,

Sorry, that was my mistake in the first line, the custom_field_id was mistypo, it is not 23 but a 3.

Below the correct and tested codes:

This code change the value of custom field:
```

if custom_field_value(3) != custom_value_for(3).try(&:value) && custom_field_value(3)=='RPA'.to_s
      self.custom_field_values = { '4' => "Execution".to_s }
      self.save_custom_field_values   # This save method is required only in after save section.
end


```This code change the possible values:
```

if custom_field_value(3) != custom_value_for(3).try(&:value) && custom_field_value(3)=="RPA".to_s
        new_posvalues = ['Plan','Execution','Check','Act']
        CustomField.find(4).update possible_values: new_posvalues.join("\n\r").to_s
        CustomField.find(4).save!
end

```
I'm using 4.1 version, but it couldn't be problem. Based on your description, the intent wasn’t entirely clear to me, if the code above doesn’t work the way you expected, please let me know please!

I hope it helps!

**Comment by Cansiano** [comment]
Thanks again. Yes I noticed and corrected the typo. I want to have set of different values if custom field  3 is changed so option. 2 nevertheless its not working. 

I have Observable object = Issue


Workflow scripts: Saving observable objects

if custom_field_value(3) != custom_value_for(3).try(&:value) && custom_field_value(3)=="RPA".to_s
        new_posvalues = ['Plan','Execution','Check','Act']
        CustomField.find(4).update possible_values: new_posvalues.join("\n\r").to_s
        CustomField.find(4).save!
end

this is in the log 

Started GET "/redmine/custom_workflows/3/edit" for 185.213.145.131 at 2021-04-28 16:14:38 +0200
Processing by CustomWorkflowsController#edit as HTML
  Parameters: {"id"=>"3"}
  Current user: Uberadmin (id=5)
  Rendering plugins/redmine_custom_workflows/app/views/custom_workflows/edit.html.erb within layouts/admin
  Rendered plugins/redmine_custom_workflows/app/views/custom_workflows/_form.html.erb (18.4ms)
  Rendered plugins/redmine_custom_workflows/app/views/custom_workflows/edit.html.erb within layouts/admin (21.3ms)
  Rendered admin/_menu.html.erb (3.2ms)
  Rendering layouts/base.html.erb
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (0.7ms)
  Rendered plugins/additionals/app/views/additionals/_body_top.slim (0.2ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.2ms)
  Rendered layouts/base.html.erb (24.6ms)
Completed 200 OK in 250ms (Views: 42.1ms | ActiveRecord: 115.2ms)

**Comment by AirTibu** [comment]
Hi, 

To which part did you add the code? Before save section or After save section?

The code is working only in before save, because the changes of custom field can be detected on at before save:

custom_field_value (3)! = custom_value_for (3) .try (&: value)

If you are using in after save, then the value is already saved, therefore the condition will always be true, so the code is not running further inside condition.

So, please try it in the before save section, I already tested the code is working well.

I hope it helps!

**Comment by Cansiano** [comment]
Yes i háve it in "before save" section.

Could it be its in conflict with other plugin? 
E.g.: redmine-view-customize

**Comment by AirTibu** [comment]
Hi,

What is the type of your dropdown custom field list?

List or key/list?

The above code is working with simple list type, if you are using key/list, then the update is a little bit different.
