### ISSUE TITLE
Knowing a user's id by name

### ISSUE THREAD

**Issue by lcasanova78** [anteo/redmine_custom_workflows#217]
I need to add as a watcher a user of which I only know the acronym. 
When I have the id I use this statement:
self.add_watcher(User.find_by_id(1150)) unless watched_by?(User.find_by_id(1150))
Is there any way to do the same but with the user acronym?

**Comment by picman** [comment]
```ruby
User.find_by(login: 'user_login')
```

**Comment by AirTibu** [comment]
Hi,

You can use this code with name:
```


@name_of_user= "John Snow".to_s

user_id = User.where("type = 'User' and firstname||' '||lastname = ?",@name_of_user.to_s).pluck(:id)[0].to_i


```

I hope it helps!

**Comment by lcasanova78** [comment]
I have a redmine instance that if I do User.find_by_id(1150) it returns me the user's name and not its acronym, but I need to know its acronym to send him an email, since his email address is acronym@email.com.

**Comment by picman** [comment]
```ruby
u = User.find_by_id(1150)
acronym = u.login
email = u.mail
```

**Comment by lcasanova78** [comment]
Thank you very much, I have one more question.
How can I know if a user has the External Developer role?

Thank you, Luis.
