### ISSUE TITLE
Cant set custom field user type

### ISSUE THREAD

**Issue by akiiraJager** [anteo/redmine_custom_workflows#222]
Hi, all

On issue update if issue is set to a certain STATUS, ir should create a project, and set project custom_field "Project owner" from issue custom_field "Project owner"

issue user object custom_field - id 100
project user object custom_field - id 101

#before script
`
@need_create_project = status_id_changed? && @issue.status_id == 9
`
#after script

```
if @need_create_project 
project = Project.create(
        :name => @issue.subject,
        :description => @issue.description,
        :parent_id => 15,
        :inherit_members => true,
        :custom_fields => 
[
               {id: 101, value: custom_field_value(100)}
]
)

end
```

Script is able to set any custom field except user object custom field.

Tried finding user and setting found user obnject or setting RAW id, same effect.

What could be the cause and how to get it working?

**Comment by AirTibu** [comment]
Hi,

Use this code:

```

if @need_create_project 
project = Project.create(
        :name => @issue.subject,
        :description => @issue.description,
        :identifier => Project.next_identifier
        :parent_id => 15,
        :inherit_members => true)

  project.save!

  project.custom_field_values = {'101' => @issue.custom_field_value(100)}
  project.save_custom_field_values

end

```

I hope it helps!

**Comment by akiiraJager** [comment]
Hi, works just right :) Thanks
