### ISSUE TITLE
help if and or in scripte

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#223]
if u can help me how i write the code correct????

`if tracker_id ==35 &&  custom_field_id: 100, value: `"CNC"`

`end`

HOW I CAN WRITE IF ----&&

**Comment by AirTibu** [comment]
Hi,

One if the method:

```

if tracker_id==35 && custom_field_value(100).to_s == “CNC”

Do some think - your code

end

```

**Comment by ashrafalzyoud** [comment]
@AirTibu 
thx for your replay and all your help
i need help about that
if cfs [100] float and i need total where cfs[100] => 500
what wrong in this code
self.custom_field_values = { 420=> Issue.joins(:custom_values).where(project_id: 69,tracker_id: 103,custom_values: {custom_field_id: 33, value: "A"},custom_values: {custom_field_id: 100, value=>500"}).to_a.sum {|issue|issue.custom_field_value(282).to_f}}

**Comment by ashrafalzyoud** [comment]
custom_values: {custom_field_id: 100, value >= "500"
@AirTibu if u can help me plz

**Comment by picman** [comment]
You can access custom values directly too.

```ruby
sum = CustomValue.sum(:value).where(['custom_field_id = ? AND value >= ?', 100, 500)
```

**Comment by ashrafalzyoud** [comment]
@AirTibu  can u help me about my another ticket

**Comment by AirTibu** [comment]
Hi,

First time you should filter issues, where the custom_field_value(33) = 'A'. After that, you can summarize the custom_field_value(100) of these issues:

```

@issues_id_list = Issue.joins(:custom_values).where("tracker_id = '103' AND project_id = '69' AND custom_field_id = '33' AND value = 'A'").pluck(:id)
@sum_value = CustomValue.where("customized_id IN (#{@issues_id_list.join(',').to_s}) AND custom_field_id = '100' AND value => 500").sum(:value)

self.custom_field_values = { 420=> @sum_value.to_f }
self.save_custom_field_values


```
I hope it helps!

**Comment by ashrafalzyoud** [comment]
@AirTibu 
thx for your replay 
i mean in my ticket #235
