### ISSUE TITLE
How to make custom user format  in issues as assignees

### ISSUE THREAD

**Issue by godpusa** [anteo/redmine_custom_workflows#227]
Hi, I have create 2 custom user format in Issues, but these kind of users are not assignees, can I write a Custom workflows to implement this ？

**Comment by godpusa** [comment]
Hi all. In case someone finds this through a search engine.
This plugin seems sovled my issues. 
https://github.com/preciousplum/custom_users_as_assignees

**Comment by picman** [comment]
I'm afraid that your description of the problem is absolutely incomprehensible.
