### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zas0006** [anteo/redmine_custom_workflows#23]
I have a need to be able to tell if any children on issue X are open so i can then throw a WorkflowError stating they cant close this issue due to open subtasks.

So something like open_children? that would return false unless there were children and at least one of them were not closed.

Or if any knows of a way to create a blocking related issue from within a custom workflow, that would eliminate this need entirely as i could have the custom workflow create a blocking related issue which already prevents the parent from being closed.

**Comment by go2null** [comment]
I've added workflow to do this.
https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#prevent-closing-an-issue-if-it-has-open-descendants

You can use this workflow as the last one to trap errors generated in other workflows.
https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#error-trapping

**Comment by kfranckiewicz** [comment]
Redmine has already this functionality in core. For example if some issue is related as "blocks" or "blocked by" then one of them issue can not by closed (status closed is not possibile to set). Is that what you need ?

**Comment by zas0006** [comment]
Thank you @go2null. I will take a look and see if that will work for me.

@kfranckiewicz I am aware that this can be done in redmine, i was looking for a way to do it automatically from within a custom workflow, OR be able to prevent closure on sub-tasks. But thank you for the reply!

**Comment by zas0006** [comment]
The workflow provided by @go2null worked lie a charm. Thank you again.

**Comment by gbhuoo** [comment]
@go2null why pop internal error when i added https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#prevent-closing-an-issue-if-it-has-open-descendants to my custom workflow?
