### ISSUE TITLE
Parent task status change after all subtask closed

### ISSUE THREAD

**Issue by babinecmiro** [anteo/redmine_custom_workflows#230]
Hi there. I'm trying to implement simple logic - when the last children task is closed, then status of parent task is changed. So far nothing worked properly for me. Please can anyone help where I'm making the mistake?

```
if @issue.status_id==7 && self.parent_id?
    closedIssueStatus = IssueStatus.find_by_is_closed true
    if parent.descendants.none? { |childIssue| childIssue.status_id != closedIssueStatus.id}
    parent.update({:status_id=>2})
    end
end
```

**Comment by AirTibu** [comment]
Hi,

Use this code after saving:
```

    if  !@parent.nil? &&  !self.root.descendants.find { |d| !d.closed? }
         @issue.parent.update({:status_id=>2})
    end

```
I hope it helps!

**Comment by babinecmiro** [comment]
Thank you very much, it really helped. You've made my day :).
Just little change in the condition was needed: !self.parent.nil? instead !@parent.nil?

    if  !self.parent.nil? &&  !self.root.descendants.find { |d| !d.closed? }
         @issue.parent.update({:status_id=>2})
    end
