### ISSUE TITLE
Help in code

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#235]
Purchase orders must not exceed the financial balance
Where the user can add several purchase orders so as not to exceed the financial balance.
And if the financial balance is exceeded, a warning message appears, and the purchase order balance must be changedt
TRAcker ORDERS 200 AND CFS[2] order_balance -->float
TRAcker  FINANCE 100 and CFS[1]  financial_balance---> float

if user added many orders and in case added Order has financial balance is exceeded 
must give warning message and put cfs[2]=0

**Comment by ashrafalzyoud** [comment]
Tracker 100 have cfs[1] float
Tracker 200 have cfs [2] float
I need  error message if the total cfs[2] >= cfs[1]
And user can't added the issue

**Comment by AirTibu** [comment]
Hi,

What is the connection between Finance tracker and Order tracker? Which is the parent? Which is the child?

If I understand well, the Finance tracker the parent and the Finance issue has many Order sub-issues. Am I right?

**Comment by ashrafalzyoud** [comment]
Finance tracker its completely separate 
THE order tracker its issues

**Comment by ashrafalzyoud** [comment]
```
if project.present?
a = project.issues.includes(:custom_values).where(:tracker_id=>'2').all.sum{|c| c.custom_field_value(2).to_f}.to_f
b = self.custom_field_value(457).to_f/ tracker_id=1
c= b-a
if (a > b )
errors.add(:base,"Exceeding the financial balance  the rest is (c)")
end
end
```
the problem the new value of cfs[2] its not calculated in first time i need resave the issue twice until the total correct
this mean the user add new order exceeded

**Comment by ashrafalzyoud** [comment]
@AirTibu plz any update frind

**Comment by AirTibu** [comment]
Where is the code? In the BEFORE SAVE or in the AFTER SAVE section?

**Comment by AirTibu** [comment]
Try to save the custom field values, before calculation:

```

self.save_custom_field_values

```

**Comment by ashrafalzyoud** [comment]
U mean put this code before save
And after save write formula

**Comment by ashrafalzyoud** [comment]
can u reriwite the formula to do this function
and user can put another value when the error show

**Comment by AirTibu** [comment]
Hi,

You should add the actual issue cfs [2] value separately, if you don't want to save the cfs before.

```

if project.present?
a = project.issues.includes(:custom_values).where(:tracker_id=>'2').all.sum{|c| c.custom_field_value(2).to_f}.to_f

a += custom_field_value(2).to_f

b = self.custom_field_value(457).to_f/ tracker_id=1
c= b-a
if (a > b )
errors.add(:base,"Exceeding the financial balance  the rest is (c)")
end
end


```

I hope it helps!

**Comment by ashrafalzyoud** [comment]
the value (c) not appear ?? how i can show remain money in error msg

**Comment by ashrafalzyoud** [comment]
```
if custom_field_value(6) != custom_value_for(6).try(&:value)
a = project.issues.includes(:custom_values).where(:tracker_id=>'49').all.sum{|c| c.custom_field_value(6).to_f}.to_f
a += custom_field_value(6).to_f
b = self.custom_field_value(9).to_f
c= b-a
self.save_custom_field_values
if (a > b )
errors.add(:base,"Exceeding the financial balance  the rest is (c)")
end
end

```
how i can this formula work when im edit the value or change value

**Comment by ashrafalzyoud** [comment]
@AirTibu 
I apologize for the requests and I appreciate your help and interest, but this is very important to me

**Comment by AirTibu** [comment]
> 

Hi,

Regarding the error message it was not clear to me, that you want to see there a the value instead of character.

If you would like to see the value of c, then use this code:

```

errors.add(:base,"Exceeding the financial balance  the rest is #{c.to_s}")

```

I'm checking your second problem, give me some minutes.

**Comment by DarkSideGeek** [comment]
For as much as you depend specifically on him for your customizations, you should give him a paid support contract!

**Comment by ashrafalzyoud** [comment]
@DarkSideGeek 

He deserves more than that. He is a helpful and loving person who always finds solutions @AirTibu

**Comment by ashrafalzyoud** [comment]
@AirTibu thx for your corporation
but still not work 
![order1](https://user-images.githubusercontent.com/50211455/149623980-10eb12b3-b21f-48c6-8621-e61f082d07f2.png)
![order2](https://user-images.githubusercontent.com/50211455/149623989-42c7c1ab-daa8-4060-9b20-965c3ad5efe7.png)

**Comment by ashrafalzyoud** [comment]
when added new order
![order3](https://user-images.githubusercontent.com/50211455/149624212-1c39b265-20a0-46d5-878c-454a97721417.png)

**Comment by ashrafalzyoud** [comment]
look to this example too
![o6](https://user-images.githubusercontent.com/50211455/149624492-b0ea604f-dbc0-459b-9638-952680090932.png)
![o5](https://user-images.githubusercontent.com/50211455/149624494-200c6fbf-01dc-48d5-b08f-81ab0cd94270.png)

its still not calculated total order and remain money in first time ,still need twice edit and submit

**Comment by ashrafalzyoud** [comment]
I FOUND the solution by 2 choise
`if new_record?
a = project.issues.includes(:custom_values).where(:tracker_id=>'N').all.sum{|c| c.custom_field_value(6).to_f}.to_f 
a += custom_field_value(6).to_f
else
a = project.issues.includes(:custom_values).where(:tracker_id=>'N').all.sum{|c| c.custom_field_value(6).to_f}.to_f 
a += (custom_field_value(6).to_f - custom_value_for(6).try(&:value).to_f).to_f
end`
but now i need it in self.tracker_id BECAUSE I HAVE IN MANY TRACKER and no need write many formula each tracker
`if project.present?
N= self.tracker_id.to_s
self.custom_field_values = { 17=> N}
if new_record?
a = project.issues.includes(:custom_values).where(:tracker_id=>'N').all.sum{|c| c.custom_field_value(6).to_f}.to_f 
a += custom_field_value(6).to_f
else
a = project.issues.includes(:custom_values).where(:tracker_id=>'N').all.sum{|c| c.custom_field_value(6).to_f}.to_f 
a += (custom_field_value(6).to_f - custom_value_for(6).try(&:value).to_f).to_f
end
self.custom_field_values = { 7=> a} 
b = self.custom_field_value(9).to_f
c= b-a
self.custom_field_values = { 8=> c} 
if (a > b )
errors.add(:base,"Exceeding the financial balance  the rest is #{c.to_s}")
end
end
`
