### ISSUE TITLE
After installing Custom Workflows into AWS Bitnami Redmine - Passenger stop working

### ISSUE THREAD

**Issue by bennopj** [anteo/redmine_custom_workflows#237]
i've installed redmine plugin following all steps. It worked out correctly. But when I restarted the services, apache/passenger stopped working. here is the passenger error.log main massage:

EasyPatchManager->register_patch: The 'patching_module' (RedmineCustomWorkflows::Patches::AttachmentPatch) already exists! (ArgumentError)
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/redmine_extensions-0.3.11/lib/redmine_extensions/patch_manager.rb:74:in `register_patch'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/redmine_extensions-0.3.11/lib/redmine_extensions/patch_manager.rb:120:in `register_model_patch'
  /opt/bitnami/redmine/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/attachment_patch.rb:64:in `<top (required)>'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:334:in `depend_on'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:246:in `require_dependency'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `each'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `block in eager_load!'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `each'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `eager_load!'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:356:in `eager_load!'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `each'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
  /opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
  /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `eval'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by picman** [comment]
See some hints here #1094.
