### ISSUE TITLE
Update Project Custom Field with sum of all Time Entries

### ISSUE THREAD

**Issue by bennopj** [anteo/redmine_custom_workflows#238]
Hi @tibillys, did you manage to solve that? Trying to do the same but struggling.

I have a calculated customer field in project that sums the Time Entries (of everything below that project). But in order to update this field i must go to project settings and just press save.

So i was thinking that i could use your plugin in order to save the project after a time entry.

_Originally posted by @tibillys in https://github.com/anteo/redmine_custom_workflows/issues/154#issuecomment-582270864_

**Comment by AirTibu** [comment]
Hi,

You should create a computed project custom field, with this code:

```

TimeEntry.where(:project => self.project.id ).sum(:hours).to_f

```

![image](https://user-images.githubusercontent.com/68789735/146659146-ff485537-1cbf-4b28-a004-14d6054df1a6.png)

You should create an ISSUE custom workflow to save the project to update project custom_field:

**AFTER SAVE**

```

self.project.save unless project.nil?

```

I hope it helps!

**Comment by AirTibu** [comment]
Hi,

Create a TimeEntry type custom workflow and add the same code this new flow.

**Comment by lublasco** [comment]
Worked perfectly. Thanks a lot for your help, @AirTibu !
