### ISSUE TITLE
Automatic create relation beetwen issues - cross projects

### ISSUE THREAD

**Issue by kfranckiewicz** [anteo/redmine_custom_workflows#24]
I would like to create automatic relation between issues (cross projects) during create new issue and add new note in existing issue. For example: In content of course I will write id issue destination "#123". Is it possible to write that with this plugin ?

**Comment by go2null** [comment]
It is possible. 

You will need to parse issue.description for the regexp, test if the referenced issues exists, check cross-project issue relations setting, and add the relation.

This functionality is in Redmine core for adding issue - commit links for repositories, so looking there would be a good place to start.

**Comment by kfranckiewicz** [comment]
Thanks for your reply. If I will find a free time I will look to this and paste the result here.

**Comment by picman** [comment]
See #74 and #75.
