### ISSUE TITLE
Change issue custom fields

### ISSUE THREAD

**Issue by wanler1** [anteo/redmine_custom_workflows#240]
Hello. I'm trying to make my custom field change when issue status changes to a certain value. I've tried a lot of different variants, but nothing works. Basically I wanna change the value of the custom field "Resolution" to "Done", when status changed to "Resolved"

Before script:

      if @issue.status_id_changed?
        if (@issue.status_id == 3)
          @issue.custom_field_value(9) == 12
        end
      end

What am I doing wrong?

**Comment by AirTibu** [comment]
Hi,

Try this code in before save section:

```

self.custom_field_values = { '9' => "Done".to_s}  ​if status_id_changed? && status_id == 3

```

If you would like to update from after save section, then you should save the update custom field values, like this:

```

​if self.status_id_changed? && self.status_id == 3
    self.custom_field_values = { '9' => "Done".to_s} 
    self.save_custom_field_values
end

```

I hope it helps!
