### ISSUE TITLE
Done%

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#242]
Is there any way to added values to
Done ratio (0,10,20,...100)
To be as example
( 0,5,10,15,25,.....,100)

**Comment by picman** [comment]
It is hard-coded in Redmine's code. You can either override the view in your custom plugin or change the code directly as follows in *app/view/issues/_attributes.html.erb*
```ruby
<% if @issue.safe_attribute?('done_ratio') && Issue.use_field_for_done_ratio? %>
-- <p><%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] }), :required => @issue.required_attribute?('done_ratio') %></p>
++ <p><%= f.select :done_ratio, ((0..20).to_a.collect {|r| ["#{r*5} %", r*5] }), :required => @issue.required_attribute?('done_ratio') %></p>
<% end %>
```

**Comment by ashrafalzyoud** [comment]
If I need 1%

**Comment by ashrafalzyoud** [comment]
but in bulk_update not update?

**Comment by AirTibu** [comment]
Hi,

Try this code:

```

@updated_done_ratio = Issue.where(:id => self.id).pluck(:done_ratio).first
@issue.update_columns(done_ratio: @updated_done_ratio + 1) unless new_record?

```

IMPORTANT: This code only works if the Administration -> Settings -> Issue tracking -> Calculate the issue done ratio with field value is "Use the issue field "

**Comment by picman** [comment]
@ashrafalzyoud You are right. You have to do the same modification in *app/view/issue_statuses/_form.html.erb* too.

**Comment by ashrafalzyoud** [comment]
It's working in status too
But still not working in bulk_edit

**Comment by ashrafalzyoud** [comment]
> Hi,
> 
> 
> 
> Try this code:
> 
> 
> 
> ```
> 
> 
> 
> @updated_done_ratio = Issue.where(:id => self.id).pluck(:done_ratio).first
> 
> @issue.update_columns(done_ratio: @updated_done_ratio + 1) unless new_record?
> 
> 
> 
> ```
> 
> 
> 
> IMPORTANT: This code only works if the Administration -> Settings -> Issue tracking -> Calculate the issue done ratio with field value is "Use the issue field "

How I can let the done_ratio take value of custom field float
Example 
1- Cfs[1]= 62.4  round the value 62
Done_ratio = 62
2- cfs[1]= 62.7 round the value 63
Done_ratio = 63

**Comment by AirTibu** [comment]
Hi,

It is not tested, I’m writing from my phone, but it should be something similar:

```

@issue.update_columns(done_ratio: custom_field_value(1).round ) unless new_record?

```

or try this code:


```

@issue.update_columns(done_ratio: custom_field_value(1).to_i ) unless new_record?

```

**Comment by ashrafalzyoud** [comment]
perfect man
