### ISSUE TITLE
How to highlight custom field when raise error for it?

### ISSUE THREAD

**Issue by iwill** [anteo/redmine_custom_workflows#245]
Hi, I have a custom field, and I'd like to validate its value in the Ruby script, but I need some helps:

- How to highlight (error style with red border) the custom field when it's invalid?

- How to get name of the custom field?

Thanks in advance!

**Comment by AirTibu** [comment]
Hi,

The custom_workflow plugin is not able to change the color of field frames, but you can raise an error message, like this:

![image](https://user-images.githubusercontent.com/68789735/151974071-14a9b1fb-8563-407e-ab72-21f899252078.png)

Use this code (change the custom_field ID and the validation):

```

unless custom_field_value(155) == "This is the right value"

    errors.add(:base,"This is not the right value for #{CustomField.find(155).name.to_s} field!") 

end

```
I hope it helps!

**Comment by iwill** [comment]
Yes, `CustomField.find(155).name` helped me! The following code can highlight the custom field:

```ruby
errors.add(CustomField.find(155).name, "#{CustomField.find(155).name.to_s} is invalid")`
```

Thank you very much! @AirTibu
