### ISSUE TITLE
Auto check the checked boxes in Related projects based on a custom field in the issue

### ISSUE THREAD

**Issue by AhoudAlten** [anteo/redmine_custom_workflows#246]
Hi there,

I'm wondering if there is a way of auto checking the check boxes in (Related projects (Edit project list)) based on a if statement of another custom field in the issue?

I've tried to do that by using the Custom Workflow plugin. But I couldn't get it to work. Is there a way where I can change the values selected in the Edit Project List by using the Custom Workflow plugin?

**Comment by AirTibu** [comment]
Hi,

If I understand well your problem, then you would like to check/uncheck checkboxes of related project, based on custom field changes on original issue. 

It is possible, but much more details are needed for code. Exact description of your intention:

- What is the project and tracker number of your issue?
- What is the custom field ID in the original issue?
- What are the values of this custom field?
- Which checkbox will be changed in related issues in case of different values?
What is the project name and tracker name of related issues? Should it be filter to tracker or all issues in related project are from same tracker/project?

Let me know the above requested information and I try to help on you!







> Hi there,
> 
> I'm wondering if there is a way of auto checking the check boxes in (Related projects (Edit project list)) based on a if statement of another custom field in the issue?
> 
> I've tried to do that by using the Custom Workflow plugin. But I couldn't get it to work. Is there a way where I can change the values selected in the Edit Project List by using the Custom Workflow plugin?

**Comment by AhoudAlten** [comment]
@AirTibu Thanks for the reply and hope I explained well.
Am using https://github.com/nanego/redmine_multiprojects_issue this plugin
https://github.com/nanego/redmine_multiprojects_issue/issues/58

**What is the project and tracker number of your issue?**
I have a main project and five sub-projects (each sub-project (1-3)have a tracker).
sub - project 1 (tracker 1) 
sub - project 2 (tracker 2)
sub - project 3 (tracker 3)
sub - project 4 
sub - project 5 

**What is the custom field ID in the original issue?**
custom_field_value_1
this custom field available in the first three trackers

**What are the values of this custom field?**
it is a drop down list, multi-selection, section values. for example,
sec 1, sec2, sec3, sec4, sec5, sec6, sec7, sec8
 
**Which checkbox will be changed in related issues in case of different values?**
if I choose sec1 or sec2 , the issue will be shared with (sub - project 4) >> auto check sub - project 4 in the related projects.
if I choose sec1 and sec 4, the issue will be shared with (sub-project 5) >> auto check sub - project 5 in the related projects.

**Comment by AirTibu** [comment]
Hi,

So the situation is a little different, as I'm not familiar the multiprojetcs_issue plugin.

In any case, I read into the [source code of the plugin](https://github.com/nanego/redmine_multiprojects_issue/blob/aa111bf9dd9b7d90fcbde0d49f2261c677d30a91/lib/redmine_multiprojects_issue/issues_controller_patch.rb), based on which I think something like this could be the solution:

Put this code into **BEFORE** section:

```

#Collect the actual values of multiselected custom field list:

   @old_selected_values = CustomValue.where(:custom_field_id => 1 ).pluck(:value).uniq.sort


#Collect the actual values of multiselect custom field list:

   @new_selected_values = [@issue.custom_field_value(1)].uniq.sort


#Compary the 2 arrays, if they do not match, it means the custom field list has been updated

   @update_projects = @old_selected_values != @new_selected_values

```

Put this code into **AFTER** section:

```

#Create new relationships between issue and projects

    RelatedProjects.new(self, [4]) if  ​["sec1","sec2"].include?(@new_selected_values)

    RelatedProjects.new(self, [5]) if  ​["sec1","sec4"].include?(@new_selected_values)


```

I hope it helps!
