### ISSUE TITLE
How to give a sequential serial number depends on inheritance??

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#249]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\ASHRAF~1.ALZ\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\ASHRAF~1.ALZ\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

seial | subject | tracker
-- | -- | --
1-0-0-0 | TEST 1 | A
1-1-0-0 | TEST 2 -> SUBTASK FROM TEST 1 | B
1-1-1-0 | TEST 3 -> SUBTASK FROM TEST 2 | C
1-1-1-1 | TEST 4 -> SUBTASK FROM TEST 3 | D
  |   |  
2-0-0-0 | EXAMPLE 1 | A
2-1-0-0 | EXAMPLE 2 -> SUBTASK FROM EXAMPLE 1 | B
2-1-1-0 | EXAMPLE 3 -> SUBTASK FROM EXAMPLE 2 | C
2-1-1-1 | EXAMPLE 4 -> SUBTASK FROM EXAMPLE 3 | D
2-1-2-0 | EXAMPLE 5 -> SUBTASK FROM EXAMPLE 4 | C
2-1-2-1 | EXAMPLE 6 -> SUBTASK FROM EXAMPLE 5 | D

</body>

</html>

**Comment by AirTibu** [comment]
Hi,

Use this code in AFTER SAVE section (change the custom field id (154) to your CFS id!):

```

if self==root

  self.custom_field_values = { 154 => Issue.where(:tracker_id=> self.tracker_id).all.count.to_i}

elsif !self.parent.nil? && !self.parent.custom_field_value(154).nil?

  self.custom_field_values = { 154 => (self.parent.custom_field_value(154).to_s + "-" + self.parent.children.where(:tracker_id=> self.tracker_id).all.count.to_s).to_s}

end

self.save_custom_field_values

```

I hope it helps!

**Comment by ashrafalzyoud** [comment]
@AirTibu 
THIS CODE not work and not depend in root

**Comment by AirTibu** [comment]
Hi,

What is the issue exactly? What is not working? 

The only thing was missing but have to manage, that the update will be done in case of new record. Try this code:

**BEFORE SAVE:**
```
@numbering_required = new_record?
```

**AFTER SAVE:**

```
 
if self==root && @numbering_required

  self.custom_field_values = { 154 => Issue.where(:tracker_id=> self.tracker_id,:project_id=> self.project_id).all.count.to_i}

elsif !self.parent.nil? && !self.parent.custom_field_value(154).nil? && @numbering_required

  self.custom_field_values = { 154 => (self.parent.custom_field_value(154).to_s + "-" + self.parent.children.where(:tracker_id=> self.tracker_id,:project_id=> self.project_id).all.count.to_s).to_s}

end

self.save_custom_field_values
 
```

The result should be this:

![image](https://user-images.githubusercontent.com/68789735/178848981-cca76244-faba-4077-b0f6-b5b8cc5cc355.png)


IMPORTANT: Do not forget to change the custom field id (4 places)

I hope it helps!

**Comment by ashrafalzyoud** [comment]
nice brother realy realy u are very intelligent man 
how i can let cfs[4] increment value +1 and start from 1 and and must be unique and read only
