### ISSUE TITLE
String data from Version Custom Field

### ISSUE THREAD

**Issue by deepakprahlad** [anteo/redmine_custom_workflows#25]
How to get the string value from the custom field which is a 'version' type? 

custom_field_value(6) returns a number depending on the selection by user. 

What I want is the "real string" for the version id (For example "Version-00.001" instead of its id)

**Comment by go2null** [comment]
``` ruby
version_name = Version.find(custom_field_value(6)).name
```

**Comment by deepakprahlad** [comment]
Throwing the followign error:

**Comment by go2null** [comment]
Sorry about that, forgot the '.value`

```ruby
version_name = Version.find(custom_field_value(6).value).name
```

**Comment by deepakprahlad** [comment]
Sorry, the new error is undefined method `value' for nil:NilClass

BTW my code looks like 
version_name = Version.find(custom_field_value($fixed_version_field_id).value).name

**Comment by go2null** [comment]
How is `$fixed_version_field_id` set?  It is returning a value that is not a valid `version_id`.

BTW, `fixed_version_id` is an standard issue field (displayed as 'Target Version' in the UI), so you may not want to use it for a custom field name. It is accessible directly thus:
```ruby
current_target_version = fixed_version

current_target_version_id = fixed_version_id
# or
current_target_verison_id = fixed_version.id
```

**Comment by deepakprahlad** [comment]
I set the value as  $fixed_version_field_id = 1		#field id of 'Fixed in Version' custom field

I am not familiar with Ruby, so I am not sure whether this is the correct method defining a variable, but it works, so I did that way :(

We are using the "Target Version" as issue observed version while reporting and Fixed In Version (defined as custom field) as the issue fixed version while resolving the issue :)

**Comment by deepakprahlad** [comment]
Solved my issue by the below code.

```ruby
version_name = Version.find(2).to_s
```

Thank you for the help @go2null

**Comment by go2null** [comment]
"We are using the "Target Version" as issue observed version while reporting and Fixed In Version (defined as custom field) as the issue fixed version while resolving the issue :)"

*Target Version* **IS** the *Fixed In Version* in Redmine.  Your usage will lead to being unable to properly use Redmine components such as Roadmap and Version Status.

What you should be defining as a custom field is the *Found In Version* field.

```ruby
fiv_icf_name = 'Found In Version'
fiv_icf = IssueCustomField.find_by_name(fiv_icf_name)
fiv_id = custom_field_value(fiv_icf)
if fiv_id.blank?
    errors.add '', "#{fiv_icf_name} is missing."
elsif fiv = Version.find(icf.value)
     version_name = fiv.name
     # your code goes here
else
    errors.add '', "#{fiv_icf_name} is invalid."
end
```

Also check out the [Example Workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows) for Error Trapping and the custom_values methods.

**Comment by aceccarelli** [comment]
Hello,
My case is reversed, I need to get the id based on a version name
For example:
version_id = Version.find_by_name ('trunk'). to_i

Thanks
