### ISSUE TITLE
Checking Multiple selectable List type Custom Field

### ISSUE THREAD

**Issue by atopcu** [anteo/redmine_custom_workflows#250]
Hi,
I've a multi selectable list type custom field. How can I check specific one is selected or not in list?

Regards!

**Comment by AirTibu** [comment]
Hi,

Use this code:

```
custom_field_value(180).to_a == [""]
```

if "true", then no selected item in multi selectable list. (Stands for: empty)

I hope it helps!

**Comment by atopcu** [comment]
> 

It is working. Thanks AirTibu!
