### ISSUE TITLE
IssueRelation.to_s is broken after #257

### ISSUE THREAD

**Issue by dmakurin** [anteo/redmine_custom_workflows#258]
Yes it fixed error in ruby 3.0 but current redmine version does not use nor support ruby 3.0. You should at least provide backward compatibility.

**Comment by dmakurin** [comment]
Turns out redmine actually supports ruby 3.0 (https://www.redmine.org/issues/34992). But compatibility for 2.7 would be great since it is still a maintainable version.

**Comment by picman** [comment]
Just tested width Ruby 2.7 and it seems to be working.
```shell
# ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
```
Could you add some details to your problem, please? production.log, Ruby version, Redmine version,...

**Comment by picman** [comment]
Very well. I've applied your patch. Could you test, the devel branch now, please?

P.S. A pull request next time, please.

**Comment by dmakurin** [comment]
Yeah, it works. Thank you.

**Comment by picman** [comment]
I've just fixed it a bit more professionally. It should work in Ruby 2.7 and 3.0 too.
