### ISSUE TITLE
close issue

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#259]
how i can prevent user to  close issue until THe VALUE in cfs[10] = 0
if tracker id =1
if cfs[10] > 0   NOT CLOSE and error msg
if cfs[10] = 0 close

**Comment by AirTibu** [comment]
Hi,

Use this code:

```

  if tracker_id==1 && custom_field_value(723).to_s.to_i>0
            errors.add(:base,'You cannot close the issue!')  
      return true
    end

```

The " return true" ensure, that the script will stop and don't save the issue.

I hope it helps!

**Comment by ashrafalzyoud** [comment]
```
  if status_id==5 && tracker_id==1 && custom_field_value(723).to_s.to_i>0
            errors.add(:base,'You cannot close the issue!')  
      return true
    end
```
i need this code if user try close  issue and cfs[10] >0

**Comment by ashrafalzyoud** [comment]
Thx brother @AirTibu
