### ISSUE TITLE
Как при создании новой задачи указать произвольный трекер?

### ISSUE THREAD

**Issue by JogicPogic** [anteo/redmine_custom_workflows#26]
Для создания новой задачи в блоке "after save" использую код, приведённый в официальном примере к плагину.

if @need_create
    sub_issue = Issue.create!(
    :author => User.current,
    :project => project,
    :tracker => tracker,                          # Так работает
    :tracker => Tracker.find(4),                     # Так НЕ работает!
    :assigned_to => author,
    :parent_issue_id => id,
    :subject => "Зарегистрировать договор",
    :description => "Присвоить номер и дату договора")
end

Проблема в том, что задача корректно создаётся только с текущим трекером:
  :tracker => tracker,
тогда как мне нужно указать другой трекер, вроде такого:
  :tracker => Tracker.find(4)
или такого:
   :tracker_id => 4

Вот сообщение об ошибке:
![redmine_custom_workflows](https://cloud.githubusercontent.com/assets/13277024/9149222/a7413aea-3db9-11e5-9012-0c2203f8075e.png)

Вопрос - как правильно указать трекер при создании задачи?

**Comment by anteo** [comment]
Лог указывает на ошибки валидации (Custom workflow exception: Validation failed), т.е. задача не может быть создана для данного трекера по какой-то причине. К сожалению, из скриншота понять какая именно ошибка выводится, не могу, приведите текст ошибки.

**Comment by JogicPogic** [comment]
Спасибо за ответ.
Я решил проблему так: 
1. Создать подзадачу как получится.
2. Назначить параметры подзадачи как требуется
3. Сохранить подзадачу.

  sub_issue1 = Issue.create!(
    :author => User.current,
    :project => project,
    :tracker => tracker,
    :assigned_to => author,
    :parent_issue_id => id,
    :subject => "Зарегистрировать договор",
    :description => "Присвоить номер и дату договора"
  )
  sub_issue1.tracker_id=1
  sub_issue1.start_date=self.start_date+1.day
  sub_issue1.assigned_to_id=6 
  sub_issue1.save!

**Comment by carukc** [comment]
For anyone else who might read this in future...

sub_issue1 = Issue.create!(
:author => User.current,
:project => project,
:tracker_id => 12, 
:assigned_to => author,
:parent_issue_id => id,
:subject => "Зарегистрировать договор",
:description => "Присвоить номер и дату договора"
)

where 12 is the ID of the tracker that you want to create.

I imagine that the other fields can be assigned during creation too.
