### ISSUE TITLE
Upgrade from 1.0.4 to 2.0.2, has an error, redmine 4.2.3 to 4.2.6

### ISSUE THREAD

**Issue by TerenceYL** [anteo/redmine_custom_workflows#260]
I just upgrade redmine from 4.2.3 to 4.2.6 and upgrade custom workflows from 1.0.4 to 2.0.2, 
after execute rake redmine:plugins:migrate RAILS_ENV=production
will raise an error:

/var/lib/gems/2.7.0/gems/activerecord-5.2.8/lib/active_record/associations.rb:1855: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activerecord-5.2.8/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
rake aborted!
NoMethodError: undefined method `autoloader' for #<Rails::Application::Configuration:0x000055bc658cb3e8>
Did you mean?  autoload_paths
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/railtie/configuration.rb:97:in `method_missing'
/opt/redmine/plugins/redmine_custom_workflows/after_init.rb:24:in `<top (required)>'
/opt/redmine/plugins/redmine_custom_workflows/init.rb:43:in `require_relative'
/opt/redmine/plugins/redmine_custom_workflows/init.rb:43:in `<top (required)>'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/lib/redmine/plugin.rb:187:in `block in load'
/opt/redmine/lib/redmine/plugin.rb:178:in `each'
/opt/redmine/lib/redmine/plugin.rb:178:in `load'
/opt/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:285:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/engine.rb:663:in `block in load_config_initializer'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/engine.rb:662:in `load_config_initializer'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/engine.rb:619:in `each'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/engine.rb:619:in `block in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.8/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.7.0/gems/railties-5.2.8/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by picman** [comment]
Fixed in _devel_ branch. I will release it.
