### ISSUE TITLE
calculate the number of subtasks

### ISSUE THREAD

**Issue by frankz96** [anteo/redmine_custom_workflows#262]
Hi there. I want to calculate the number of subtasks and save it to a custom field value. 
Is there anyone can help me?

**Comment by picman** [comment]
```ruby
n = @issue.descendants.visible.all.size
@issue.custom_values.each do |cv|
  if cv.custom_field_id == 74 # Your CF ID
    cv.value = n
    cv.save
  end
end
```

**Comment by frankz96** [comment]
> ```ruby
> n = @issue.descendants.visible.all.size
> @issue.custom_values.each do |cv|
>   if cv.custom_field_id == 74 # Your CF ID
>     cv.value = n
>     cv.save
>     break
>   end
> end
> ```

Thank you so mcuh! It's working.
