### ISSUE TITLE
Changing Boolean custom field value always changes to no/false

### ISSUE THREAD

**Issue by bootymcjudy** [anteo/redmine_custom_workflows#264]
I have a custom field value (Boolean type) called isBlocked where if an issue has a relation of blocked by I want this field to say yes/true.

Here is my code in the before_save,

`if blocked?`
`  self.custom_field_values={2 => true}`
`end`

When the workflow triggers, whether I put the value as true/false the custom field ends up always being 'No' or false.
When I put
`self.custom_field_values={2 => nil}`
it removes the boolean value correctly so the code does work, its just whether I put true/false it always sets the custom value to false/no

What is even more interesting is when I put false, it changes the value to No. Saving the issue again keeping false does nothing, but if I change it to true and save the issue it will show custom value changed No to No. So it looks like the custom value is set to No for both true and false

**Comment by AirTibu** [comment]
Hi,

Try with ‘yes’:

```

if blocked?
self.custom_field_values={2 => “yes”.to_s}
end


```
Or with 0/1:

```

if blocked?
self.custom_field_values={2 => 1}
end


```

**Comment by AirTibu** [comment]
It definitely works, I also use:

```
 
if blocked?
    self.custom_field_values = { '2'=> 1.to_s }
    self.save_custom_field_values
end
 
```

**Comment by bootymcjudy** [comment]
Thank you! It's working now!

so currently this works (if current ticket is blocked by the custom value says yes) when I click the issue and save it. What if I want this to behave automatically such that once a ticket blocks another the blocked ticket would change its field without having to edit+save?

**Comment by AirTibu** [comment]
Hi,

Use this code in the AFTER SAVE section of the issue, which is blocking the blocked issue:

```
 
    self.relations.where(:relation_type => IssueRelation::TYPE_BLOCKED).each do |blocked_issue|
   		
                blocked_issue.custom_field_values = { '2'=> 1.to_s }
    		blocked_issue.save_custom_field_values
    
     end
 
```

This code is update only the issues, where the relation type is "blocked". (Based on your mail, that was requested.)

Possible types of issue relations:
TYPE_RELATES = "relates"
TYPE_DUPLICATES = "duplicates"
TYPE_DUPLICATED = "duplicated"
TYPE_BLOCKS = "blocks"
TYPE_BLOCKED = "blocked"
TYPE_PRECEDES = "precedes"
TYPE_FOLLOWS = "follows"

I hope it helps!

**Comment by bootymcjudy** [comment]
Hey Air! Sorry for the delay in response, been busy with work etc and didn't have time to test your suggestion. When I try to save in the AFTER_SAVE section it indicates theres an undefined method 'where'

`Workflow script executable after saving observable object contains error: undefined method 'where' for []:IssueRelation::Relations Did you mean? when`

Any suggestions to get past this error? Also, are you suggesting this custom workflow should only have the AFTER_SAVE workflow or would be addition to the before_save script that was originally asked for?

**Comment by AirTibu** [comment]
Hi,

What is your observable object? Issue or Issue relation?

![image](https://user-images.githubusercontent.com/68789735/178863618-bb316027-597c-4e39-bc25-3288b71f8d6e.png)

**Comment by AirTibu** [comment]
Hi,

Use "Issue Relation" object and copy / paste this below code to AFTER_SAVE and BEFORE_DELETE section:

```
 
@blocks_to = issue_to.relations.any?{|r| r.relation_type == TYPE_BLOCKED } if issue_to
@blocks_from = issue_from.relations.any?{|r| r.relation_type == TYPE_BLOCKS } if issue_from


if self.issue_to && @blocks_to

   self.issue_to.custom_field_values = { '1'=> 1.to_s } if @blocks_to
   self.issue_to.custom_field_values = { '1'=> 0.to_s } unless @blocks_to
   self.issue_to.save_custom_field_values 

end

if self.issue_from && @blocks_from 

   self.issue_from .custom_field_values = { '1'=> 1.to_s } if @blocks_from 
   self.issue_from .custom_field_values = { '1'=> 0.to_s } unless @blocks_from 
   self.issue_from .save_custom_field_values 

end


```

**Comment by bootymcjudy** [comment]
Hey Air,

Thanks for your response! I'll have to do some thorough testing to see if it behaves as wanted on my production instance, but I'll ask if I run into any issues. Thanks so much for the help, appreciate it!
