### ISSUE TITLE
How can I  inherit custom fields values from Parent task?

### ISSUE THREAD

**Issue by AndreyGorloff** [anteo/redmine_custom_workflows#266]
I need to inherit parent task's custom field values to child issue.
Sorry, I'm noob in ruby.

**Comment by AirTibu** [comment]
Hi,

You should use this code in BEFORE SAVE section:

```

self.custom_field_values = {'100' => self.parent.custom_field_value(100).to_s}

```

If you are using the code in AFTER SAVE section, then you should save the values:

```

self.custom_field_values = {'100' => self.parent.custom_field_value(100).to_s}

self.save_custom_field_values

```

Do not forget to change the custom field id (100) to your custom field id!

I hope it helps!

**Comment by AndreyGorloff** [comment]
Thanks a lot. Very helpful.

**Comment by AndreyGorloff** [comment]
https://github.com/anteo/redmine_custom_workflows/issues/266#issuecomment-1159339524 help

**Comment by AndreyGorloff** [comment]
> AirTibu

AirTibu, we have some requirements. Can we talk somewhere on telegram, whatsap, skype?

**Comment by picman** [comment]
It's a bug in the plugin. You should update it to it's latest release v2.0.3.

**Comment by AndreyGorloff** [comment]
thanks. will try

**Comment by AndreyGorloff** [comment]
> 

Seems like it's related to 2.0.4 version. https://github.com/anteo/redmine_custom_workflows/issues?q=is%3Aclosed+milestone%3A2.0.4 
I experienced this issue on 2.0.3 version

**Comment by AirTibu** [comment]
> > AirTibu
> 
> AirTibu, we have some requirements. Can we talk somewhere on telegram, whatsap, skype?

I'm not a programmer, so I don't even use the preferred communication channels in the IT world, but if you think so, you can reach me here: airtibu2@gmail.com

**Comment by picman** [comment]
You are right. Sorry. v2.0.4 released.

**Comment by AirTibu** [comment]
@AndreyGorloff check your mailbox, I sent you answer.
