### ISSUE TITLE
performance Workflow script executable

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#267]
how i can increase performance or response time to decrease time to execute 
I'm note when I'm write code to subtask its take many seconds
my server hardware its very good
can i do configuration in**( mysql or nginx or passenger )** to reduced time response executable time

**Comment by picman** [comment]
In the first step you should identify what takes the longest time. If something takes seconds, it is suspicious even on a slow hardware. I'd start with the _production.log_.

**Comment by ashrafalzyoud** [comment]
Let's talk in general case
Some scripts need more than 30sec
Some more 15 seconds 
If I have hardware server excellent details 

How I can increase performance or response time?!? And where
Configuration **( rails,MySQL,Nginx,passenger)**

**Comment by ashrafalzyoud** [comment]
I know from my code
Because my code need update 4 level sub task until root and calculating field's 

But my question is 
If that possible if I can increase performance and reduce time
If I have good server and need some configuration in any where( rails,MySQl, Nginx,passenger)

**Comment by picman** [comment]
I think that there is no such configuration. What you should avoid in your code is recursion. It's a general rule for faster code.

**Comment by ashrafalzyoud** [comment]
`
if self.tracker_id == YOUR_BILL_TRACKER_ID
     self.parent.save
     self.parent.parent.save
     self.root.save
end
`
This code take time

**Comment by picman** [comment]
This code is at the first glance wrong. If you create an issue in the top level then self is equal to root, so this code causes an infinite loop. In other cases when root differs from self, saving the parent issue causes saving of its children. That is the reason why it takes very long. Also saving the parent causes calling this custom workflow for the parent, so the code self.parent.save and self.parent.parent.save makes no sense.I think that you should thing again what you need to achieve and rework this code completely.

**Comment by ashrafalzyoud** [comment]
This code I'm use it to update custom fields from child to root automatically I have 4 levels

I don't need user  resave update parent (opend_edit_save) until root to effect values to path until root

This code reduces time for user to open four task until root

If u can update the code to achieve my goal **OR** give me advice to optimize my server components or configuration

**Comment by picman** [comment]
```ruby
# Sample code
# Get a custom value from the currently updated issue and 
# propagate it to all its parents.
if @issue
  # Custom field's ID to copy
  cf_id = 10 
  # Get the custom value of this issue
  value = CustomValue.find_by(
            custom_field_id: cf_id,
            customized_type: 'Issue',
            customized_id: @issue.id)
  # Iterate over all parents and set/create the custom value
  parent_issue_id = @issue.parent_id
  while parent_issue_id
    v = CustomValue.find_by(
          custom_field_id: cf_id,
          customized_type: 'Issue',
          customized_id: parent_issue_id)
    if v
      v.value = value
      v.save
    else
      CustomValue.create(
        custom_field_id: cf_id,
        customized_type: 'Issue',
        customized_id: parent_issue_id,
        value: value
      )       
    end
    parent_issue_id = Issue.where(id:parent_issue_id).
      pick(:parent_id)
  end
end
```

**Comment by ashrafalzyoud** [comment]
this flowchart to explain what i do
![1212121212](https://user-images.githubusercontent.com/50211455/176313896-067292a6-e754-42f0-9cd2-c87a682482f2.png)
i need when cfs[1] in tracker bill all the parent update cfs[2,3,4]

**Comment by ashrafalzyoud** [comment]
@picman

**Comment by ashrafalzyoud** [comment]
[https://github.com/anteo/redmine_custom_workflows/issues/179](url)
#179

**Comment by picman** [comment]
You can use the algorithm posted by me, just with a few modifications related to your case. I'm pretty sure that it will be fast enough and no HW upgrade will be needed.

**Comment by ashrafalzyoud** [comment]
In your algorithm just using one cfs[1] I need four custom field update through root

**Comment by picman** [comment]
So just copy the code for all the four custom fields.

**Comment by ashrafalzyoud** [comment]
I will try 
Thx for your support 
And I will tell u the result

**Comment by ashrafalzyoud** [comment]
im try your code its only work if i have cfs[1] in all my tracker
im change your code like this its work only in bill and company tracker

```
if @issue
  # Custom field's ID to copy
  cf_id = 10 
  cf_id_1= 11
  # Get the custom value of this issue
  value = CustomValue.find_by(
            custom_field_id: cf_id,
            customized_type: 'Issue',
            customized_id: @issue.id)
  # Iterate over all parents and set/create the custom value
  parent_issue_id = @issue.parent_id
  while parent_issue_id
    v = CustomValue.find_by(
          custom_field_id: cf_id_1,
          customized_type: 'Issue',
          customized_id: parent_issue_id)
    if v
      v.value = value
      v.save
    else
      CustomValue.create(
        custom_field_id: cf_id,
        customized_type: 'Issue',
        customized_id: parent_issue_id,
        value: value
      )       
    end
    parent_issue_id = Issue.where(id:parent_issue_id).
      pick(:parent_id)
  end
end
```

**Comment by AirTibu** [comment]
Hi,

Try this code:

 ```

def total_value(from_cf,to_cf,issue_level)

     children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }

     cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (from_cf)).pluck(:value)

     cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (to_cf)).first

     cv.value = (cfv.inject(0){|sum,x| sum.to_i + x.to_i }).to_i

     cv.save(:validate => false)
end

@company_issue = @issue.parent
@tender_issue = @company_issue.parent
@budget_issue = @tender_issue.parent

total_value(1,2,@company_issue)
total_value(2,3,@tender_issue)
total_value(3,4,@budget_issue)
 
```

I hope it helps!

**Comment by ashrafalzyoud** [comment]
> Hi,
> 
> Try this code:
> 
> ```
> 
> def total_value(from_cf,to_cf,issue_level)
> 
>     children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }
> 
>     cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (from_cf)).pluck(:value)
> 
>     cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (to_cf)).first
> 
>     cv.value = (cfv.inject(0){|sum,x| sum.to_i + x.to_i }).to_i
> 
>     cv.save(:validate => false)
> end
> 
> @company_issue = @issue.parent
> @tender_issue = @company_issue.parent
> @budget_issue = @tender_issue.parent
> 
> total_value(1,2,@company_issue)
> total_value(2,3,@tender_issue)
> total_value(3,4,@budget_issue)
> ```
> 
> I hope it helps!

 the performance and more fast excute
this code before or new one
```
if self.tracker_id == YOUR_BILL_TRACKER_ID 
self.parent.save
 self.parent.parent.save 
self.root.save 
end
```
i will test this code

**Comment by ashrafalzyoud** [comment]
``
Workflow script executable before saving observable object contains error: undefined method `parent' for nil:NilClass Did you mean? present?
``

**Comment by AirTibu** [comment]
Hi,

If parent is not mandatory, then you should test it:

```
 
def total_value(from_cf,to_cf,issue_level)

    children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }

    cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (from_cf)).pluck(:value)

    cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (to_cf)).first

    cv.value = (cfv.inject(0){|sum,x| sum.to_i + x.to_i }).to_i

    cv.save(:validate => false)
end

# Change the tracker_id number to your bill tracker_id:
if tracker_id==3 && @issue

@company_issue = @issue.parent if @issue.parent
@tender_issue = @company_issue.parent if @company_issue.parent
@budget_issue = @tender_issue.parent if @tender_issue.parent

total_value(1,2,@company_issue) if @company_issue
total_value(2,3,@tender_issue) if @tender_issue
total_value(3,4,@budget_issue) if @budget_issue

end

```

**Comment by ashrafalzyoud** [comment]
**hint**
the cfs[2],cfs[3],cfs[4] its configured by computed custom field
i just need when im cfs[1]  in tracker bill enterd the cfs2,3,4  in different tracker parent updated
---> im see in your code u assumed the cfs2,3,4 not computed

**Comment by AirTibu** [comment]
Hi,

That's a problem. Change it to non-computed field.

**Comment by ashrafalzyoud** [comment]
where i can added in your code in @company_issue and  @tender_issue and @budget_issue
if i need calculate the remain money for company (Referral value - Paid value = Unpaid value)
`cfs[6] = total_value(1,2,@company_issue) if @company_issue - cfs[7]`

**Comment by AirTibu** [comment]
Hi,

The "total_value(1,2,@company_issue)" code has no return value, so you cannot use in math calculation. This code update the field fields. If you need the value for further calculation, then use the custom_field_value directly.

```
 
@referral _value = @company_issue.custom_field_value (1).to_f
@paid_value = @company_issue.custom_field_value (7).to_f

@unpaid = @referral _value - @paid_value


```

Please check ths custom_field_ids, because this code is only an example!

**Comment by ashrafalzyoud** [comment]
which faster plz 
this code
```
if self.tracker_id == YOUR_BILL_TRACKER_ID 
self.parent.save
 self.parent.parent.save 
self.root.save 
end
```
or this

 
```
def total_value(from_cf,to_cf,issue_level)

    children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }

    cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (from_cf)).pluck(:value)

    cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (to_cf)).first

    cv.value = (cfv.inject(0){|sum,x| sum.to_i + x.to_i }).to_i

    cv.save(:validate => false)
end

# Change the tracker_id number to your bill tracker_id:
if tracker_id==3 && @issue

@company_issue = @issue.parent if @issue.parent
@tender_issue = @company_issue.parent if @company_issue.parent
@budget_issue = @tender_issue.parent if @tender_issue.parent

total_value(1,2,@company_issue) if @company_issue
total_value(2,3,@tender_issue) if @tender_issue
total_value(3,4,@budget_issue) if @budget_issue

end

```

**Comment by ashrafalzyoud** [comment]
> 

where added this code?? inside the main code or another 1

**Comment by ashrafalzyoud** [comment]
im try this

```
def total_value(from_cf,to_cf,issue_level)

    children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }

    cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (from_cf)).pluck(:value)

    cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (to_cf)).first

    cv.value = (cfv.inject(0){|sum,x| sum.to_f + x.to_f }).to_f

    cv.save(:validate => false)
end

# Change the tracker_id number to your bill tracker_id:
if tracker_id==128 && @issue

@company_issue = @issue.parent if @issue.parent
@tender_issue = @company_issue.parent if @company_issue.parent
@budget_issue = @tender_issue.parent if @tender_issue.parent

total_value(239,238,@company_issue) if @company_issue
total_value(238,237,@tender_issue) if @tender_issue
total_value(237,236,@budget_issue) if @budget_issue

A = @company_issue.custom_field_value (29).to_f
B = @company_issue.custom_field_value (238).to_f

C = A- B
self.custom_field_values = { 242=> C}
end

```
but not work

**Comment by ashrafalzyoud** [comment]
@AirTibu plz if help

**Comment by ashrafalzyoud** [comment]
im try to do this code with paid and unpaid in same code
if u can help
```
def total_value(invoice_cf,paid_cf,referral_cf,unpaid_cf,issue_level)

    children_ids = Issue.where(:parent_id =>issue_level.id.to_i).pluck(:id) { |m| m.to_s }

    cfv = CustomValue.where("customized_id IN (?) AND custom_field_id = ?",children_ids, (invoice_cf)).pluck(:value)

    cv = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (paid_cf)).first

    cv.value = (cfv.inject(0){|sum,x| sum.to_i + x.to_i }).to_i

    cv.save(:validate => false)
    cv1 = CustomValue.where("customized_type = ? AND customized_id = ? AND custom_field_id = ?","Issue", issue_level.id.to_i, (unpaid_cf)).first
    cv1.value = referral_cf.to_f - cv.value.to_f

    cv1.save(:validate => false)


end

# Change the tracker_id number to your bill tracker_id:
if tracker_id==3 && @issue

@company_issue = @issue.parent if @issue.parent
@tender_issue = @company_issue.parent if @company_issue.parent
@budget_issue = @tender_issue.parent if @tender_issue.parent

total_value(1,2,3,4,@company_issue) if @company_issue
total_value(5,6,7,8,@tender_issue) if @tender_issue
total_value(9,10,11,12,@budget_issue) if @budget_issue

end
```

**Comment by ashrafalzyoud** [comment]
@AirTibu

**Comment by ashrafalzyoud** [comment]
any update PLZ

**Comment by MateusAnacleto** [comment]
Hi, 

I have a similar problem. In the after save i call a rest API:

```
  begin    
  response = RestClient.post url, {"routine":routine,"label":"AlterarDadosMovideskProdutos","params": [ticket,proj,documentacao,release,@tipoTarefa,@tipo,dataPrevisao]}.to_json, {content_type:'application/json',Authorization: token,  dbNameSpace: namespace}
  rescue RestClient::ExceptionWithResponse, RestClient::Forbidden , RuntimeError=> err
  raise WorkflowError, "#{err}"
  end
```

This call is taking around 30 seconds
  
 Can someone help me?

**Comment by ashrafalzyoud** [comment]
@AirTibu

**Comment by MateusAnacleto** [comment]
> Hi,
> 
> I have a similar problem. In the after save i call a rest API:
> 
> ```
>   begin    
>   response = RestClient.post url, {"routine":routine,"label":"AlterarDadosMovideskProdutos","params": [ticket,proj,documentacao,release,@tipoTarefa,@tipo,dataPrevisao]}.to_json, {content_type:'application/json',Authorization: token,  dbNameSpace: namespace}
>   rescue RestClient::ExceptionWithResponse, RestClient::Forbidden , RuntimeError=> err
>   raise WorkflowError, "#{err}"
>   end
> ```
> 
> This call is taking around 30 seconds
> 
> Can someone help me?

I found a workaround:

Seting the timeout for 10 seconds

  response= RestClient::Request.execute(:method => :post,:url => url,
                                     :payload => {"routine":routine,"label":"AlterarDadosMovideskProdutos","params": [ticket,proj,documentacao,release,@tipoTarefa,@tipo,dataPrevisao]}.to_json,
                                     :headers => {content_type:'application/json',Authorization: token,  dbNameSpace: namespace},
                                     :timeout => 10)

**Comment by ashrafalzyoud** [comment]
@AirTibu any help plz?

**Comment by husseindaradkah** [comment]
.

**Comment by MateusAnacleto** [comment]
hi,

I solve using a native ruby ​​asynchronous function:

task = Concurrent::TimerTask.new(run_now: true) do |t|
sleep 10 # 10 seconds

your code ....


  t.shutdown
  end
  task.execute  
 end
