### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by Centimane** [anteo/redmine_custom_workflows#27]
Hi, I'm wondering what the terms of use/redistribution are for this plugin. Does it fall under GPL(v2)?

**Comment by anteo** [comment]
Yes, it's open to use and distribute.

**Comment by Centimane** [comment]
Would it be reasonable to request that a license file is included with the plugin? Others have to review my request to use this and without terms laid out they'll likely say no.

I'd understand though if you don't want to attach a license to your work, but I'll provide a link to the GPLv2 license.

http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by anteo** [comment]
Included a license into the project
