### ISSUE TITLE
How can I copy custom fields values "id 2" to "id 55"?

### ISSUE THREAD

**Issue by cbmarchetti** [anteo/redmine_custom_workflows#271]
I need to create a baseline of the custom field "2" so that I can compare it with the custom field "55"

AFTER SAVE 
	 if @issue.status_id == 1 && @issue.tracker_id == 4
	*****	custom_field_value(55)  = custom_field_value(cfs[2].try(:position))*******
	 end

**Comment by cbmarchetti** [comment]
if @issue.status_id == 1 && @issue.tracker_id == 4
if custom_field_value(2) != custom_value_for(2).try(&:value)
      self.custom_field_values = { '55' => @cf_key.to_s }
      self.save_custom_field_values 
end
end

**Comment by AirTibu** [comment]
Hi,

What does it mean the "baseline" exactly? What is the type of custom_fields (text, number or list)? Are multiple values allowed for custom_fields?
