### ISSUE TITLE
How can I copy or create tags from custom fields values?

### ISSUE THREAD

**Issue by cbmarchetti** [anteo/redmine_custom_workflows#272]
@cf_key_value = CustomFieldEnumeration.where(:id=> custom_field_value(1).to_s,:custom_field_id => '1').first.to_s

if @issue.tracker_id == 4
if custom_field_value(1) != custom_value_for(1).try(&:value)
self.tag_list.add(@cf_key_value)
self.save
end
end

**Comment by AirTibu** [comment]
Hi,

Use this code in **BEFORE SAVE** section:

```
 
if (custom_field_value(1) != custom_value_for(1).try(&:value)) && tracker_id == 4
    self.save_custom_field_values
    self.tag_list.add(CustomFieldEnumeration.where(:id=> custom_field_value(1).to_s,:custom_field_id => '1').first.to_s)
end
 
```


I hope it helps!

**Comment by cbmarchetti** [comment]
Hi, thanks for your help, but it's not working yet
[tags.zip](https://github.com/anteo/redmine_custom_workflows/files/9107839/tags.zip)

**Comment by AirTibu** [comment]
Hi,

This code was tested and works properly. Do you use any special plugin for tags?

**Comment by cbmarchetti** [comment]
redmineup_tags  2.0.11
https://www.redmineup.com/pages/plugins/tags/

![image](https://user-images.githubusercontent.com/104323419/178886394-78962d34-e18f-41c4-a0eb-1280931295bb.png)

**Comment by AirTibu** [comment]
Hi,

Try it with @issue instead of self:

```
 
if (custom_field_value(1) != custom_value_for(1).try(&:value)) && tracker_id == 4
    @issue.save_custom_field_values
    @issue.tag_list.add(CustomFieldEnumeration.where(:id=> custom_field_value(1).to_s,:custom_field_id => '1').first.to_s)
end


```
