### ISSUE TITLE
time_entry is necessary when issue is in specific status

### ISSUE THREAD

**Issue by frankz96** [anteo/redmine_custom_workflows#273]
Here is what i want:
time_entry is necessary when issue is in specific status.

for example: 
if @issue.status_id == 3
if time_entry is empty
errors.add '', 'Please fill in the time entry!'

Thanks a lot!

**Comment by AirTibu** [comment]
Hi,

Use this code:

```

if status_id==3 && @issue.time_entries.none?

  errors.add(:base,"Please fill in the time entry!")

end

```

I hope it helps!

**Comment by frankz96** [comment]
> Hi,
> 
> Use this code:
> 
> ```
> 
> if status_id==3 && @issue.time_entries.none?
> 
>   errors.add(:base,"Please fill in the time entry!")
> 
> end
> ```
> 
> I hope it helps!

Thank you so much! It works.
