### ISSUE TITLE
When using Before Destruction on issues, no error gets displayed

### ISSUE THREAD

**Issue by Seahawk240** [anteo/redmine_custom_workflows#275]
Hello,

I prevent the deletion of issues once someone worked on them. This way one can delete a new ticket, in the case they made a mistake or something.

My code is as follows:

```
if self.status_id != 8     
  errors.add(:base,"Nur neue Tickets können gelöscht werden.")
  throw(:abort)
end

if self.children?
  errors.add(:base, "Dieses Ticket kann nicht gelöscht werden, da untergeordnete Tickets existieren.")
  throw(:abort)
end	
	
if self.spent_hours > 0
  errors.add(:base, "Dieses Ticket kann nicht gelöscht werden, da schon Zeiten gebucht wurden.")
  throw(:abort)
end
```

The deletion of the issue gets prevented but when i click on delete, redmine still tells me deletion worked as intended and raises no errors.

Thank you for this amazing plugin and thanks to anyone willing to help me :)

Greetings Matthias

**Comment by AirTibu** [comment]
Hi,

Change this code:

`throw(:abort)`
 
 To this:

`return true`

This will interupt the running.

**Comment by Seahawk240** [comment]
Hi,

thanks for your reply. I finally came around trying this. Sadly it didn't work any ideas why?

Greetings Matthias

**Comment by picman** [comment]
This is not possible in the present code. `throw :abort` interrupts the plugin's destroy method, but the parent issue's destroy method will continue. `return true` is simply ignored'.

**Comment by picman** [comment]
This code will work in v2.0.6

*before destroy*

```ruby
# Suppress the original message "Issue deleted"
self.custom_workflow_messages[:notice] = ''
# Add your own error message
self.custom_workflow_messages[:error] = 'Issue cannot be deleted'
# Return false to stop processing of delete event
return false
```

**Comment by Seahawk240** [comment]
> This code will work in v2.0.6

It does! Just updated to v2.0.8
Thanks Man! Thanks for your amazing work on this project, really appreciate it!
