### ISSUE TITLE
Created issue related 

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#28]
Hello!

Similar to the subtasks for creating flow would create a new task but only relate to task source.

thanks!

**Comment by go2null** [comment]
I'm on mobile right now, but check out the examples.
 ([Example-Workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows))

**Comment by aceccarelli** [comment]
Eu  verifiquei mas os exemplos cita apenas subtarefa. Pela minha ignorancia em ruby não consegui abstrair para a tarefa relacionada.
Se puder me ajudar, agradeço.

**Comment by aceccarelli** [comment]
Hello,
Can you create the task in another project but could not create the relationship between the source task and this created. I researched the issues of wiki and historiography but found nothing to help me.

I need the following condition to the workflow:

1. Create a task in another project only if you no longer have it created and linked to this task that I'm changing.

Thanks!

**Comment by picman** [comment]
#75
