### ISSUE TITLE
save custom field user

### ISSUE THREAD

**Issue by cbmarchetti** [anteo/redmine_custom_workflows#284]
Hi,
I need to save custom field values to users. 

Any idea??

self.custom_field_values = { 147=> CustomValue.where(:customized_id => @user.id.to_s, :custom_field_id => '131').first.to_s}
self.save_custom_field_values 
![image](https://user-images.githubusercontent.com/104323419/196698243-fe84707b-576f-414c-9e36-4c5b1ee4c32c.png)

**Comment by picman** [comment]
You must consider the situation when a user is being created (doesn't exist yet). So, this code would work:
```ruby
unless new_record?
  self.custom_field_values = { 147=> CustomValue.where(customized_id: @user.id, custom_field_id: 131).first }
  self.save_custom_field_values
end
```

**Comment by cbmarchetti** [comment]
thanks for the support!
