### ISSUE TITLE
Send notification to user when a certain custom field value is chosen

### ISSUE THREAD

**Issue by lublasco** [anteo/redmine_custom_workflows#286]
Hi, I've got a similar need to the one addressed in #216 . However it is not the same case and I can't find the write code. 

I need to send a notification to a certain Redmine user (let's call it user5 with id 5), when a certain value Y ("valueY") is chosen in a list custom field X (id=72). Note that the user might not be author, assignee or watcher of the issue.

Could you please rewrite the code for this requirement? Thank you in advance very much for your help!

**Comment by AirTibu** [comment]
Hi,

Try this code:

BEFORE SAVE SECTION:
```
 @notification  = custom_field_value(72).to_s == "valueY".to_s
```

AFTER SAVE SECTION:
```
if @notification
    mailuser=User.find(5)
           
        @html = "<b><p><strong>Dear #{mailuser.firstname} #{mailuser.lastname},</strong></p>
        <p>Please be informed, that value Y has been selected at issue: #{@issue.id} .</p>
        </b>".html_safe
           
    CustomWorkflowMailer.deliver_custom_email(mailuser, "The Y value has been selected: Redmine ID: #{@issue.id}", @html )
end
```

I hope it helps!

**Comment by lublasco** [comment]
Hi @AirTibu Thanks a lot for your help!! The workflow worked perfectly with your code!

**Comment by lublasco** [comment]
Hi, @picman & @AirTibu 
This code doesn't seem to work anymore with Redmine 5. The log states: "Custom workflow Send notification when custom field gets certain value 2, #4 exception: wrong number of arguments (given 3, expected 1..2)"
It seems that the code for "CustomWorkflowMailer.deliver_custom_email" should be modified. Could you please check this?
Thank you very much in advance for your help!

**Comment by picman** [comment]
I think that it shoul look like
```ruby
CustomWorkflowMailer.deliver_custom_email(
  mailuser, 
  subject: "The Y value has been selected: Redmine ID: #{@issue.id}", 
  html_body: @html )
```
