### ISSUE TITLE
Update parent status - Need help

### ISSUE THREAD

**Issue by ngtquavn** [anteo/redmine_custom_workflows#287]
Hi all, 

I want to create a custom workflow for updating parent status when the sub-task status changes, but nothing happens. My code as below: 
  # before save
  if @issue.status_id_changed? && @issue.status_id ==2
    @check = status_id_changed? 
  end

  # after savve
  if !parent.nil? && @check
    self.parent.status_id == 2
    self.parent.save
  end

Please help me in this case

**Comment by picman** [comment]
```ruby
if !parent.nil? && @check
-- self.parent.status_id == 2
++ self.parent.status_id = 2
   self.parent.save
end
```

**Comment by ngtquavn** [comment]
Thank @picman
