### ISSUE TITLE
date_start automatically set to current datetime

### ISSUE THREAD

**Issue by Tinostarn** [anteo/redmine_custom_workflows#29]
Hi,

I'm looking for a solution to this workflow : 
A customer create a ticket, the "Date created" field is set, the status "New".
When we change the ticket status to "In progress", I'd like to have a custom field "Date started" automatically set to the current datetime, and having.

What's the easiest way to do that, without touching to Ruby if possible ? 

Thanks a lot

**Comment by LeDistordu** [comment]
Very good idea. I think a useful part of this workflow would be then to switch automatically the status of the current issue to determined value when an admin answers, like I ask in the following issue : https://github.com/anteo/redmine_custom_workflows/issues/30

**Comment by go2null** [comment]
Redmine has a built in "Start Date" field.

**Comment by go2null** [comment]
```` ruby
start_date = Date.today if status.name == 'In progress' && status_was.name == 'New'
````

**Comment by go2null** [comment]
The above will reset the 'Start date' whenever the New to In progress transition occurs.

**Comment by supertino7** [comment]
Hello,

You're right, Redmine has a built in "start date" field BUT 
the format seems to be a simple "date", no ? 

![image](https://cloud.githubusercontent.com/assets/4602440/10007324/9c22c344-60c4-11e5-9661-65a9452170ed.png)

What we need is datetime format.

Ok for your condition which is in fine trivial. But where is it supposed to be paste ? 

Thanks a lot :)

**Comment by go2null** [comment]
I'm on mobile right now, but check out the examples.
 ([Example-Workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows))
