### ISSUE TITLE
How can I get related issues (only copy_from and copy_to)

### ISSUE THREAD

**Issue by ngtquavn** [anteo/redmine_custom_workflows#290]
Hi all, 

Please help me get list related issues only including copy_from and copy_to lists. 

Thank you in advance.

**Comment by AirTibu** [comment]
Hi,

Use this code:

```

@relations = "#".to_s +  IssueRelation.where("relation_type = ? AND (issue_to_id = ? OR issue_from_id = ?)","copied_to", self.id, self.id).pluck(:issue_from_id,:issue_to_id).uniq.compact.join(', #').squish.to_s

 self.custom_field_values = {'1' => @relations.to_s}
 self.save_custom_field_values

````

The first row collect the issues, with "#" prefix. The last 2 rows just add the result to a custom field, like this:

![image](https://user-images.githubusercontent.com/68789735/208983191-d015309e-3fa1-4384-9e26-4fa0d8e1fef4.png)

If you need only an array of issue ids, then use this code:

```

@relation_array = IssueRelation.where("relation_type = ? AND (issue_to_id = ? OR issue_from_id = ?)","copied_to", self.id, self.id).pluck(:issue_from_id,:issue_to_id)

````

I hope it helps!

**Comment by ngtquavn** [comment]
It works for me. 

Thanks for your help.

**Comment by AirTibu** [comment]
> It works for me.
> 
> Thanks for your help.

Your welcome! Don’t forget to close this issue!
