### ISSUE TITLE
inherited watchers(users/group) to subtask

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#291]
how i can inherited group watcher to subtask

**Comment by AirTibu** [comment]
Hi,

Use this code in AFTER_SAVE section:

```

unless self.parent.nil?
  self.parent.watcher_user_ids.each do |w_user|
      Watcher.create(:watchable_type=> 'Issue',:watchable_id=> self.id,:user_id=> w_user)
  end
end


```
I hope it helps!

**Comment by ashrafalzyoud** [comment]
I will test it
Thx for your reply
And we miss u @AirTibu

**Comment by ashrafalzyoud** [comment]
thx @AirTibu  its work for me 
im using this example to[]( https://github.com/anteo/redmine_custom_workflows/issues/161)
 **how i can added group only as watcher without  every on of user??**
@AirTibu

**Comment by AirTibu** [comment]
Hi,

If you would like to add only the groups, than add a condition inside the loop, like this:

```

unless self.parent.nil?
  self.parent.watcher_user_ids.each do |w_user|
      Watcher.create(:watchable_type=> 'Issue',:watchable_id=> self.id,:user_id=> w_user) unless Group.find(w_user).nil?
  end
end

```

I hope it helps!

**Comment by ashrafalzyoud** [comment]
```
if self.assigned_to.is_a?(Group)
   arr = Array.new
   arr = Group.find(self.assigned_to_id).user_ids
   for item in arr
     self.add_watcher(User.find(item)) unless self.watched_by?(User.find(item))
   end
 end
```
how i can added  Assignee group = group as wachers?
this i want?

**Comment by AirTibu** [comment]
Hi,

Use this code in AFTER_SAVE section:

```

self.add_watcher(self.assigned_to) unless self.assigned_to.nil? || Group.find(self.assigned_to.id).nil? 

```
I hope it helps!
