### ISSUE TITLE
How can I copy or create tags from custom fields values? 

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#292]
#272 
 
```
if (custom_field_value(1) != custom_value_for(1).try(&:value)) && tracker_id == 4
    @issue.save_custom_field_values
    @issue.tag_list.add(CustomFieldEnumeration.where(:id=> custom_field_value(1).to_s,:custom_field_id => '1').first.to_s)
end


```
Not working if cfs[1] multiple value

**Comment by AirTibu** [comment]
Hi,

In case of multiple value field use this code:

```

CustomFieldEnumeration.where(id:custom_field_value(1).to_a,custom_field_id:'1').pluck(:name).each do |cfenum|
   @issue.tag_list << cfenum.to_s
end

```

I hope it helps!

**Comment by ashrafalzyoud** [comment]
`Custom workflow error (Please contact an administrator)
`
@AirTibu

**Comment by AirTibu** [comment]
Hi,

It's working fine for me. Use in before save section.

**Comment by AirTibu** [comment]
This code causing **Custom workflow error (Please contact an administrator) ** if you try to use on NON multiple value field.

**Comment by ashrafalzyoud** [comment]
1-its work only if im choose multiple value, but maybe use choose one value or three value
2- cfs1 look like this
![3333](https://user-images.githubusercontent.com/50211455/211420017-c07d7b11-5b94-4fa3-abae-a455ea34deb0.png)

**Comment by ashrafalzyoud** [comment]
IN MY CASE cfs id 8
![4444](https://user-images.githubusercontent.com/50211455/211421136-25927e99-6f23-428c-b3a5-ad60700e30be.png)

**Comment by ashrafalzyoud** [comment]
can u update the code the user can choose one value or multiple value

**Comment by AirTibu** [comment]
If the custom field type is **Multiple values**, then the code works if empty, if choosed only 1 option or choosed more option. I tested all the scenarios and it is working properly.

You can try with this code:

```

  CustomFieldEnumeration.where(id:custom_field_value(18).to_a,custom_field_id:'18').pluck(:name).each do |cfenum|
   self.tag_list.add(cfenum.to_s)
  end


```

**Comment by ashrafalzyoud** [comment]
its working thx for u alooooooooooooooooooot
