### ISSUE TITLE
Restructuring  task with subtask

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#294]
hi all  
i want to change the main task with subtask (parent task )
this pic describe what i want 
![pp](https://user-images.githubusercontent.com/50211455/216184303-b57f076f-eb95-4fd8-9297-4728165b7ba1.png)
if i will do it manualy these many step to do that
1- open issue_id(11) and edit the parent task = null
2- open issue_id(10) and edit parent task = 11
3- open issue_id(12) and edit parent task = 10
3- open issue_id(13) and edit parent task = 10
how i can do it automatic ,i have many task

**Comment by ashrafalzyoud** [comment]
@picman

**Comment by picman** [comment]
I don't know. To write a rake task?

**Comment by ashrafalzyoud** [comment]
Maybe this needed dif function

**Comment by qawsed55** [comment]
@ashrafalzyoud , you can import issuses and make there setup of parent\child
You need to add in CSV file field UNIC NUM, and in fields for parent task you need to setup what are whom.
Sorry, in English it is difficult for me. May be on screenshot you will understand what about I say.
What table I want to import:

![image](https://user-images.githubusercontent.com/16443881/224557875-03ad5930-5070-4ed2-9200-f175bdd28902.png)

How it will be imported (if you naming fields in CSV as field in issue - it will be chained automaticly when importing)
![image](https://user-images.githubusercontent.com/16443881/224557987-ef51690b-cdfe-428b-a9a8-e95c69f25f9d.png)
