### ISSUE TITLE
Switch status field on technician reply

### ISSUE THREAD

**Issue by LeDistordu** [anteo/redmine_custom_workflows#30]
Hello, 

I'd like to have the status field automatically set to "In progress" (or any other custom status) when a technician answer to a customer in a ticket, and this customer haven't replied yet.

How can I perform that ? 

Thank you for this module ;)

**Comment by kersm** [comment]
Hi,

I'm not sure how to decide for the technican answer.
But maybe my code for Changing Status, after Assingee was changed helps:

`# has assignee been changed
if assigned_to_id_changed?
  # status is NEW and not changed manually
  if status_id == 1 && !status_id_changed?
    # set status to ASSIGNED
    self.status_id = 8
  end
  # status is not NEW and not changed manually
  if status_id != 1 && !status_id_changed?
    # set status to FORWARDED
    self.status_id = 9
  end
end`
