### ISSUE TITLE
How to change status if Done ratio is changed to 100

### ISSUE THREAD

**Issue by nsdhanoa** [anteo/redmine_custom_workflows#307]

**Comment by picman** [comment]
Issue::before_save
```ruby
if self.done_ratio == 100
  self.status_id = 5
end
```

**Comment by nanaksingh13** [comment]
i had tried that earlier but then i cannot change issue status

**Comment by picman** [comment]
That is strange. I've tested it and it worked. Verify that the issue status ID and done_ration exist in your system. And also check the log for any errors. You can also add some debug messages to find out what went wrong, e.g.:
```ruby
Rails.logger.info ">>> #{self.status.name}"
```

**Comment by AirTibu** [comment]
> i had tried that earlier but then i cannot change issue status

Hi,

Usually this issue is occur when you have field, which is mandatory according to your workflow, but it is empty. In this case, the status won’t be changed. Check your workflow first!

I hope it helps!
