### ISSUE TITLE
Couldn't get rails to send an email using the example

### ISSUE THREAD

**Issue by fredsdc** [anteo/redmine_custom_workflows#308]
I tried to have a workflow send an email, using the given example and it gives the following error: undefined method `custom_email' for Mailer:Class

Do this still work?

**Comment by piotrsz772** [comment]
I have an error like this 

`Workflow script executable before saving observable object contains error: undefined local variable or method `issue' for #<Issue:0x00005621e7d15ce0> Did you mean? @issue `

but when i use @issue not working

**Comment by picman** [comment]
What is the observable object? How about `self.issue`?

**Comment by piotrsz772** [comment]
Observable object is **issue**  self.issue not working too

**Comment by piotrsz772** [comment]
![image](https://github.com/anteo/redmine_custom_workflows/assets/45937421/8f3c9dbb-d3d4-4a88-95cf-25f5d7348c72)

**Comment by picman** [comment]
If the observable object is Isssue, you can directly call its methods, so `author` instead of `self.issue.author`.

**Comment by piotrsz772** [comment]
Ok, it works for author issue but if i want to send email to selected email on the picture? There is a way?

![image](https://github.com/anteo/redmine_custom_workflows/assets/45937421/75a4cf9c-2c4e-42a4-b906-14f62dfa9a46)

**Comment by piotrsz772** [comment]
Yeah I did this, it is very nice plugin and simple but need some time to understand :) Thank you very much for your help.

**Comment by piotrsz772** [comment]
How can I set for Body html value?

**Comment by fredsdc** [comment]
I had a similar problem. Finally I used ActionMailer to build and send the mail out of Redmine constraints.

Where:
content_bh -> html of the body
content_bp -> text of the body
mail_to -> to
mail_cc -> cc
content -> subject
tags -> tags for which attachments to include, search in description

```
html_part = Mail::Part.new do
  content_type  'text/html; charset=UTF-8'
  body content_bh   
end

text_part = Mail::Part.new do
  body content_bp   
end

m=ActionMailer::Base.mail(
  from: User.current.mail,
  to: mail_to,
  cc: mail_cc,
  subject: content,
  body: '',
  content_type: "multipart/mixed"
)

self.attachments.select{|a| a.description.downcase.match?(tags.downcase)}.each do |a|
  m.attachments[a.filename]=File.read(a.diskfile)
end

m.part content_type: "multipart/alternative" do |p|
  p.html_part = html_part
  p.text_part = text_part
end

m.deliver_now
```

**Comment by picman** [comment]
You can use `html_safe` function:
```ruby
recipient = User.find(9)
CustomWorkflowMailer.deliver_custom_email(recipient, 
                                          'Subject', 
                                          '<b>Body</b>'.html_safe)
```
