### ISSUE TITLE
Administration not possible (redmine 3.1.0)

### ISSUE THREAD

**Issue by moatingodseye** [anteo/redmine_custom_workflows#31]
Installed 0.1.4 plugin, installation seems to go fine, no errors. But on attempting to go into redmine to the administration area. The plugin shows its loaded. The administration section has a new item which i think is supposed to say "Custom workflows" but in fact says "translation missing: en-GB.label_custom_workflow_plural" on clicking this i get an error message saying "Page not found" 404 error. The URL its attempted to access is <server>/redmine/custom_workflows. 
![problem](https://cloud.githubusercontent.com/assets/14743269/10014120/fb20dabc-610e-11e5-845d-3caef9ba8336.jpg)

**Comment by anteo** [comment]
Check whether you have all plugin files installed into /plugins folders correctly.
I have working 0.1.4 on redmine 3.1.0 with no problems.

**Comment by moatingodseye** [comment]
Thanks, the fact that you had it working helped. I found that the directory name for the plugin has to be redmine_custom_workflows. I had it as redmine_custom_workflows.0.1.4 and that made it appear to be installed but not actually work. Didn't realise the directory name was so important. I can get to the admin section now, just have to work out how to use it :)
