### ISSUE TITLE
Custom tables plugin

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#314]
Hi all
Can from your plugin git value from custom_tables plugin

**Comment by picman** [comment]
Try to formulate it better please. Your question makes no sence.

**Comment by ashrafalzyoud** [comment]
Thx for replying me fast
I want use your plugin to execute in custom table plugin
https://github.com/frywer/custom_tables

But I can't find the value or treat with it
If I need custom field from the table there and write the code

**Comment by AirTibu** [comment]
Hi,

Use this code to get the custom table values:

```

CustomValue.where(:customized_id => self.custom_entity_ids,:customized_type =>'CustomEntity').detect {|v| v.custom_field.external_name == "Threat"}.try(:value)

```

You should change the **"Threat"** word to you table column name! This is the external name of custom_field as below picture shown:

![image](https://github.com/anteo/redmine_custom_workflows/assets/68789735/e5144adb-844e-4c6a-9350-d43baca27b4c)


The result of above code is:

**1.1 Airborne particles/dust; Levegőben lévő részecskék/por**

All rows with ";" separation.

I hope it helps!

**Comment by ashrafalzyoud** [comment]
im try this code 
```
if self.custom_field_value(536) != self.custom_value_for(536).try(&:value) || self.custom_field_value(537) != self.custom_value_for(537).try(&:value)
    
     @aa =  CustomValue.where(:customized_id => self.custom_entity_ids,:customized_type =>'CustomEntity').detect {|v| v.custom_field.external_name == "AA"}.try(:value) 

    @bb = CustomValue.where(:customized_id => self.custom_entity_ids,:customized_type =>'CustomEntity').detect {|v| v.custom_field.external_name == "BB"}.try(:value)


    @combination_exists = !(@aa & @bb).empty?
 
errors.add(:base,"This   combination is exists!") if @combination_exists

end
```
but not working
if u can help where the wrong

**Comment by AirTibu** [comment]
The problem is, that the code I wrote give you back string and you try to compare as array.

**Comment by ashrafalzyoud** [comment]
Ok what the correct code
@AirTibu

**Comment by AirTibu** [comment]
Hi,

This code gives back array, what you can compare with other array:

```

@aa = CustomValue.joins("LEFT JOIN custom_fields ON custom_fields.id = custom_values.custom_field_id").where(custom_values: { customized_id:self.custom_entity_ids,customized_type:'CustomEntity'}, custom_fields: { name: 'AA'}).pluck(:value)

@bb = CustomValue.joins("LEFT JOIN custom_fields ON custom_fields.id = custom_values.custom_field_id").where(custom_values: { customized_id:self.custom_entity_ids,customized_type:'CustomEntity'}, custom_fields: { name: 'BB'}).pluck(:value)

errors.add(:base,"This   combination is exists!") unless (@aa & @bb).empty?

```

I hope it helps!
