### ISSUE TITLE
Set custom filed only when issue is created, not changed

### ISSUE THREAD

**Issue by vomus** [anteo/redmine_custom_workflows#317]
Hi!
I have a custom field for an issue and need to set it to a generated value only when the issue is first created. I created such a script

```
icf = IssueCustomField.find_by_name('Issue polycy')
self.custom_field_values = { icf.id => Time.now.strftime('Policy.%d%m%H%M%S-%y')  }
```

but it runs also when the issue is commented on. How does one limit the runtime?

**Comment by picman** [comment]
No support for the Russians here.
