### ISSUE TITLE
Access journal entries

### ISSUE THREAD

**Issue by chibacityblues** [anteo/redmine_custom_workflows#32]
Hey, great plugin!

I try to access the latest journal entry in my workflow. I can access the correct data via Rails console (e.g. Issue.find(1).journals.last.notes) but when I fill my custom field trough an after_save workflow, I only get entries like  **#<Journal:0x0000000a303630>**

I also tried setting the field via **self.custom_field_values= {'4' => self.journals.last.notes }**
but then I get the error message
**'Workflow script executable after saving observable object contains error: undefined method `notes' for nil:NilClass'**

Any hint on what I'm doing wrong?

**Comment by anteo** [comment]
Do you need access notes of the issue being saved? You can access it through self.current_journal.notes

**Comment by chibacityblues** [comment]
Hey anteo, thanks for the reply. With **self.custom_field_values= {'4' => self.current_journal.notes }** I still get **undefined method `notes' for nil:NilClass** on saving the workflow. What I intend to do is writing the latest journal note to a custom field so I can use it as a column in the issue list.

**Comment by anteo** [comment]
Note that when you create issue, you will have empty current_journal.
When you update issue, current_journal is always present, even when notes are empty.
So you need check the case when the new issue created

**Comment by chibacityblues** [comment]
Finally got this working. FYI:

(before saving observable object...)
````
unless @issue.current_journal.nil?
  @issue.custom_field_values = { '173' => @issue.current_journal.notes }
end
````
