### ISSUE TITLE
Interference with other redmine-plugins

### ISSUE THREAD

**Issue by MichaGeh** [anteo/redmine_custom_workflows#320]
Hi,

we use your redmine_custom_workflows and the helpdesk-plugin from RedmineUP. We use the helpdesk-plugin to create tickets from emails, for this mails are fetched via imap from an exchange-online mailbox and delivered to Redmine.

When I activate your plugin, the mails are no longer delivered. The helpdesk plugin moves the mails to a error-folder in the mailbox because an error occurs. When I remove your plugin, the helpdesk plugin works perfectly.

How can both plugins be used at the same time?

**Comment by picman** [comment]
Take a look into _log/production.log_ file. If there is an error, it should be described there.

**Comment by MichaGeh** [comment]
is it possible to disable event processing on emails in your plugin?

**Comment by picman** [comment]
No, it isn't.

**Comment by picman** [comment]
> unfortunately no errors, except that the mail can not be processed if your plugin is installed. what does these entries mean?:
> 
> ```
> = Running shared code for Attachment (#) "#<Attachment:0x00005642b83aaad8>"
> = Finished running shared code for Attachment (#) "#<Attachment:0x00005642b83aaad8>"
> = Running shared code for Issue (#) "IT-Helpdesk #: Testticket über OAuth"
> = Finished running shared code for Issue (#) "IT-Helpdesk #: Testticket über OAuth"
> ```
> 
> they are logged only if your plugin is installed

It's perfectly Okay, I think. it's logged that the plugin processes scripts assigned to certain events if any.

**Comment by MichaGeh** [comment]
even if no shared code is configured?
or are there other places than in a workflow to execute shared code on events?

**Comment by picman** [comment]
Yes, even when no workflow is defined. That is probably wrong. I will change it.
