### ISSUE TITLE
Actions possible on new tickets

### ISSUE THREAD

**Issue by pkoevesdi** [anteo/redmine_custom_workflows#325]
Sadly any new created tickets in our Redmine 5 installation become an asignee (if none is chosen then the current user). But we have the process, that status "new" (id = 1) means "unassigned", so no owner. Only then the next status is "assigned" and has an owner.
So I made the rule 
```
if @issue.status_id == 1
           self.assigned_to_id = ''
end
```
which works if a tickets gets changed, but not on a newly created one. Is it possible to trigger workflow scripts by creating a new ticket? If not, I'd like to set it as a feature request.

Thank You!

**Comment by picman** [comment]
Do you have it as a "Before save" script? As a "Before save" script it works for me. I've a default assignee set in the project's settings and the assignee is reset to nil when an issue of the given tracker is created. I'd also recommend changing `''` with nil:

```ruby
if @issue.status_id == 1
 self.assigned_to_id = nil 
end
```

**Comment by pkoevesdi** [comment]
Hmm, strange, but now it works, I "didn't change"® something. Sorry fo the disturbance, I really tested it thourougly before opening up this here, but somehow now it works as expected.
