### ISSUE TITLE
Mail sending from custom workflows

### ISSUE THREAD

**Issue by swiehr** [anteo/redmine_custom_workflows#328]
In older versions custom workflows had a quite configurable approach to send custom emails using templates - the `mailer_patch.rb` for this still exists but apparently is not applied anymore in `redmine_custom_workflows.rb` or anywhere else. In fact the patch seems orphaned. 
Instead there is the `CustomWorkflowMailer` class that only supports `body` and `subject` parameters.

Thus the question:
Are there any plans to re-establish the old configurable way of custom email sending since the patch was not discarded from the codebase? Or is this just some legacy code that has not been removed yet?

**Comment by picman** [comment]
It's a legacy code that hasn't been removed yet. I think that uses are not supposed to modify the source code of the plugin.

**Comment by picman** [comment]
#330
