### ISSUE TITLE
Help needed with custom_field date type

### ISSUE THREAD

**Issue by akkow** [anteo/redmine_custom_workflows#329]
For example I have this 'd', which does not work at all, but 'e' on the other hand works fantastic. I am trying to check for a specific day's custom_field_value(19)'s value, then raise an error or pass through accordingly. No matter what I change the `custom_values: {custom_field_id: 21, value: '2024-01-06'}` is just not working.

`d = project.issues.includes(:custom_values).where(:tracker_id=>'13',custom_values: {custom_field_id: 21, value: '2024-01-06'}, :status_id=>[16,18,22,27]).all.sum{|c| c.custom_field_value(19).to_f}.to_f
`
`e = project.issues.includes(:custom_values).where(:tracker_id=>'13',custom_values: {custom_field_id: 19, value: "8"}, :status_id=>[16,18,22,27]).all.sum{|c| c.custom_field_value(19).to_f}.to_f`

**Comment by picman** [comment]
Maybe you can try to debug it in the database. Firstly print out the generated SQL query. Secondly try the query in the database, whether it returns any results.
```ruby
Rails.logger.info project.issues.includes(:custom_values).where(:tracker_id=>'13',custom_values: {custom_field_id: 21, value: '2024-01-06'}, :status_id=>[16,18,22,27]).to_sql
```
```sql
mysql# SELECT * FROM...
```
I guess that in the database is stored something like '2024-01-06 00:00:00' and you compare it with '2024-01-06'.

**Comment by akkow** [comment]
@picman Thanks for the fast reply. We have checked on how it's stored on the database and it has saved well. As you can see in the screenshot value is saved as 'MMMM-mm-dd'.
![vaizdas](https://github.com/anteo/redmine_custom_workflows/assets/26257486/0fa059ff-50c1-4dd9-acfa-37d37d5bd2bf)

**Comment by picman** [comment]
Okay, have you tested the query produced by your code too?

**Comment by akkow** [comment]
We have resolved this issue, thanks for help.
