### ISSUE TITLE
Pop message once then allow to continue

### ISSUE THREAD

**Issue by zas0006** [anteo/redmine_custom_workflows#33]
I have situation where i need to force my developers to update a wiki with some information needed by another department BEFORE they mark the issue as resolved. This is only temporary, as once they migrate to use our git/Jenkins stack it will be redundant, so i was going to do this via a custom workflow.

What i would like to be able to do is pop a workflow error, increment a counter that will track that the error has displayed, and then if they save it again (barring any other issues prevent the save) it would allow then to continue in peace. 

Is there anything remotely like this available in this tool-set? I have tried a few different ways, but nothing seems to stick.

I thought maybe using a shared code workflow would do it, but no luck.

Any suggestions ill be greatly appreciated. 

Adam

**Comment by anteo** [comment]
Consider this:

```Ruby
unless new_record?
  $popup ||= {}
  $popup[User.current.id] ||= {}
  unless $popup[User.current.id].has_key?(self.id)
    $popup[User.current.id][self.id] = true
    raise WorkflowError, "This warning you should see once for issue"
  end
end
```
