### ISSUE TITLE
Send mail to the author when an issue is created

### ISSUE THREAD

**Issue by Hernan22** [anteo/redmine_custom_workflows#330]
Hello, thank you all for the work done on the plugin.

I am trying to implement a ticket system in redmine, whereby the customer can create a ticket via email.
I want the customer to receive a notification email when the issue is created. Redmine allows this if the option "I don't want to be notified of changes that I make myself" is unchecked, but this generates the inconvenience that all client actions, like notes, will be notified.
With the plugin I can send an email notification only when the ticket is created, which is perfect, but I have problems customizing the email. I would like it to be the same as the notification that Redmine sends if the option is unchecked, is it possible to do this? I tried to use templates but was unsuccessful.

This is my code:

before_save
`if new_record?
 @var = 1
end`

after_save
`if @var > 0
  CustomWorkflowMailer.deliver_custom_email(@issue.author, "[Ticket creado en #{@issue.project} ##{@issue.id}]", "#{@issue.description}")
end`

**Comment by picman** [comment]
I've restored the original functionality of the ability to use email templates. You can send such an email as follows:

Before script:
```ruby
@var = new_record?
```
After script:
```ruby
if @var && id
    sbj = "[#{project.name} - #{tracker.name} ##{id}]"
    sbj += " (#{status.name})" if Setting.show_status_changes_in_mail_subject?
    sbj += " #{subject}"
  CustomWorkflowMailer.deliver_custom_email(
    User.current,
    subject: sbj,
    template_name: 'mailer/issue_add',
    template_params: { 
      issue: self,
      issue_url: Rails.application.routes.url_helpers.url_for(controller: 'issues', action: 'show', id: id, host: 'localhost:3000')
    })
end
```

Could you test the functionality in the _devel_ branch?

**Comment by Hernan22** [comment]
It works, thank you!

**Comment by picman** [comment]
Great!

**Comment by piotrsz0772** [comment]
Can you help me with defintion template_name not working (plugin version 2.1.2). Not loading template.

if status_id == 7
  subject = "[#{tracker} ##{id}]"

  html_body = <<~HTML
    <p><strong>Hi, #{author}</strong></p>
  HTML

  CustomWorkflowMailer.deliver_custom_email(
    User.find_by_id(23),
    subject: subject,
    html_body: html_body,
    template_name: 'mailer/custom_email'
  )
end

<img width="161" height="134" alt="Image" src="https://github.com/user-attachments/assets/0eee2f6a-dcd3-4c75-b705-4bb41ab0b328" />
