### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by fabianocruzdf** [anteo/redmine_custom_workflows#331]
I'm new to Custom_Workflows, and I need help with an example: "Creating subtask if the issue's status has changed." I want to automatically create new subtasks only when I create a new issue. Can someone assist me with this?

**Comment by picman** [comment]
Before saving
```ruby
@var = new_record? && parent_id.nil?
```
After saving
```ruby
if @var
  issue = Issue.new
  issue.tracker_id = tracker_id
  issue.project_id = project_id
  issue.subject = 'Sub-issue'
  issue.status_id = status_id
  issue.priority_id = priority_id
  issue.author_id = author_id
  issue.parent_id = id
  issue.save
end
```

**Comment by fabianocruzdf** [comment]
> _Before saving_ script:
> 
> ```ruby
> @var = new_record? && parent_id.nil?
> ```
> 
> _After saving_ script
> 
> ```ruby
> if @var
>   issue = Issue.new
>   issue.tracker_id = tracker_id
>   issue.project_id = project_id
>   issue.subject = 'Sub-issue'
>   issue.status_id = status_id
>   issue.priority_id = priority_id
>   issue.author_id = author_id
>   issue.parent_id = id
>   issue.save
> end
> ```

Works like a charm!!
Thanks a lot.
