### ISSUE TITLE
Integration with repository code

### ISSUE THREAD

**Issue by marmat1** [anteo/redmine_custom_workflows#337]
I have been working with this great plugin for years. Once you have a lot of different workflows it would be very useful (and recommended) to manage the workflows code using a repository like Gitlab.

Is there any way to link code from workflows with a repository in order to manage changes?

Many thanks.

**Comment by picman** [comment]
No, there is no such option.

**Comment by marmat1** [comment]
Thanks for your answer. And in case we wanted to implement a solution, where are the workflows  saved?

**Comment by picman** [comment]
They are saved in _custom_workflows_ database table.

**Comment by marmat1** [comment]
Thanks!
