### ISSUE TITLE
Use a template other that the test_email

### ISSUE THREAD

**Issue by bigjay517** [anteo/redmine_custom_workflows#34]
Hello,

I can't seem to get the plugin to send an email using any other template other than the test_email template.

I would like to use the issue_edit template with different recipients, and possibly change the subject if possible.  I am not sure what other parameters I would need to pass to the different templates in order to use them.  Does the plugin support any other template besides the test_email template?  Am I able to use templates stored in any other path besides views/mailer/?  I do not have permission to change this folder and would like to store my own custom templates in the plugins directory of Redmine.

**Comment by anteo** [comment]
How to send 'issue_edit' mail:

```Ruby
issue = self
if issue.current_journal
  users = <list of users recipients>
  subject = <subject>
  journal = issue.current_journal
  details = journal.visible_details(users.first)
  Mailer.custom_email(:to => users, :subject => subject, :template_name => 'mailer/issue_edit', 
    :template_params => {
      :users => users, 
      :journal => journal, 
      :journal_details => details, 
      :issue => issue, 
      :issue_url => Rails.application.routes.url_helpers.url_for(:host => 'example.com', :controller => 'issues', :action => 'show', :id => issue, :anchor => "change-#{journal.id}")
    }).deliver
end
```

I would recommend use your own template, you can specify it in `:template_name` parameter to `Mailer#custom_email`. You can use absolute or relative to `app/views` paths there. You can create template file in your plugin views folder, for example, `<plugin_name>/app/views/mailer/my_template.html.erb` and specify it as `:template_name => 'my_template'`, Redmine should find it. 
You can pass parameters to that template through `:template_params`. You can also pass `:text_body` and `:html_body` parameters without need to pass `:template_name`

**Comment by bigjay517** [comment]
I tried a few different variations of this, but am still not able to get these to work.  My user is user id 66.
```ruby
if issue.current_journal
  subject = "Delivery Date Has Changed" 
  journal = issue.current_journal
  users = User.find(66)
  details = journal.visible_details(users.first)
  Mailer.custom_email(:to => users, :subject => subject, :template_name => 'mailer/issue_edit', 
    :template_params => {
      :users => users, 
      :journal => journal, 
      :journal_details => details, 
      :issue => issue, 
      :issue_url => Rails.application.routes.url_helpers.url_for(:host => 'example.com', :controller => 'issues', :action => 'show', :id => issue, :anchor => "change-#{journal.id}")
    }).deliver
end
```
Using this I get an error in my production.log
```log
== Running after_save custom workflow "Send Sales an Email on Delivery Date Change"
== Custom workflow exception: undefined method `first' for #<User:0x007fb79d1e1110>
 /media/data/redmine-2.6.0-3/apps/redmine/htdocs/plugins/redmine_custom_workflows/app/models/custom_workflow.rb:86:in `instance_eval'
 /media/data/redmine-2.6.0-3/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.19/lib/active_record/attribute_methods.rb:149:in `method_missing'
```
So I must not be passing the same "user" that the template is expecting?

I am also not having much luck using a template from any folder other than the redmine-2.6.0-3/apps/redmine/htdocs/app/views/mailer folder.  I put a custom template in redmine-2.6.0-3/apps/redmine/htdocs/plugins/redmine_custom_workflows/app/views/mailer called test_email_relative.text.erb and test_email_relative.html.erb and I get another undefined error.
```log
== Running after_save custom workflow "Send Sales an Email on Delivery Date Change"
== Custom workflow exception: undefined method `each' for nil:NilClass
```
I am using this as my workflow in this case
```ruby
  subject_line = "Delivery Date Changed"
  Mailer.custom_email(:subject => subject_line, :template_name => 'test_email_relative', :user => User.find(66)).deliver
```

I have tried listing the path as ../../plugins/redmine_custom_workflows/app/views/mailer/test_email_relative and I get the same error.  Any ideas what I am doing wrong still?

**Comment by anteo** [comment]
First, the name "users" says that it is the list of users, not one user, so you need to write:
```Ruby
users = [User.find(66)]
```
Second, you need to pass :template_params to Mailer#custom_email with at least empty hash {} as value (I fixed this error in repository):
```Ruby
subject_line = "Delivery Date Changed"
Mailer.custom_email(:subject => subject_line, :template_name => 'test_email_relative', :user => User.find(66), :template_params => {:url => 'http://example.com'}).deliver
```
(no need to specify :url unless you copied test_email.html.erb to test_email_relative.html.erb as is)

**Comment by bigjay517** [comment]
I really appreciate your help!  Thank you.
