### ISSUE TITLE
Send email to address in custom field?

### ISSUE THREAD

**Issue by jwr03** [anteo/redmine_custom_workflows#340]
I have a custom field called end_user_email_address.   That is the email address that a Redmine user is submitting an issue on behalf of.  
That email address is assumed to be someone who does not have a Redmine account.  

Is it possible to use the send email from your custom workflow to send email to the custom field's contents on CLOSE of a issue?  I noticed it used the User object which in this case I am not sure would work.  Thanks in advance
  Jeremy

**Comment by picman** [comment]
``` ruby
CustomWorkflowMailer.deliver_custom_email(nil, to: 'franz.kafka@prague.cz', subject: subject, text_body: text)
```

**Comment by jwr03** [comment]
I tried that as follows and get an error

    @subject = "This is a test of the workflow"
    @desc = "This is the body I hope Andrew gets this!"
    @to =" ***@***.***"
    CustomWorkflowMailer.deliver_custom_email(nil, :to => @to, :subject => @subject, :text_body => @desc)


  *   The error is:  "Workflow script executable after saving observable object contains error: wrong number of arguments (given 2, expected 3)

**Comment by picman** [comment]
What version of the plugin do you use?

**Comment by jwr03** [comment]
1.0.7  is there a newer version?

**Comment by jwr03** [comment]
I do really appreciate your help.  We upgraded to the latest plugin.  (2.1.1)

And we tried a few different variations of the code and still can’t seem to send to a custom email addresses that we hardcode.

My latest attempt is with this code and this code only in the Workflow script executable after saving observable object


@subject = "This is a test of the workflow"
@desc = "This is the body I hope Andrew gets this!"
@to = ***@***.******@***.***>
CustomWorkflowMailer.deliver_custom_email(nil, :to => @to, :subject => @subject, :text_body => @desc)


No email get sent.  ☹


***@***.***

**Comment by picman** [comment]
You will have to check _log/production.log_ for errors too and also your mail server.

**Comment by jwr03** [comment]
I am getting the following in the logs with latest version and adding nil as you mentioned.


/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
Error performing ActionMailer::DeliveryJob (Job ID: ec9e3218-bd17-4b8a-bc78-8da259a84a2e) from Async(mailers) in 0.25ms: ArgumentError (First argument has to be a user, was nil):
/usr/local/redmine-4.2.1/app/models/mailer.rb:37:in `process'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `tap'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/actionmailer-5.2.5/lib/action_mailer/delivery_job.rb:16:in `perform'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/execution.rb:39:in `block in perform_now'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/i18n-1.8.11/lib/i18n.rb:314:in `with_locale'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/logging.rb:48:in `tag_logger'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/execution.rb:38:in `perform_now'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/execution.rb:24:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/reloader.rb:73:in `block in wrap'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/reloader.rb:72:in `wrap'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/execution.rb:22:in `execute'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/activejob-5.2.5/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/home/redmine/.rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'

**Comment by picman** [comment]
Hm, you're right. Fixed in the branch _devel_.
