### ISSUE TITLE
Add All Project Members as Watchers

### ISSUE THREAD

**Issue by Hernan22** [anteo/redmine_custom_workflows#341]
How can I add all members of a project as watchers when an issue is created?

**Comment by picman** [comment]
Something like that as an after_save script might work:
```ruby
if subject.present? && journals.all.size == 0
  project.members.each do |m|  
    add_watcher(m.user) unless watched_by?(m.user)
  end
end
```

**Comment by Hernan22** [comment]
Thanks, it worked!

**Comment by Hernan22** [comment]
Hello again, how can I exclude the 'cliente' role with ID 10 from being added to the watchers?

Best regards

**Comment by picman** [comment]
```ruby
if subject.present? && journals.all.size == 0
  project.members.each do |m|  
    add_watcher(m.user) unless watched_by?(m.user) || m.role.id == 10
  end
end
```

**Comment by Hernan22** [comment]
Thank you, but it doesn't work, it doesn't add anyone as followers.

**Comment by picman** [comment]
And is there a member who is not among watchers yet and hasn't got role id 10?
