### ISSUE TITLE
Remove user from groups when locked

### ISSUE THREAD

**Issue by marmat1** [anteo/redmine_custom_workflows#343]
I would like to remove users from their groups when they are locked.

I have tried with an user after saving observable object workflow:

```
if (self.locked?)
  self.groups.remove
end
```

Is there any method in _user_ or _group_ classes to get it?

Many thanks.

**Comment by picman** [comment]
``` ruby
if locked?
  groups.delete_all
end
```

**Comment by marmat1** [comment]
Perfect! It works!

if self.locked?
  self.groups.delete_all
end
