### ISSUE TITLE
Check if version.due_date has changed

### ISSUE THREAD

**Issue by marmat1** [anteo/redmine_custom_workflows#345]
How can I check if **version.due_date** has changed and get the previous value?

On custom fields I usually use something like:

@original_value = self.custom_value_for(id).try(&:value)

To get the original value... but, unfortunately, there is not a value method for due_date, neither a _changed? property.

Many thanks in advance.

**Comment by picman** [comment]
I think that you can ask for version.effective_date value in the database in before_save script.

**Comment by marmat1** [comment]
Thanks for your help!

I am sorry, but I have no idea about how to ask database from a workflow, and couldn't find any example

I have tried with:

(before saving)
`@original_value_due = self.effective_date`
(after saving)
`if self.due_date != @original_value_due && !@original_value_due.nil?`

As expected... it doesn't work :(

**Comment by picman** [comment]
```ruby
 @original_value_due = Version.where(id: self.id).pluck(:effective_date)
```

**Comment by marmat1** [comment]
Thank you so much for your support!!!!

It works!

**Comment by marmat1** [comment]
There was a bug in my code... if you want to compare self.due_date with @original_value_due, you must take into account that @original_value_due will return an array, so it is neccesary to get the first element

@original_value_due =  Version.where(id: self.id).pluck(:effective_date).first
