### ISSUE TITLE
Integration with Custom Workflows Plugin for Enhanced Feature Implementation

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#346]
I am currently working on integrating a feature from your Custom Workflows plugin into my Redmine plugin. Specifically, I need to activate or run a specific setting programmatically based on certain conditions within my plugin.

Could you please provide guidance or point me to the appropriate API methods or hooks in your plugin that would allow me to execute this setting safely? If there are any examples or documentation you could share, that would also be extremely helpful.

Thank you for your time and assistance.

**Comment by picman** [comment]
A preferred way how to modify Redmine functionality is via hooks:
https://www.redmine.org/projects/redmine/wiki/Hooks
