### ISSUE TITLE
How can I view all variables that I can use?

### ISSUE THREAD

**Issue by RAPGabs** [anteo/redmine_custom_workflows#348]
Is there an easy way to view all variables that I can use in this extension?

I am new to ruby and this Redmine, to any sort of guidance would be really helpful.

**Comment by picman** [comment]
No, you have to look into Redmine's source codes what is available.

**Comment by picman** [comment]
In the source code:

If the observable object is Issue for example, look into _app/models/issue.rb_ and search for `safe_attributes`.

In the datebase:

```sql
desc issues;
```
And you can use all Fields.
