### ISSUE TITLE
Is there any way to update a parent from a child's workflow?

### ISSUE THREAD

**Issue by carukc** [anteo/redmine_custom_workflows#35]
Extremely useful plugin.  Thank you.

I see that it provides read access to a parent (if one exists).  Is there any way to get it to write or otherwise update a parent when saving a child?

In my case I want to automatically change the status of a parent when something specific happens to a child.

Chris

**Comment by zas0006** [comment]
Here is how i did it:

    parent.update({:status_id=>15})

This can be used to update grandparent or root issues as well using

    parent.parent.update({:status_id=>15})

or

    root.update({:status_id=>15})

respectively

**Comment by carukc** [comment]
That's really helpful!  Thank you very much.

**Comment by zas0006** [comment]
Glad to hear!

If that takes care of youre request, be sure to close it! We dont want people thinking that anteo has a lot of issues outstanding now do we? :)

**Comment by carukc** [comment]
quite right!
