### ISSUE TITLE
Redmine 6.0.0

### ISSUE THREAD

**Issue by DmitryMigunov** [anteo/redmine_custom_workflows#350]
After upgrading to Redmine 6.0.0, I encountered a `NoMethodError` related to the `before_add_for_users method` in the plugin.

```
~/.gem/gems/activerecord-7.2.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `before_add_for_users' for class Group (NoMethodError)
Did you mean?  after_add_for_users
	from /.../redmine-6.0.0/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/models/group_patch.rb:48:in `block (2 levels) in prepended'
	from /.../redmine-6.0.0/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/models/group_patch.rb:47:in `each'
	from /.../redmine-6.0.0/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/models/group_patch.rb:47:in `block in pre
	pended'
```

**Comment by carlos0424** [comment]
Actualizar el plugin
Edita los archivos del plugin en las siguientes ubicaciones:

lib/redmine_custom_workflows/patches/models/wiki_page_patch.rb
lib/redmine_custom_workflows/patches/models/project_patch.rb
lib/redmine_custom_workflows/patches/models/issue_patch.rb
lib/redmine_custom_workflows/patches/models/group_patch.rb

Reemplazar before_add_for_* y after_add_for_*: Estos métodos ya no existen en Rails 6+. En su lugar, define métodos explícitos para manejar los eventos, como add_attachment o remove_attachment.

Eliminar o comentar bloques de código incompatibles:

%i[before_add before_remove after_add after_remove].each do |observable|
  send("#{observable}_for_attachments") << lambda { |event, page, attachment|
    WikiPage.attachments_callback(event, page, attachment)
  }
end

Reemplazo:

def self.add_attachment(page, attachment)
  attachments_callback(:before_add, page, attachment)
  # Lógica para agregar adjuntos
  attachments_callback(:after_add, page, attachment)
end

def self.remove_attachment(page, attachment)
  attachments_callback(:before_remove, page, attachment)
  # Lógica para eliminar adjuntos
  attachments_callback(:after_remove, page, attachment)
end

**Comment by picman** [comment]
Díky moc za analýzu. Upravím podle toho. Jestli mi zbyde čas, tak se naučím i Španělsky ;-)

**Comment by picman** [comment]
@carlos0424 Who calls your new methods like `self.add_attachment(page, attachment)`?

https://github.com/rails/rails/issues/45316

**Comment by picman** [comment]
According to the doc above, methods `before_add_for`,.. are generated, if we add `before_add` option into `has_many`. It works for me, if I modify let's say _project_patch.rb_ as follows:
```ruby
++has_many :attachments,
++         lambda { order("#{Attachment.table_name}.created_on ASC, #{Attachment.table_name}.id ASC") },
++         as: :container,
++         dependent: :destroy,
++         inverse_of: :container,
++         before_add: Proc.new {}, # => before_add_for_attachments
++         after_add: Proc.new {}, # => after_add_for_attachments
++         before_remove: Proc.new {}, # => before_remove_for_attachments
++         after_remove: Proc.new {} # => after_remove_for_attachments

def self.attachments_callback(event, project, attachment)
  project.instance_variable_set(:@project, project)
  project.instance_variable_set(:@attachment, attachment)
  CustomWorkflow.run_shared_code(project) if event.to_s.starts_with? 'before_'
  CustomWorkflow.run_custom_workflows(:project_attachments, project, event)
end

%i[before_add before_remove after_add after_remove].each do |observable|
  send("#{observable}_for_attachments") << lambda { |event, project, attachment|
    Project.attachments_callback event, project, attachment
   }
end
```
