### ISSUE TITLE
How to create a new issue that has a required custom field?

### ISSUE THREAD

**Issue by carukc** [anteo/redmine_custom_workflows#37]
I am trying to generate a new Issue based on a tracker that has a mandatory custom field.

if @create_instructor_booking_request
  booking = Issue.create!(
    :author => User.current,
    :project => project,
    :tracker_id => 11, 
    :parent_issue_id => id,
    :subject => "Reservation",
    :description => description,
    "Days" => self.custom_field_value(36))

I've also tried 

  :Days => ...

In each case the logs tell me that the field 'Days' does not exist. 

Does anyone know how to initialize an issue that requires a custom field?

Thanks
Chris

**Comment by carukc** [comment]
OK... for anyone else who stumbles this way... here's how:

booking = Issue.create!(
    :author => User.current,
    :project => project,
    :tracker_id => 11, 
    :parent_issue_id => id,
    :subject => "Reservation",
    :description => description,
    :custom_field_values => {36 => self.custom_field_value(36).to_s})

where 36 is the ID of the target custom field.

I'm not sure if the to_s is required.

**Comment by ElskerDane** [comment]
thanks for posting your solution!!  :)

**Comment by carukc** [comment]
No problem... Very glad to help where I can...  Thank you for redmine_stats... We get allot of use out of it :) .. at some point we're going to try to get it working with postgres and will definitely offer that back too.

**Comment by ElskerDane** [comment]
Question for you carukc; I am very new to this plugin, and I was wondering how you go about determining what the ids of various items are?  Such as custom fields, statuses, ect.  You seem like a knowledgeable fellow, so I thought I would pose the question to you.  :)

**Comment by carukc** [comment]
Hi Again... sure... very pleased to help.  I went directly to the database for the ID numbers.

custom fields are all stored in the custom_fields table, status IDs are all stored in the issue_status table.  Unfortunately this would not be particularly portable.  There must be an API call that would allow you to get the IDs from the names but I was less worried about portability than I was about just getting something working.

The rest was pure ruby... @issue for the current issue, self for the current object, etc... so I suspect that most things that would work directly within a plugin would work within the custom workflow code.

knowledgeable... hmmm not so sure... I'm very new to ruby myself so am figuring alot of things out as I go

**Comment by ElskerDane** [comment]
Thank you for being so helpful!  I was able to find the IDs I was searching for.

I don't suppose I can push my luck and ask you if you have any idea how to assign other users to an issue?  "User.current" is used in all the examples, but I would like to assign someone besides the current user.  If you have any ideas, they would be much appreciated.

**Comment by carukc** [comment]
Hi, no problem.

The user object seems to have quite a few methods.  How do you want to specify the User?  By ID?  By username?  I found this documentaiton for hte user object: http://www.rubydoc.info/github/redmine/redmine/User

If you want to specify by mail address for example I imagine that it would be a matter of instantiating a user object and then using the appropriate method... any of the .find_by... look promising and then using the returned object to get the user ID.  You might even be able to use that method with the User object noted in the docs but I'm not competent enough yet in ruby to know how all this works.

Does that make sense?  If I can think of another way I'll post here... Please do let me know if you find a solution.

**Comment by ElskerDane** [comment]
Using your guidance @carukc I was able to figure it out!

For example, if you want to set the assignee whenever an issue's status is changed, your code would look like this:

# before_save #
@need_create = status_id_changed? && !new_record?

# after_save #
if @need_create
   assigned_to = User.find_by_login('testuser2')
end

Thanks again for your help!

**Comment by carukc** [comment]
Excellent! I knew that it would be something like that.  Glad to help.
