### ISSUE TITLE
[Feature] Ability to raise a warning or info (similar to raise WorkflowError, “Your message”)

### ISSUE THREAD

**Issue by plapczyn** [anteo/redmine_custom_workflows#39]
It would be nice to be able to raise an info message or warning on save similar to the `raise WorkflowError` hook. This could be useful to help indicate to a user that a field was changed by the workflow plugin, or indicate a non-blocking message, for instance _"Due date is in the past. Is this correct?"_

**Comment by silversmarty** [comment]
I'm interested too ! 
It would be very helpful to inform the user what has been done. I've seen that "flash notice" (as it's the name of this feature) seems a bit heavy to modify directly (http://stackoverflow.com/questions/2701932/accessing-rails-flashnotice-in-a-model), it should be great to have a built-in function in Custom Workflow plugin.

Thanks

**Comment by Spongar** [comment]
I agree.

**Comment by andreabonadei** [comment]
+1 I'm looking forward to this enhancement being added.

**Comment by picman** [comment]
Flash messages can be displayed for a script this way now:
```ruby
  self.custom_workflow_messages[:notice] = 'Custom workflow info'
  self.custom_workflow_messages[:warning] = 'Custom workflow warning'
  self.custom_workflow_messages[:error] = 'Custom workflow error'
```
