### ISSUE TITLE
Debug Code

### ISSUE THREAD

**Issue by TehDuffman** [anteo/redmine_custom_workflows#42]
I freely admit to being a newbie in both Ruby and Redmine. Looking for a way to debug some workflows. I know how to run the ruby shell interactively but try to find out why some workflows are not being called when it seems they should. Is there anyway to walk through the script or see a log of the scripts output?

**Comment by zas0006** [comment]
assuming you are on linux you can do this:

    cd <redmine path>/log
    tail -f production.log

This will let you see the log as you do things in the browser, so when the issue occurs you should be able to see the error that is thrown and go from there.

You can also use 

    raise WorkflowError, "message to user"

to force a blocking pop up on the screen to debug. Very useful when you want to make sure you got into a certain loop, or exited a certain point, and so on.
