### ISSUE TITLE
Example with time_entry.comments

### ISSUE THREAD

**Issue by errogaht** [anteo/redmine_custom_workflows#44]
Please provide an example worcflow where we can check if time_entry.comments.blank?
if time_entry.hours.blank? then check if time_entry.comments.blank? and if blank raise error

**Comment by chibacityblues** [comment]
I use the following before-saving-workflow to set a time entry's comment to something like "Work on $tracker-Ticket #$issue_id ($issue_subject)" if the comment field was left empty. 

**Example:** "Work on Error-Ticket #1234 (Function foo() fails if user does bar)" 

Perhaps this is useful to you. @anteo Feel free to add this to the example workflows
````
if @time_entry.comments.blank?
  unless @time_entry.issue_id.nil?
   @time_entry.comments = "Work on #{@time_entry.issue.tracker.name}-Issue ##{@time_entry.issue.id} (#{@time_entry.issue.subject})"
  end
end
````
