### ISSUE TITLE
Redmine 3.2

### ISSUE THREAD

**Issue by marcoprodata** [anteo/redmine_custom_workflows#45]
This master work with redmine 3.2?

**Comment by marius-balteanu** [comment]
Hello,

I'm using Redmine 3.2.0 and this plugin without any issue for two weeks.

**Comment by archonwang** [comment]
@marius-balteanu 

I write an script to force user to write notes when submit issues with status Rejected. as follows

if @issue.status_id_changed?
if @issue.status_Id==6 && @issue.current_journal.notes.nil?
raise WorkflowError, 'Errors found. Please fill in the notes first! ' unless @issue.current_journal not nil
end
end
Is there something wrong for I always received the error message with contact administrator....

Thanks so much.
