### ISSUE TITLE
Error in pt-br.yml file

### ISSUE THREAD

**Issue by jonramos** [anteo/redmine_custom_workflows#46]
After installed this plugin in redmine 3.1.0, my redmine language changed automatically from PT-BR (Brazilian Portuguese) to PT (Portugal Portuguese) 
When the filename is pt-br.yml, redmine don't use Brazilian Portuguese.

To resolve this, I renamed the pt-br.yml file to pt-BR.yml (according redmine uses in locales folder) and the problem was solved.

**Comment by picman** [comment]
Fixed.
