### ISSUE TITLE
get id of newly created user

### ISSUE THREAD

**Issue by mSttn** [anteo/redmine_custom_workflows#47]
I want to write a custom workflow to assign every newly created user to a certain group, but can't seem to manage to get the user object of the new user.

My code is the following at the moment:
```
group = Group.find(49)
nUser = self
group.users << nUser
```

Group Nr. 49 is obviously the one I want to assign to the new users. For Line 2 I get different errors when trying to save the workflow depending on the version. The one above gives me:
> Workflow script executable after saving observable object contains error: Validation failed: E-Mail muss ausgefüllt werden, Mitgliedsname muss ausgefüllt werden, Vorname muss ausgefüllt werden, Nachname muss ausgefüllt werden

I also tried the following (line 2):
`nUser = User.find(id)`
with this error:
> Workflow script executable after saving observable object contains error: Couldn't find User without an ID

Any help would be really appreciated. Thanks!

**Comment by pyroit** [comment]
Hi,
 try after save: 
User.last

Br

**Comment by mSttn** [comment]
Yes, that did the trick. Thanks a lot!

For anyone interested, my code is now the following:
```
group = Group.find(49)
nUser = User.last
group.users << nUser
```
