### ISSUE TITLE
Custom email subject

### ISSUE THREAD

**Issue by jaimeguzman** [anteo/redmine_custom_workflows#49]
Hi, great plugin

I have a doubt, I'm trying to change the subject without result, actually I used the example 
on FAQ pages:

`  Mailer.custom_email(:to => 'ejemplo@domain.cl', :text_body => 'Hello Friend!').deliver
`
How I can replace the "Custom email" subject, for  my own subject email text?

Regards

**Comment by pyroit** [comment]
have a look here #34

**Comment by jaimeguzman** [comment]
Thanks so much ! 
=)
