### ISSUE TITLE
add email support

### ISSUE THREAD

**Issue by pyroit** [anteo/redmine_custom_workflows#5]
Hi,
beeing able to send email via the custom workflow. I could not find any other soultion than writing my own additional plug in, but this solution is very durty and very static. Mybe something like this can be added to the main source, but far better programmed...

This would be the comand to send a mail:
Mailer.custom_email("add string to mail subject  ", User.find(1), self).deliver   

Please be aware that my extention is highly adapted to my needs and cannot be implemented in your enviroment as is. 

https://www.dropbox.com/s/dt0uoqks8zasbbi/redmine_custom_workflow_email_support.zip?dl=0

Regards
Moritz

**Comment by anteo** [comment]
Thank you, I'll think about it.

**Comment by go2null** [comment]
Not sure that methods should be added to the plugin.  These should be defined in the user's custom workflow.  

What may make sense is the ability to source other custom workflows/rb files so that a user can create a library for reuse.  This could build on the #1 (saving and restoring workflows).

**Comment by anteo** [comment]
It's not possible to refer methods declared in other workflows now (validation of workflow will not pass calls to undeclared methods)
Workflows are not place for declaring helper functions. Maybe it make sense to implement a special type of workflows (e.g. "helper" workflows) which will run before all other workflows in which we can declare needed functions.
Then we can define "Mail helper" workflow and share it in online repository, which I hope implement soon.

**Comment by anteo** [comment]
Added Mailer#custom_email helper in the last (0.1.2) version.
It's available through repository for now.
Check the wiki for usage.
