### ISSUE TITLE
custom email html_body rendering 

### ISSUE THREAD

**Issue by pyroit** [anteo/redmine_custom_workflows#50]
Hi,
has someone tried to pass an html_body? 

```
html = '<h3>headline</h3>
<p>some text.</p>'

Mailer.custom_email(:to => 'user@hotmail.com', :html_body => html).deliver
```

The HTML is passed however not rendered when i receive the email. Can someone give me a hint?

![email](https://cloud.githubusercontent.com/assets/9677935/12866264/3225d070-cd03-11e5-9df9-0c4867dde00c.png)

 many thanks

**Comment by jaimeguzman** [comment]
I'm probably in the same situation of you, I trying to create a template email and when call in the function, maybe is not the best solution, but this can help you fix the html issue. 

```    
Mailer.custom_email(:user => User.find(1), 
              :template_name => 'mailer/mycustomemail', 
              :template_params => {
                :url => "mydomain.cl"
                }).deliver
```

**Comment by pyroit** [comment]
Hi, 
thank you for the information, however I would like to create the layout with the custom workflow plugin. This gives me much more freedom, when performing some changes or adding new layouts.

**Comment by jaimeguzman** [comment]
Yes is true, try to pass you path of your template  in the headers of the custom_email function, I mean
when it execute mailer_patch.rb, using email templates you have more freedom to pass parameters and have a nice personalization of your html code for your custom email. 
```
    module InstanceMethods
      def custom_email(headers={})
     .
     ...
     ......
```
lookup this file, after I check this file I'm more clear how to use the template references.

Good Luck !

**Comment by pyroit** [comment]
Thank you for the feedback. But is still try to figure out how to pass HTML into the email without using a template. According to the FAQ it should work.

**Comment by pyroit** [comment]
Finally got it to work


```

html = '<h3>headline</h3>
<p>some text.</p>'

html = html.html_safe


Mailer.custom_email(:to => 'user@hotmail.com', :html_body => html)
```
