### ISSUE TITLE
How to manipulate date from custom field ?

### ISSUE THREAD

**Issue by msneet** [anteo/redmine_custom_workflows#51]
I need some calculation with date from custom field. However none of these methods works:

```
self.custom_field_values={ 77 => custom_field_value(10) + 1.month}
temp = custom_field_value(10).year
temp = custom_field_value(10).to_i
temp = custom_field_value(10).to_date
temp = custom_field_value(10) + 1
```

I've got error:
`undefined method`+' for nil:NilClass`

How to convert CustomFieldValue object to date? How can I do some calculations with custom field value?

P.S.: i'm trying calculate age from birthdate which is stored in custom field

**Comment by msneet** [comment]
Any thoughts?

**Comment by pyroit** [comment]
I cannot provide you a solution, but whenever I stuck I try to do it in the interactive ruby console. This gives you instant feedback and makes it easier to track down the issue. 

https://github.com/anteo/redmine_custom_workflows/wiki/Frequenly-Asked-Questions#how-can-i-experiment-with-the-issue-interactively

**Comment by picman** [comment]
Very probably no custom field of id 10 exists.
