### ISSUE TITLE
Include watchers on task

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#52]
Hi,

After creating the task must include some users as Watchers. How would this include?

thanks

**Comment by go2null** [comment]
https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#watchers

**Comment by aceccarelli** [comment]
Hello,

I tried this but it did not work the creation of the observer in the new issue created.

Thanks!

- Workflow script executable before saving observable object
```
# = before_save = #
@need_create_uc = status_id_changed? && !new_record?

```


- Workflow script executable after saving observable object
```
if @need_create_uc

  issue = Issue.create!(
    :author => User.current,
    :project_id => 88,
    :tracker_id => 14,
    :assigned_to_id => 21,
    :parent_issue_id => id,
    :subject => "Documentar - #"+id.to_s+" "+subject.to_s)

    issue.add_watcher(50) unless watched_by?(50)
end

```

**Comment by gituser** [comment]
Sorry to resurrect an old issue, but you're doing it wrong.

Here is how to properly do it and add a specific user (id=99 in my case) as a watcher only for new issues:

* Workflow script executable before saving observable object
```
# = before_save = #
@need_create_uc = new_record?
```

* Workflow script executable after saving observable object
```
if (@need_create_uc)
  self.add_watcher(User.find(99)) unless self.watched_by?(User.find(99))
end
```
