### ISSUE TITLE
Update custom field from another observable object

### ISSUE THREAD

**Issue by dimasariyo** [anteo/redmine_custom_workflows#53]
i want to lookup custom field on user observable object and use it on issue. i lookup using issue assign_to_value.
can you help me please ?
Thank you

**Comment by picman** [comment]
You can search directly in custom values.
```ruby
cv = CustomValue.where(customized_type: 'Principal', customized_id: your_user_id,
          custom_field_id: your_custom_field_id).first
value = cv.value if cv
```
