### ISSUE TITLE
How can I force to add notes when I changed status to resolved?

### ISSUE THREAD

**Issue by archonwang** [anteo/redmine_custom_workflows#57]
How can I force to add notes when I changed status to resolved?

thanks.

**Comment by go2null** [comment]
See [Example-Workflows](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows), especially [Error Trapping](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#error-trapping) and [this example](https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows#prevent-closing-an-issue-if-it-has-open-descendants)

**Comment by archonwang** [comment]
@go2null  Thanks. I will try it later and report what I have found.

**Comment by marilawang** [comment]
@go2null but how can i tell, if a note is being add ?

**Comment by jdkemme** [comment]
```ruby
if @issue.status_id==3 #resolved status id
  unless @issue.current_journal.nil? #check if the issue has a journal
    if @issue.current_journal.notes.empty? #test if notes has content
      errors.add :base, 'Cannot resolve issue without comment.'
    end
  end
end
```

**Comment by marilawang** [comment]
@jdkemme thanks, I figured it out too.
