### ISSUE TITLE
not support redmine 3.2.1

### ISSUE THREAD

**Issue by archonwang** [anteo/redmine_custom_workflows#58]
I tested it on Redmine 3.2.1 and it not works..

could you solve it? Thanks so much.

I write an script to force user to write notes when submit issues with status Rejected. as follows

> if @issue.status_id_changed?
>     if @issue.status_Id==6 && @issue.current_journal.notes.nil?
>         raise WorkflowError, 'Errors found. Please fill in the notes first! ' unless @issue.current_journal not nil
>     end
> end

Is there something wrong for I always received the error message with contact administrator....

Thanks so much.

**Comment by zas0006** [comment]
I tried it without the unless ... part and it worked fine. Not sure why that would be needed since the if statement where the raise will occur would be precluded if that part of the statement were true...

**Comment by picman** [comment]
`raise WorkflowError.new('Errors found. Please fill in the notes first! ') unless @issue.current_journal`
