### ISSUE TITLE
Add error messages to server response

### ISSUE THREAD

**Issue by xJom** [anteo/redmine_custom_workflows#59]
I think it would be great to add the error message added in the Custom Workflow when raising WorkflowError, to the server response (422 Unprocessable Entity), instead of just logging it, so you can get the text in the an error dialog box in javascript.

I do not realize if it can be done at all. Anyone willing to take a look?

**Comment by picman** [comment]
It works the same way as StandardError:
```ruby
class WorkflowError < StandardError
  attr_accessor :error

  def initialize(message)
    @error = message.dup
    super message
  end
end
```
