### ISSUE TITLE
Support for Blocks, Precedes, Follows

### ISSUE THREAD

**Issue by ashok31415** [anteo/redmine_custom_workflows#61]
Is there any existing support for assigning blocks, precedes, or follows?

**Comment by picman** [comment]
What do you mean with blocks, precedes and follows?

**Comment by AirTibu** [comment]
Hi,

Yes, it is possible. You should define the issue relation type:
```

relation = IssueRelation.new (
                      :issue_from => @issue, 
                      :issue_to => issue_new,
                      :relation_type => IssueRelation::TYPE_RELATES)
relation.save!

```
**Possible types:**
  TYPE_RELATES      = "relates"
  TYPE_DUPLICATES   = "duplicates"
  TYPE_DUPLICATED   = "duplicated"
  TYPE_BLOCKS       = "blocks"
  TYPE_BLOCKED      = "blocked"
  TYPE_PRECEDES     = "precedes"
  TYPE_FOLLOWS      = "follows"
