### ISSUE TITLE
Project.custom_field_value don't work

### ISSUE THREAD

**Issue by rhervet** [anteo/redmine_custom_workflows#62]
Hi,

My problem is to create a condition (if...end) in a custom worflows about a project custom filed value.

For an issue, it works : "if @issue.custom_field_value(83)=...." but not for a project with "if @project.custom_field_value(83)=....".

I don't understand why...

Thank you for your help.

**Comment by letic** [comment]
Hi there,

I stumble upon the same issue today. When trying to access a project from a timeentry I cannot get the Project Custom Values. Somehow the syntax is different. See #41 or https://github.com/annikoff/redmine_plugin_computed_custom_field/issues/26

I just made a quick test and the solution from above works : 
`custom_value = @project.try(:custom_field_value, ProjectCustomField.find_by_name("Custom").id)`

Hope this help
LeTic

**Comment by annikoff** [comment]
Hi.
Is custom field with ID 83 just a sample, or it is an IssueCustomField?
