### ISSUE TITLE
How change status_id when the status_id has changed

### ISSUE THREAD

**Issue by JoseLuisR** [anteo/redmine_custom_workflows#67]
I want to change the status_id and the assigned_to_id when the status_id_changed has been changed, 

I have this code:
before_save
if  @issue.status_id_changed?
   if @issue.status_id==3   #any status id
       @issue.assigned_to_id=5 #any other status id
        @issue.status_id==20
   end
end
When I check the changes the assigned_to_id==5(it´s changed OK)  but status_id==3(not changed)
I´ve check the old user and the new user (id=5) has authoritation to transiction from status_id=3 to status_id=20

Anybody know how it´s the problem?

**Comment by w0www** [comment]
if issue.status_id_changed? && issue.status_id == 3
 issue.assigned_to_id = 5
 issue.status_id = 20
end

the problem is that you have issue.status_id == (double).

**Comment by picman** [comment]
Yes, this's a problem.
```ruby
@issue.status_id==20
```
