### ISSUE TITLE
Find Status ID's in advance

### ISSUE THREAD

**Issue by kenan3008** [anteo/redmine_custom_workflows#70]
Is it possible to find ID's of statuses of a tracker and store them in variables in advance so that I don't have to write code that is dependent on specific ID's only. I would like it to be more portable.
Could someone please give me an example?

**Comment by pyroit** [comment]
maybe not quite what you are locking for, but this helps me to make my code more readable:
```
irb(main):009:0> IssueStatus.find_by_name("Rejected").id
=> 6

```
```
irb(main):011:0> IssueStatus.find_by_name("Rejected")
=> #<IssueStatus id: 6, name: "Rejected", is_closed: true, position: 6, default_done_ratio: nil>
```

If you just wand to increase the status by one position you could do it like this (but this will not follow the worklow set up in redmine)

```
self.status_id = IssueStatus.find_by_position(self.status.position + 1)
```

Or have a look here [FAQ](https://github.com/anteo/redmine_custom_workflows/wiki/Frequenly-Asked-Questions) 
`new_statuses_allowed_to(user=User.current, include_default=false) -- Returns an array of statuses that user is able to apply`
