### ISSUE TITLE
parent_issue_id

### ISSUE THREAD

**Issue by boki69** [anteo/redmine_custom_workflows#71]
Hi,

If an issue created by copy, I would like to set the parent_issue_id to copied_from issue id. In redmine 2.2.2 I can't set it. My code:

`
# before save

if @copied_from.present? and self.new_record?
    self.parent_issue_id=@copied_from.id.to_s
end
`
Nothing happened... 

I tried to show the value of self.parent_issue_id with this code, but the property value is ""

'
if @copied_from.present? and self.new_record?
    self.parent_issue_id=@copied_from.id.to_s
   raise WorkfloeError , 'Property: ' + self.parent_issue_id.to_s
end
'

Please help me, to resolve my problem.

Thanks!

**Comment by picman** [comment]
I think that the id is stored here:
```ruby
@issue.parent_id
```
and not here
```ruby
self.parent_issue.id
```
