### ISSUE TITLE
Workflow submit json external

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#72]
You can create a workflow that makes a json post in a given url is the inclusion or modification of a task?

The idea is that JSON has some data that can be defined.
 
Example:
{
   "issue": {
     "Project", "Project Name"
     "Subject", "Example"
     "Author": "email_from@email.com"
     "Description": "Description detailed"
     "Assigned_to": "email_to@email.com"
     "Status": "New"
     "Notes": "New notes"
   }
}

Thanks!

**Comment by picman** [comment]
How about this:
```ruby
require 'net/http'
require 'uri'

json = %{
  {
   "issue": {
     "Project", "Project Name"
     "Subject", "Example"
     "Author": "email_from@email.com"
     "Description": "Description detailed"
     "Assigned_to": "email_to@email.com"
     "Status": "New"
     "Notes": "New notes"
   }
  }
}

uri = URI.parse('http://localhost:3000')
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new(uri.request_uri,initheader = {'Content-Type' => 'application/json'})
request.body = json
response = http.request(request)
Rails.logger.info response.body
```
