### ISSUE TITLE
ошибка при установке модуля

### ISSUE THREAD

**Issue by nonickDev** [anteo/redmine_custom_workflows#8]
Cтолкнулся вот с такой проблемой при установке плагина.

```
    bundle install --without development test
    bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production

    ...
    ...
    ...
     == 20120831064944 CreateExampleWorkflow: migrating ============================
     rake aborted!
     StandardError: An error has occurred, all later migrations canceled:

     undefined method `author` for
```

Environment:
==========

  Redmine version                3.0.3.devel
  Ruby version                   2.1.6-p336 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.9
  redmine_checklists             3.1.1
  redmine_custom_workflows       0.1.1
  redmine_gitlab_hook            0.1.3

ruby установkен через rvm

**Comment by anteo** [comment]
Обновитесь с репозитория, должно заработать
