### ISSUE TITLE
Workflow works in version 2.6.1 Redmine but don't work in version 3.3.2 Redmine

### ISSUE THREAD

**Issue by aceccarelli** [anteo/redmine_custom_workflows#81]
Hi!

This workflow was error in Redmine 3.3.2

<pre>
if subject.present?
    if closing? && descendants.find { |d| !d.closed? }
        errors.add '', 'Cannot close an item with Open children.'
    end
end</pre>

Error

![error](https://cloud.githubusercontent.com/assets/2286593/23750461/dedb7adc-04ab-11e7-8ab5-8e3f8665b2dd.PNG)

Thanks!

**Comment by aceccarelli** [comment]
Hi, this problem is the unique for to the migration of the redmine. If you can i help me, thanks!

**Comment by boki69** [comment]
Hi, try to change this line:
`errors.add '', 'Cannot close an item with Open children.'`
to:
`errors.add(:base,"Cannot close an item with Open children.")`
