### ISSUE TITLE
Compatability with new Redmine 3.3.2.

### ISSUE THREAD

**Issue by xantyp** [anteo/redmine_custom_workflows#84]
Hello, is there any chance to make this great plugin compatible with new Redmine 3.3.2?
Or it is compatible and I'm doing something wrong?
When installing, in console it throws:
```
NameError: uninitialized constant RedmineCustomWorkflows::GroupPatch::CustomWorkflow
```
My configuration is:
```
  OS: Windows Server 2012 R2 Datacenter
  Redmine version                3.3.2.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
  Git                            2.7.4
```

**Comment by demiurg85** [comment]
looks like you are doing something wrong. This plug-in is compatible with Redmine 2.x.x, 3.x.x
OS: Centos 6
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.1

**Comment by xantyp** [comment]
Thanks for your response, I'll try to solve it somehow.
