### ISSUE TITLE
Preventing issue attachments to be deleted

### ISSUE THREAD

**Issue by liawmike** [anteo/redmine_custom_workflows#85]
Hello everyone,

Custom workflow has attachments observables and therefore it is possible to add some validation on "before destroy" attachments.
In this case, for testing purposes only, I'm raising a WorkflowError exception but redmine shows a internal server error.
In the logs I can see the custom workflow is working and the error is there - but unlike issues (the exception is presented on top of the page) with attachments I get only a general browser error.

Is there another way to perform this?
Thanks in advance!

- Mike

**Comment by liawmike** [comment]
Here are some updates:
- I made a mistake and changed the observable object to "Issue Attachment"
- This way I no longer see an error page after removing attachments but rather the issue itself with the attachment removed (looks like no exception has been raised at all!!)
- But in the log there lines indicating that a exception has been raised - nonetheless redmine completes the attachment removal...

Shouldn't redmine halt the attachment deletion due to an exception risen?

Mike

**Comment by nayefeb** [comment]
> Here are some updates:
> 
> * I made a mistake and changed the observable object to "Issue Attachment"
> * This way I no longer see an error page after removing attachments but rather the issue itself with the attachment removed (looks like no exception has been raised at all!!)
> * But in the log there lines indicating that a exception has been raised - nonetheless redmine completes the attachment removal...
> 
> Shouldn't redmine halt the attachment deletion due to an exception risen?
> 
> Mike

I think I just had the same issue when trying to prevent a Relation from being removed. My code was as per the following:

```
if self.issue_to_id
 if Issue.where(:id=>self.issue_to_id.to_i).first.status_id == 2 || Issue.where(:id=>self.issue_from_id.to_i).first.status_id == 2
  throw(:abort)
 end
end
```

I've used the [throw(:abort)] to cancel the action from a user who is trying to remove a Relation from an Issue with Status_id = 2. 

Even though Redmine Page still removes the relation, however when refreshing the page, the relation appears back again. 

Just posting this code in the hope it would help someone.

**Comment by picman** [comment]
Return `false` from the _before destroy_ script.
Related to #275.
