### ISSUE TITLE
Rendering bug after upgrading to Redmine 3.4.2

### ISSUE THREAD

**Issue by dalekgamma** [anteo/redmine_custom_workflows#88]
redmine_custom_workflows       0.1.6

![image](https://user-images.githubusercontent.com/30634476/28840253-658cb4da-76c4-11e7-843f-314180b69412.png)

**Comment by picman** [comment]
I've created a pull request. However, the plugin seems to be unmaintained. 

https://github.com/anteo/redmine_custom_workflows/pull/95

**Comment by antopgs** [comment]
![image](https://user-images.githubusercontent.com/37363516/43760903-bd6a2f38-9a23-11e8-90cf-538fc3079e85.png)
Same issue here when upgrading to 3.4.x

**Comment by RobertoCesar** [comment]
Same issue, using version 3.4.6-2. If someone could fix the problem, could you please send me the fix (supposing the plugin is not mainteined anymore)...

**Comment by picman** [comment]
Try this: https://github.com/picman/redmine_custom_workflows

**Comment by picman** [comment]
Yes, the filename changed.

**Comment by Cavva79** [comment]
some Pr fixes this bug for example my #101

**Comment by picman** [comment]
Fixed.
