### ISSUE TITLE
Custom workflow for @time_entry doesn't raise on submit of issue form if spent time subform filled

### ISSUE THREAD

**Issue by TrumanRu** [anteo/redmine_custom_workflows#89]
subj.

Redmine 3.3.3
Redmine Custom Workflow plugin 0.1.6

**Comment by boki69** [comment]
This is my problem too. 

Redmine 3.4.2
latest CustomWorkflow plugin

**Comment by picman** [comment]
I can't reproduce it in v1.0.0. If a spent time is logged in the issue's edit form, the workflow scripts are correctly called. If you log a time entry out of issue form, directly form the menu, scripts are called only in case of _Time entry_ or _<shared code>_ are selected as the observable object.

**Comment by TrumanRu** [comment]
@picman where did you get v1.0.0 of redmine_custom_workflows plugin?

**Comment by picman** [comment]
The branch devel-1.0.0. Redmine 4 required.
https://github.com/anteo/redmine_custom_workflows/tree/devel-1.0.0
