### ISSUE TITLE
How to Redirect after issue save

### ISSUE THREAD

**Issue by axellerater** [anteo/redmine_custom_workflows#93]
Hello!

I've been using this plugin to automate a lot of the workflow but I would like to know if there is any way I could redirect a user to log its time after he sets a ticket on a certain status or if I could receive any suggestions on doing something similar.

I'm using Redmine 2.6, if it's relevant in some way.

**Comment by picman** [comment]
Something like this?

```ruby
redirect_to project_time_entries_path(@issue.project, :issue_id: @issue.id)
return
```
