### ISSUE TITLE
compatibility with redmine 3.4.3

### ISSUE THREAD

**Issue by sro70** [anteo/redmine_custom_workflows#94]
Is this plugin also compatible with redmine 3.4.3? I tried to migrate database from 3.1.1 but after plugin migration it is not listed in plugins list. No errors detected while migration processed.

**Comment by picman** [comment]
It seems to be working at least in my case:
![image](https://user-images.githubusercontent.com/779003/34160411-1dc23c66-e4cd-11e7-95e1-261143638a16.png)

Check the plugin placement `redmine/plugins/redmine_custom_wokflows`, access rights and the production.log.

**Comment by sro70** [comment]
Thank you for your answer. Yes, you're right: it's working. I used wrong version (0.1.5) of the plugin.
