### ISSUE TITLE
My Custom WorkFlow Script Does Not Work

### ISSUE THREAD

**Issue by destiny931** [anteo/redmine_custom_workflows#97]
Hello,
I am trying to create a custom workflow but I can't get it to work.  Here is what I'm trying to do:

I have a status called To Do and its status id is 15.  I have a custom field called action and one of the values for this field can be set to New. 

I am trying to accomplish the following:
 When the status changes to TO DO, changed the action to NEW.  

Here is my custom flow script.  Can anyone tell me what I'm doing wrong?

if @issue.status_id_changed?
  if @issue.status_id==15
   custom_field_value(9)  =='New'     
  end
end

**Comment by destiny931** [comment]
Can anyone help me with this?

**Comment by liawmike** [comment]
In order to change a custom field value you should use this syntax:
@issue.custom_field_values = {'9' => 'New'}

**Comment by destiny931** [comment]
@liawmike Thank you so much!!! That worked!!!!
