### ISSUE TITLE
Allow send attachments in email

### ISSUE THREAD

**Issue by w0www** [anteo/redmine_custom_workflows#98]
We need to send a report email all weeks. This email have an attachment like CSV. 

I do an update in your mailer_patch.rb and add this lines after "def custom_email(headers...)"

csv = headers.delete :csv
attachments['informe.csv'] = {mime_type : 'text/csv', content: csv} if csv

**Comment by picman** [comment]
Please create a pull request.

**Comment by w0www** [comment]
sorry picman this code was for a private bussinees and now i dont have the code that i developed. If u need help i can do this again in my freetime.

**Comment by picman** [comment]
I think that it's not a commonly required feature, so I'd leave it as it is.
