### ISSUE TITLE
How to avoid security errors for anonymous user during mail handler processing

### ISSUE THREAD

**Issue by Niremizov** [anteo/redmine_custom_workflows#99]
Is it posible to change status by workflow if:

* project is private,
* current user is anonymous,
* issue edited throught mail handler email processing.

Currently I use this workflow:

```
user = User.current
self.status_id = 1 if (user.anonymous? and self.status_id == 5)
```

This rule exectued during email processing, inside logs:

> MailHandler: an unexpected error occurred when receiving email: Failed to save the record

If project would be made public rule seems to work. But is it possible if project is private?

**Comment by picman** [comment]
If I understand correctly you're trying to update an issue of a private project and as expected Redmine refuses to update the issue. How is it related to this plugin?
